src/Compute/Metadata.php
src/Compute/Metadata/Readers/StreamReader.php
tests/ComputeMetadataTest.php

Adding GCE Metadata lib

---

docs/toc.json
src/ClientTrait.php
src/Logging/Connection/ConnectionInterface.php
src/Logging/Connection/Rest.php
src/Logging/Connection/ServiceDefinition/logging-v2-beta1.json
src/Logging/Entry.php
src/Logging/Logger.php
src/Logging/LoggingClient.php
src/Logging/Metric.php
src/Logging/PsrLogger.php
src/Logging/Sink.php
src/RequestBuilder.php
src/ServiceBuilder.php
tests/Logging/Connection/RestTest.php
tests/Logging/LoggerTest.php
tests/Logging/LoggingClientTest.php
tests/Logging/MetricTest.php
tests/Logging/PsrLoggerTest.php
tests/Logging/SinkTest.php

Hey all, looking to get some feedback on the structure of the logging API before finishing up the underlying code.
In addition to this code I am planning on implementing a thin monolog handler.

Introduce Logging API

---

composer.json

closes https://github.com/GoogleCloudPlatform/gcloud-php/issues/81

upgrade guzzlehttp/psr7

---

composer.json
scripts/release-generator

Usage:
`./scripts/release-generator release <version>`

Add console app for generating releases

---

docs/toc.json
src/BigQuery/InsertResponse.php
src/BigQuery/Table.php
tests/BigQuery/InsertResponseTest.php
tests/BigQuery/TableTest.php

closes https://github.com/GoogleCloudPlatform/gcloud-php/issues/83

add ability to stream rows into bigquery tables

---

scripts/deploy-docs.sh

@dwsupplee @jdpedrie I'll ping you on chat about this.

Fix deploy-docs script.

---

src/Datastore/EntityMapper.php

Bugfix for $key is undefined

---

src/BigQuery/Table.php
src/NaturalLanguage/NaturalLanguageClient.php
src/Storage/Acl.php
src/Storage/Bucket.php
src/Storage/StorageObject.php
src/Vision/Image.php
src/Vision/VisionClient.php
tests/BigQuery/TableTest.php
tests/NaturalLanguage/NaturalLanguageClientTest.php
tests/Storage/BucketTest.php
tests/Storage/StorageObjectTest.php

closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/117
Could I please get some eyes on this to make sure I haven't missed anything? :)

rename Object -> StorageObject

---

src/Storage/Connection/ConnectionInterface.php
src/Storage/Connection/Rest.php
src/Storage/StorageObject.php
tests/Storage/Connection/RestTest.php
tests/Storage/StorageObjectTest.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/108
@cedricziel how does this look to you? :)

Add object copy operation

---

composer.json
docs/manifest.json
docs/toc.json
scripts/release-generator
src/ServiceBuilder.php

Version 0.8.0

---

src/RequestWrapper.php
tests/RequestWrapperTest.php

Fixes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/145

return full message instead of truncated with guzzle exceptions

---

src/Datastore/Operation.php
tests/Datastore/OperationTest.php
tests/fixtures/datastore/entity-result-no-properties.json

References issue #147 regarding non-existent properties index in array.

Added a check for properties key in entities

---

src/Logging/Logger.php
tests/Logging/LoggerTest.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/140
@tmatsuo PTAL :)

Add entries method to logger

---

appveyor.yml
appveyor_install_php.ps1
tests/Logger/AppEngineFlexHandlerTest.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/122

Introduce appveyor for windows testing

---

src/Datastore/Operation.php
src/Datastore/Transaction.php
tests/Datastore/OperationTest.php
tests/Datastore/TransactionTest.php

Fixes #161 
@dwsupplee @layoaster PTAL

Implement Transaction rollback

---

src/Logging/V2/ConfigServiceV2Api.php
src/Logging/V2/LoggingServiceV2Api.php
src/Logging/V2/MetricsServiceV2Api.php

As requested in https://github.com/GoogleCloudPlatform/google-cloud-php/pull/142

Regenerate Logging with Stackdriver rename

---

src/Logging/Connection/ServiceDefinition/logging-v2-beta1.json

Renaming some APIs to Stackdriver brand

Stackdriver product rename

---

src/RequestWrapper.php
tests/RequestWrapperTest.php

For reference: https://github.com/GoogleCloudPlatform/gcloud-common/issues/179

update user-agent string

---

src/Datastore/DatastoreClient.php
src/Datastore/Operation.php

Stop setting default readConsistency

---

docs/home.html

closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/159

home.html gcloud -> google-cloud

---

docs/manifest.json
src/ServiceBuilder.php

* Google Cloud Storage now includes several new methods: `Bucket::compose()`,
`StorageObject::rewrite()` and `StorageObject::rename()` which enable you to 
better manage your storage objects. (#169)
* Google Cloud Storage now offers the ability to use user-supplied encryption
keys. (#169)
* Google Cloud Datastore now supports the
[Datastore Emulator](https://cloud.google.com/datastore/docs/tools/datastore-emulator),
which can be enabled by setting the environment variable
`DATASTORE_EMULATOR_HOST`. (#181)
* Datastore no longer sets `readConsistency` to `EVENTUAL` on lookups and queries.
Instead, Datastore allows the API to determine the best option. Users may still
choose one or the other as before. (#174 and #184)
* The documentation in Datastore has been updated to be more in line with …

Prepare v0.10.0

---

src/Datastore/Query/Query.php
tests/Datastore/Query/QueryTest.php

fix projection path

---

dev/src/DocGenerator/Parser/CodeParser.php

Fixes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/196

Fix outputName

---

src/Datastore/Entity.php
src/Datastore/EntityMapper.php
src/Datastore/Operation.php
src/Datastore/Query/Query.php
tests/Datastore/EntityMapperTest.php

When `meaning` field was populated, field mapping was incorrect.
Fixes #192.

Fix property mapping on lookup/query.

---

src/PubSub/IncomingMessageTrait.php
src/PubSub/Subscription.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/207

fix docblocks

---

src/Storage/Connection/ServiceDefinition/storage-v1.json
src/Storage/StorageClient.php

product refresh

---

src/BigQuery/Connection/ConnectionInterface.php
src/BigQuery/Connection/Rest.php
src/BigQuery/Table.php
tests/BigQuery/Connection/RestTest.php
tests/BigQuery/TableTest.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/215

bigquery: add table update

---

src/BigQuery/JobConfigurationTrait.php

Fix capitalization of namespace

---

docs/manifest.json
src/ServiceBuilder.php

Draft release notes. Please edit as necessary.
----
* Introducing gRPC Support for Google Cloud Pub/Sub and Google Cloud Logging!
If your server has the [gRPC](https://grpc.io) PHP extension installed, your
Pub/Sub and Logging messages will be sent over gRPC rather than HTTP/REST.
gRPC is great for high-performance, low-latency applications, and is highly
recommended in cases where performance and latency are concerns. (#210 and
#217)
* Google BigQuery now supports updating tables. Use
`Google\Cloud\BigQuery\Table::update()` to modify existing tables. (#216)
* Google Cloud PHP now offers a Datastore Session Handler. (#213)
* Google Cloud Datastore now allows setting of the namespace ID when creating
keys and when executing queries. It is still advised that you set your
namespace ID when …

Prepare v0.12.0

---

src/RequestBuilder.php

Remove URI options from available options

---

src/PubSub/Connection/Grpc.php
src/PubSub/V1/PublisherClient.php
src/PubSub/V1/SubscriberClient.php

Fixes issues with sslCreds and credentialsProvider
Renames XApi classes to XClient
Adds leading backslashes to doc types

Regenerate pubsub with latest vkit

---

composer.json

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/255

upgrade auth

---

src/Logging/V2/ConfigServiceV2Client.php
src/Logging/V2/LoggingServiceV2Client.php
src/Logging/V2/MetricsServiceV2Client.php
src/PubSub/V1/PublisherClient.php
src/PubSub/V1/SubscriberClient.php

- Include note about experimental status
- Remove hardcoded gax version
- Update name of project format function
- Comment updates from protos

Regenerate logging and pubsub vkits

---

src/NaturalLanguage/Connection/Rest.php
src/NaturalLanguage/Connection/ServiceDefinition/language-v1.json
tests/system/NaturalLanguage/AnalyzeTest.php
tests/system/NaturalLanguage/NaturalLanguageTestCase.php

updates Natural Language service definition to v1, adds tests

---

composer.json
src/Logging/V2/ConfigServiceV2Client.php
src/Logging/V2/LoggingServiceV2Client.php
src/Logging/V2/MetricsServiceV2Client.php
src/Logging/V2/resources/logging_service_v2_client_config.json
src/PubSub/V1/PublisherClient.php
src/PubSub/V1/SubscriberClient.php
src/PubSub/V1/resources/subscriber_client_config.json

- Fix method samples for paged methods
- Support additional options in Client constructor
- Include new logging method
- Update google/gax and google/proto-client-php versions

Regenerate Pubsub and Logging

---

composer.json
src/Speech/V1beta1/SpeechClient.php
src/Speech/V1beta1/resources/speech_client_config.json

Note: depends on https://github.com/GoogleCloudPlatform/google-cloud-php/pull/305
This is only the generated SpeechClient - I have not tried to add support for automatically switching to grpc when available.

Add support for Speech

---

src/Speech/V1beta1/SpeechClient.php

This should fix the build error caused by the missing comment

Add comment to getOperationsClient method

---

src/Storage/Bucket.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/331

include null as valid data type

---

src/NaturalLanguage/NaturalLanguageClient.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/337

correct analyzeEntities doc string 

---

src/Translate/TranslateClient.php
tests/unit/Translate/TranslateClientTest.php

Omit `model` if not set

---

docs/manifest.json
src/ServiceBuilder.php

* Added a Cloud Storage stream wrapper. This stream wrapper enables you to
interact with cloud storage objects with PHP's built-in file functions, such
as `file_get_contents` and `fopen`. For more information, see PHP's
[streamWrapper documentation](http://php.net/manual/en/class.streamwrapper.php).
(#323)
* Added support for per-object storage classes. (#341)
* Fixed bug in which translate calls failed due to an invalid parameter. (#344)
* Introduced support for Stackdriver Error Reporting via gRPC. (#309)

Prepare v0.21.0

---

src/Storage/StreamWrapper.php

Fix php notices in stream wrapper

---

src/Storage/StreamWrapper.php

Ensure that parse_url provides required keys in stream wrapper

---

src/RequestWrapper.php

We received some feedback these rate limit retries should be dropped, so, this drops them :).
/cc @michaelbausor

Remove rate limit retries

---

src/RequestWrapper.php

Looks like we'll be keeping this after all :)
Reverts GoogleCloudPlatform/google-cloud-php#356

Revert "Remove rate limit retries"

---

src/ClientTrait.php
src/JsonTrait.php
src/Logger/AppEngineFlexFormatter.php
src/NaturalLanguage/NaturalLanguageClient.php
src/RequestBuilder.php
src/RequestWrapper.php
src/RestTrait.php
src/Upload/MultipartUploader.php
src/Upload/ResumableUploader.php
tests/unit/JsonTraitTest.php
tests/unit/RequestWrapperTest.php

Add documentation about the expected behavior of encoding type

---

dev/src/DocGenerator/Parser/CodeParser.php

Parse iterator return types

---

dev/src/DocGenerator/Command/Docs.php
dev/src/DocGenerator/TableOfContents.php

#404 was a touch premature, as it turns out.

Fix source code links in docs for real

---

src/ErrorReporting/composer.json
src/Monitoring/composer.json

Add ext-grpc as a dep for services that only provides grpc lib

---

src/BigQuery/BigQueryClient.php
tests/unit/BigQuery/BigQueryClientTest.php

Thanks to @michaelbausor for the report!

BigQuery::jobs() - project to projectId

---

src/Core/composer.json
src/Spanner/composer.json

corrects spanner dependency on core and removes symfony/lock requirement

---

src/Translate/Connection/Rest.php
src/Translate/Connection/ServiceDefinition/translate-v2.json
src/Translate/TranslateClient.php
tests/system/Translate/TranslateTest.php
tests/system/Translate/TranslateTestCase.php

Supercedes #521.
See also #287, #250.

Update Translate service definition, add system tests, remove documentatation for non-existent option

---

src/Trace/TraceSpan.php
tests/unit/Trace/TraceSpanTest.php

Skip creating the labels info until there are labels.

---

src/Storage/StorageObject.php
tests/system/Storage/SignedUrlTest.php
tests/unit/Storage/StorageObjectTest.php

Fix signed URLs for objects with spaces in the name

---

composer.json
dev/src/Release/Command/Release.php

Add support for composer replace

---

CONTRIBUTING.md

See https://github.com/GoogleCloudPlatform/google-cloud-php/issues/531

Fix troubleshooting link

---

src/Storage/StorageObject.php
tests/unit/Storage/StorageObjectTest.php

Fix signed URLs on Windows

---

dev/src/DocGenerator/Parser/CodeParser.php
src/Core/Batch/BatchConfig.php
src/Core/Batch/BatchJob.php
src/Core/Batch/BatchRunner.php
src/ServiceBuilder.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/580
After speaking with @michaelbausor we decided to extract the fix from https://github.com/GoogleCloudPlatform/google-cloud-php/pull/581 into a separate PR as further changes will be required there.

Fix for doc links

---

composer.json
src/Core/composer.json

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/587

Relax auth requirements

---

src/Speech/SpeechClient.php

This feature is now available publicly

Remove whitelist comments from Speech wordTimeOffset feature

---

src/Storage/Bucket.php

Add documentation for custom metadata

---

tests/unit/Spanner/Session/CacheSessionPoolTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/654
@stanley-cheung, please let me know if this resolves the issue for you! :)

Include mock globals

---

src/Speech/V1/resources/speech_client_config.json
src/VideoIntelligence/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
src/VideoIntelligence/V1beta2/README.md
src/VideoIntelligence/V1beta2/VideoIntelligenceServiceClient.php
src/VideoIntelligence/V1beta2/resources/video_intelligence_service_client_config.json

Also update timeout for Speech streaming method

Add video intelligence v1beta2

---

src/BigQuery/Table.php

BigQuery : fix next result token key

---

src/Storage/Connection/Rest.php
tests/unit/Storage/Connection/RestTest.php

Fixes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/667

use JSON API endpoint and pass userProject query string

---

tests/unit/PubSub/Connection/GrpcTest.php
tests/unit/PubSub/Connection/RestTest.php
tests/unit/PubSub/SubscriptionTest.php

Follow up to https://github.com/GoogleCloudPlatform/google-cloud-php/pull/679

Restore subscription update tests

---

src/Language/composer.json
src/Speech/composer.json
src/Vision/composer.json

Require google/gax and google/proto-client in grpc components

---

src/Datastore/Entity.php

Remove redundancy from exists check.

Datastore/Entity: Remove redundancy

---

src/Core/ClientTrait.php
src/Core/RequestWrapperTrait.php
tests/unit/Core/ClientTraitTest.php
tests/unit/Core/RequestWrapperTest.php

Closes: #739
@tmatsuo, thank you for the report. PTAL.

default to anonymous credentials only if failed to obtain ADC

---

composer.json
docs/contents/cloud-videointelligence.json
src/Dlp/composer.json
src/ErrorReporting/composer.json
src/Language/composer.json
src/Logging/composer.json
src/Monitoring/composer.json
src/PubSub/composer.json
src/Spanner/composer.json
src/Speech/composer.json
src/VideoIntelligence/V1/Gapic/VideoIntelligenceServiceGapicClient.php
src/VideoIntelligence/V1/VideoIntelligenceServiceClient.php
src/VideoIntelligence/V1/resources/video_intelligence_service_client_config.json
src/VideoIntelligence/composer.json
src/Vision/composer.json

Note: CI is expected to fail until gax-php 0.26 is released

Add video v1

---

src/Core/ClientTrait.php
src/Firestore/FirestoreClient.php
src/Firestore/composer.json
src/Spanner/SpannerClient.php
tests/unit/Core/ClientTraitTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/749

Clarify gRPC dependencies

---

src/BigQuery/BigQueryClient.php

Fixed a couple busted markdown links.

fix bigquery docs links

---

dev/src/DocGenerator/Parser/CodeParser.php
src/Spanner/Database.php
src/Storage/StreamWrapper.php

I've removed the `else`s when we have already returned something :put_litter_in_its_place:

Clean elses

---

src/Language/LanguageClient.php
src/Speech/SpeechClient.php
src/Translate/TranslateClient.php
src/Vision/VisionClient.php

Update ML client constructor docs

---

src/Trace/README.md

Migration guide being added here: https://github.com/census-instrumentation/opencensus-php/pull/90

Add link for Trace migration guide in OpenCensus' docs

---

src/BigQuery/Table.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/805

Update documentation to include type

---

src/BigQuery/BigQueryClient.php
src/BigQuery/Job.php
src/BigQuery/QueryResults.php

Default Job::queryResults call to 0ms timeout

---

composer.json
src/Bigtable/composer.json
src/Container/composer.json
src/Dataproc/composer.json
src/Dlp/composer.json
src/ErrorReporting/composer.json
src/Firestore/composer.json
src/Language/composer.json
src/Logging/composer.json
src/Monitoring/composer.json
src/OsLogin/composer.json
src/PubSub/composer.json
src/Spanner/composer.json
src/Speech/composer.json
src/Trace/composer.json
src/VideoIntelligence/composer.json
src/Vision/composer.json

This won't work until the gax release.

Bump gax to v0.29.0

---

src/Core/ClientTrait.php
tests/unit/Core/ClientTraitTest.php

Add support for  env var in Project ID detection

---

src/Firestore/FirestoreClient.php
tests/unit/Firestore/FirestoreClientTest.php

Pass correct database name to WriteBatch

---

dev/src/DocGenerator/Parser/CodeParser.php

Prompted by #842.
Currently, when declaring a generic-style return (i.e. `ItemIterator<Foo>`), `Foo` must be a fully-qualified namespace, even when the file is in the same namespace as the declaration.
This is not well enforced in the docs site ([example](https://googlecloudplatform.github.io/google-cloud-php/#/docs/google-cloud/v0.50.1/spanner/spannerclient?method=instances)), resulting in non-clickable names. Additionally, as shown in #842, the current suggested syntax doesn't work well with certain static analysis tools, and probably with some code intelligence.
This change adds support for relative class names in generic return type declarations.
```diff
- * @return ItemIterator<Google\Cloud\Library\Foo>
+ * @return ItemIterator<Foo>
```

Resolve types in same namespace in generic

---

src/BigQuery/BigQueryClient.php
src/BigQuery/Dataset.php
src/Datastore/DatastoreClient.php
src/Datastore/Operation.php
src/Datastore/Transaction.php
src/Logging/Logger.php
src/Logging/LoggingClient.php
src/PubSub/PubSubClient.php
src/PubSub/Topic.php
src/Storage/Bucket.php
src/Storage/StorageClient.php

Update generic return to use relative class names

---

docs/CODEOWNERS

Not sure if this will have any effects for the release process (VERSION and other files appear to be touched when releasing).
Also, not sure if I need to be added as an admin to this repo for this to work.
cc @tmatsuo, @dwsupplee, @jdpedrie

Add PHP Silver Language SWEs as codeowners of Trace/Debugger code

---

src/BigQuery/Exception/JobException.php
src/BigQuery/Table.php
src/Core/GrpcRequestWrapper.php
src/Core/Iam/Iam.php
src/Core/Lock/SymfonyLockAdapter.php
src/Core/RequestBuilder.php
src/Core/RequestWrapper.php
src/Core/Upload/ResumableUploader.php
src/Datastore/DatastoreClient.php
src/Debugger/Breakpoint.php
src/Debugger/Debuggee.php
src/ErrorReporting/Bootstrap.php
src/Firestore/DocumentSnapshot.php
src/Firestore/FirestoreClient.php
src/Firestore/Query.php
src/Logging/Metric.php
src/Logging/PsrLogger.php
src/Logging/Sink.php
src/PubSub/BatchPublisher.php
src/PubSub/PubSubClient.php
src/Spanner/Connection/Grpc.php
src/Spanner/Result.php
src/Spanner/SpannerClient.php
src/Storage/StreamWrapper.php
src/Trace/Trace.php
src/Translate/TranslateClient.php
src/Vision/VisionClient.php

After running [`PHPStan`](https://github.com/phpstan/phpstan) at level 0, it could found some issues with our code, like misspelling classes, unused variables or undefined variables, missing docblocks are more :smile:

Fixes from PHPStan level 0

---

composer.json
src/Bigtable/composer.json
src/Container/composer.json
src/Dataproc/composer.json
src/Debugger/V2/Controller2Client.php
src/Debugger/V2/Debugger2Client.php
src/Debugger/V2/Gapic/Controller2GapicClient.php
src/Debugger/V2/Gapic/Debugger2GapicClient.php
src/Debugger/V2/resources/controller2_client_config.json
src/Debugger/V2/resources/debugger2_client_config.json
src/Dlp/composer.json
src/ErrorReporting/composer.json
src/Firestore/composer.json
src/Language/composer.json
src/Logging/composer.json
src/Monitoring/composer.json
src/OsLogin/composer.json
src/PubSub/composer.json
src/Spanner/composer.json
src/Speech/composer.json
src/Trace/composer.json
src/VideoIntelligence/composer.json
src/Vision/composer.json

cc @chingor13 
We expect tests to fail until proto-client 0.30 is released

Add debugger gapic

---

tests/snippets/Datastore/TransactionTest.php
tests/snippets/Logging/LoggingClientTest.php
tests/snippets/Logging/PsrLoggerTest.php
tests/snippets/Spanner/DatabaseTest.php
tests/unit/BigQuery/DatasetTest.php
tests/unit/BigQuery/TableTest.php
tests/unit/Datastore/OperationTest.php
tests/unit/PubSub/TopicTest.php
tests/unit/Spanner/DatabaseTest.php
tests/unit/Spanner/TransactionTypeTest.php

Simplify returns

---

tests/snippets/Datastore/DatastoreClientTest.php
tests/snippets/Datastore/KeyTest.php
tests/snippets/Datastore/Query/GqlQueryTest.php
tests/snippets/Datastore/Query/QueryTest.php
tests/snippets/Spanner/TransactionTest.php
tests/snippets/Vision/ImageTest.php
tests/system/Datastore/RunQueryTest.php
tests/system/Datastore/RunTransactionTest.php
tests/unit/Core/ArrayTraitTest.php
tests/unit/Core/RequestWrapperTest.php
tests/unit/Datastore/EntityMapperTest.php
tests/unit/Datastore/EntityTest.php
tests/unit/Debugger/BreakpointTest.php
tests/unit/Debugger/MatchingFileIteratorTest.php
tests/unit/Debugger/VariableTableTest.php
tests/unit/Firestore/DocumentSnapshotTest.php
tests/unit/Spanner/KeySetTest.php
tests/unit/Spanner/TransactionTest.php
tests/unit/Spanner/ValueMapperTest.php
tests/unit/Trace/AttributesTest.php

With this PR, I want to propose some assertions improve. Using the `PHPUnit`'s dedicated ones, instead of PHP functions, will give us a better error message for debugging the error, as well reduce some logic and complexity :smile: 
Thanks to [`Rector`](https://github.com/rectorphp/rector) that helped me find them.

Improve assertions

---

src/Core/GrpcTrait.php
src/Firestore/Connection/Grpc.php
src/Logging/Connection/Grpc.php
src/PubSub/Connection/Grpc.php
src/Spanner/Connection/Grpc.php
tests/unit/Core/GrpcTraitTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/725

Pass authHttpHandler through to GAPICs/GAX

---

src/Dlp/V2beta1/resources/dlp_service_rest_client_config.php
src/Spanner/Admin/Database/V1/resources/database_admin_rest_client_config.php
src/Spanner/Admin/Instance/V1/resources/instance_admin_rest_client_config.php
src/Spanner/V1/resources/spanner_rest_client_config.php

Generation has omitted commas after additionalBindings

Fix syntax errors in resources files

---

composer.json
src/Bigtable/composer.json
src/Container/composer.json
src/Dataproc/composer.json
src/Dlp/composer.json
src/ErrorReporting/composer.json
src/Firestore/composer.json
src/Language/composer.json
src/Logging/composer.json
src/Monitoring/composer.json
src/OsLogin/composer.json
src/PubSub/composer.json
src/Spanner/composer.json
src/Speech/composer.json
src/Trace/composer.json
src/VideoIntelligence/composer.json
src/Vision/composer.json

Update to proto-client 0.32 to pick up changes in vision v1 protos

Update proto-client version

---

dev/src/DocGenerator/DocGenerator.php
dev/src/DocGenerator/Parser/CodeParser.php

Fixes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/868
Does removing the if condition seem safe? It seemed removing it fixed the issue above and created no other side effects, but if someone could verify I am not missing anything just to be safe that would be greatly appreciated.

Use correct source link

---

src/Firestore/Connection/Grpc.php
tests/unit/Firestore/Connection/GrpcTest.php

Fix previous transaction protobuf error

---

src/Firestore/WriteBatch.php
tests/unit/Firestore/WriteBatchTest.php

Fixes #901 (and a gap in conformance to API specification).

Allow DocumentReference in WriteBatch

---

src/Core/GrpcTrait.php
tests/unit/Core/GrpcTraitTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/906
/cc @tmatsuo

Correctly handle nested structs when unpacking gRPC values

---

src/Core/Testing/Snippet/Coverage/ExcludeFilter.php
src/Core/Testing/Snippet/Coverage/Scanner.php
src/Core/Testing/Snippet/Fixtures.php
src/Core/Testing/Snippet/Parser/Parser.php
src/Core/Testing/Snippet/keyfile-stub.json
tests/snippets/Vision/Annotation/FaceTest.php

These changes support snippet tests in subrepos after the restructuring in https://github.com/GoogleCloudPlatform/google-cloud-php/pull/889

Update Core with changes to support restructure

---

docs/CODEOWNERS

Should fix the auto code review requests by library.

Update paths for CODEOWNERS files

---

tests/Component/TestComposerInstall.php

This got missed because it's scripted to run in cron, and we're not running a test cron right now.

Fix composer integration test

---

Spanner/src/CommitTimestamp.php
Spanner/src/SpannerClient.php
Spanner/tests/Snippet/CommitTimestampTest.php
Spanner/tests/Snippet/SpannerClientTest.php
Spanner/tests/System/WriteTest.php
Spanner/tests/Unit/CommitTimestampTest.php
Spanner/tests/Unit/SpannerClientTest.php

Add support for Spanner Commit Timestamps

---

README.md

Just adding links to packagist and subrepos to make navigation a bit simpler.

Add links to subpackages from README

---

ErrorReporting/src/prepend.php

Fix prepend include path

---

README.md

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/968

Move Google Bigtable back to alpha

---

.gitignore
Firestore/src/ValueMapper.php
Firestore/tests/Unit/ValueMapperTest.php

Add support for instances of \DateTimeInterface

Add support \DateTimeInterface

---

BigQueryDataTransfer/composer.json
Bigtable/composer.json
Container/composer.json
Core/composer.json
Dataproc/composer.json
Dlp/composer.json
ErrorReporting/composer.json
Firestore/composer.json
Language/composer.json
Logging/composer.json
Monitoring/composer.json
OsLogin/composer.json
PubSub/composer.json
Spanner/composer.json
Speech/composer.json
Trace/composer.json
VideoIntelligence/composer.json
Vision/composer.json
composer.json

Isolating this from https://github.com/GoogleCloudPlatform/google-cloud-php/pull/937 to see if we have any better luck with the travis build.

Bump GAX to ^.31

---

BigQueryDataTransfer/src/V1/README.md
Container/README.md
Container/src/V1/README.md
Dataproc/README.md
Dataproc/src/V1/README.md
OsLogin/README.md
OsLogin/src/V1beta/README.md
VideoIntelligence/README.md
dev/src/AddComponent/Readmes.php
dev/src/AddComponent/templates/template-README.md.txt

Fix links to API docs in READMEs

---

Datastore/src/Operation.php
Datastore/tests/Unit/OperationTest.php

Clone key objects when filling to a number

---

BigQueryDataTransfer/composer.json
Bigtable/composer.json
Container/composer.json
Dataproc/composer.json
Dlp/composer.json
ErrorReporting/composer.json
Firestore/composer.json
Iot/composer.json
Language/composer.json
Logging/composer.json
Monitoring/composer.json
Monitoring/src/V3/AlertPolicyServiceClient.php
Monitoring/src/V3/Gapic/AlertPolicyServiceGapicClient.php
Monitoring/src/V3/Gapic/NotificationChannelServiceGapicClient.php
Monitoring/src/V3/NotificationChannelServiceClient.php
Monitoring/src/V3/resources/alert_policy_service_client_config.json
Monitoring/src/V3/resources/alert_policy_service_descriptor_config.php
Monitoring/src/V3/resources/alert_policy_service_rest_client_config.php
Monitoring/src/V3/resources/notification_channel_service_client_config.json
Monitoring/src/V3/resources/notification_channel_service_descriptor_config.php
Monitoring/src/V3/resources/notification_channel_service_rest_client_config.php
OsLogin/composer.json
PubSub/composer.json
Spanner/composer.json
Speech/composer.json
Trace/composer.json
VideoIntelligence/composer.json
Vision/composer.json
composer.json

This needs to wait for a new proto-client-php release with proto updates before merging.

Add Monitoring alert service

---

Core/src/Batch/SysvConfigStorage.php
Core/tests/Unit/Batch/SysvConfigStorageTest.php

Fixes #1008
These can be overridden by setting envvars.

Added default values for the shemaphore and the shared memory

---

README.md

- Updated main readme to list Dialogflow and IoT
- Moved BQDT to restore alphabetical ordering

Update README to list all APIs

---

README.md

Spurred by https://github.com/GoogleCloudPlatform/google-cloud-php/pull/1022

Update DLP example

---

Core/src/Testing/Snippet/Parser/Parser.php
Core/tests/Snippet/TimestampTest.php
dev/sh/tests

Fixes a bug wherein method snippets are excluded from the list of snippets to cover.

Fix snippet coverage

---

Core/src/GeoPoint.php
Core/tests/Unit/GeoPointTest.php
Datastore/src/EntityMapper.php
Datastore/tests/System/SaveAndModifyTest.php
Datastore/tests/Unit/EntityMapperTest.php

Support reading and writing empty geopoint values

---

Speech/src/V1p1beta1/Gapic/SpeechGapicClient.php
Speech/src/V1p1beta1/README.md
Speech/src/V1p1beta1/SpeechClient.php
Speech/src/V1p1beta1/resources/speech_client_config.json
Speech/src/V1p1beta1/resources/speech_descriptor_config.php
Speech/src/V1p1beta1/resources/speech_rest_client_config.php
docs/contents/cloud-speech.json

Add speech v1p1beta1 API

---

Spanner/src/Session/CacheSessionPool.php
Spanner/tests/Unit/Session/CacheSessionPoolTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1070

Ensure releasing a session after pool has been cleared does not error

---

.gitattributes
BigQuery/.gitattributes
BigQueryDataTransfer/.gitattributes
Bigtable/.gitattributes
Container/.gitattributes
Core/.gitattributes
Dataproc/.gitattributes
Datastore/.gitattributes
Debugger/.gitattributes
Dialogflow/.gitattributes
ErrorReporting/.gitattributes
Firestore/.gitattributes
Iot/.gitattributes
Language/.gitattributes
Logging/.gitattributes
Monitoring/.gitattributes
OsLogin/.gitattributes
PubSub/.gitattributes
Redis/.gitattributes
Spanner/.gitattributes
Speech/.gitattributes
Storage/.gitattributes
Trace/.gitattributes
Translate/.gitattributes
VideoIntelligence/.gitattributes
Vision/.gitattributes
dev/src/AddComponent/Command/AddComponent.php
dev/src/AddComponent/GitAttributes.php
dev/src/AddComponent/templates/template-gitattributes.txt

Add .gitattributes file to improve composer archive for umbrella and all subpackages. Also added to the component generator.
I tested this locally using `git archive`.

Add .gitattributes

---

BigQueryDataTransfer/composer.json
Bigtable/composer.json
Container/composer.json
Dataproc/composer.json
Debugger/composer.json
Dialogflow/composer.json
Dlp/composer.json
ErrorReporting/composer.json
Firestore/composer.json
Iot/composer.json
Language/composer.json
Logging/composer.json
Monitoring/composer.json
OsLogin/composer.json
PubSub/composer.json
Redis/composer.json
Spanner/composer.json
Speech/composer.json
Trace/composer.json
VideoIntelligence/composer.json
Vision/composer.json
Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
Vision/src/V1/resources/image_annotator_client_config.json
Vision/src/V1/resources/image_annotator_descriptor_config.php
Vision/src/V1/resources/image_annotator_rest_client_config.php
composer.json

Note: Requires proto file update

Regenerate Vision V1

---

dev/src/DocGenerator/Parser/CodeParser.php
docs/external-classes.json

Follow up to: https://github.com/GoogleCloudPlatform/google-cloud-php/pull/1076

Fix documentation links

---

README.md
VideoIntelligence/README.md

@jdpedrie 
Can you cherrypick this for the release?

Fixed the code example in the README

---

Firestore/src/SnapshotTrait.php
Firestore/tests/Unit/FirestoreClientTest.php

Support special characters in Firestore document paths

---

Translate/README.md

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1134

Fix package name

---

composer.json

Add missing autoloader config for Tasks and tts tests

---

Core/src/Batch/BatchTrait.php

Output the stacktrace as well when catching exceptions

---

Bigtable/src/Connection/ConnectionInterface.php
Bigtable/src/Connection/Grpc.php
Bigtable/src/Connection/LongRunningConnection.php
Bigtable/tests/Unit/Connection/LongRunningConnectionTest.php

Adding lognrunning connection functions.

BIgtable longrunnig connection

---

Logging/src/PsrLogger.php
Logging/tests/Unit/PsrLoggerTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1163

Allow context to handle Throwable interface

---

Bigtable/src/Connection/Grpc.php

This update was necessary for me in order to get RPCs to complete. Does it seem correct?
/cc @mohitq @ajaaym @sduskis

Update CreateInstanceMetadata type

---

Bigtable/src/BigtableClient.php
Bigtable/src/Instance.php
Bigtable/tests/Unit/InstanceTest.php

Replace Protobuf constant with class constant

Bigtable replace proto constant with class constant

---

Storage/tests/System/RequesterPaysTest.php

The requester pays system tests have been broken for some time. This change fixes them.

Fix Storage Requesterpays system tests

---

Bigtable/src/Connection/Grpc.php
Bigtable/src/Instance.php
Bigtable/tests/Snippet/InstanceTest.php
Bigtable/tests/System/BigtableSystemTestCase.php
Bigtable/tests/System/InstanceTest.php
Bigtable/tests/Unit/Connection/GrpcTest.php
Bigtable/tests/Unit/InstanceTest.php

Bigtable delete instance

---

composer.json

@sduskis this should resolve the CI issues for now

Workaround for tests to pass with new warning being triggered in auth

---

Bigtable/src/BigtableClient.php
Bigtable/src/Connection/Grpc.php
Bigtable/src/Instance.php
Bigtable/src/Table.php
Bigtable/tests/Snippet/BigtableClientTest.php
Bigtable/tests/Snippet/InstanceTest.php
Bigtable/tests/Snippet/TableTest.php
Bigtable/tests/System/TableTest.php
Bigtable/tests/Unit/BigtableClientTest.php
Bigtable/tests/Unit/Connection/GrpcTest.php
Bigtable/tests/Unit/InstanceTest.php
Bigtable/tests/Unit/TableTest.php

Bigtable create delete table

---

Bigtable/src/BigtableClient.php
Bigtable/src/Connection/Grpc.php
Bigtable/src/Instance.php
Bigtable/src/Table.php
Bigtable/tests/Unit/BigtableClientTest.php
Bigtable/tests/Unit/Connection/GrpcTest.php
Bigtable/tests/Unit/InstanceTest.php
Bigtable/tests/Unit/TableTest.php

Issues of PHPDoc, PSR-2 code style, unused variables and imports are fixed.

[Bigtable] Housekeeping job to fix minor issues of styles and PHPDoc

---

Bigtable/src/Connection/ConnectionInterface.php
Bigtable/src/Connection/Grpc.php
Bigtable/tests/Unit/Connection/GrpcTest.php

The remaining todos are instance/LRO operations. If this has been helpful, I can go ahead and get those ready too. Just let me know :)
/cc @sduskis @ajaaym

Implement Data/Remaining Table RPCs in connection layer

---

Core/src/Lock/SymfonyLockAdapter.php

Fixes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1199

Update exception messaging and pass in previous exception

---

Bigtable/src/Connection/ConnectionInterface.php
Bigtable/src/Connection/Grpc.php
Bigtable/src/Connection/IamInstance.php
Bigtable/src/Instance.php
Bigtable/tests/Snippet/InstanceTest.php
Bigtable/tests/Unit/Connection/IamInstanceTest.php
Bigtable/tests/Unit/InstanceTest.php

Also fix minor issues of PHPDoc comments for copyrights.

[Bigtable] Add support for getting IamInstance to Instance.php

---

Bigtable/src/Connection/Grpc.php
Bigtable/tests/Unit/Connection/GrpcTest.php

Implement Remaining Instance RPCs in connection layer

---

Bigtable/src/DataClient.php
Bigtable/src/Exception/BigtableDataOperationException.php
Bigtable/src/RowMutation.php
Bigtable/tests/Snippet/DataClientTest.php
Bigtable/tests/System/DataClientTest.php
Bigtable/tests/Unit/DataClientTest.php
Bigtable/tests/Unit/RowMutationTest.php

Bigtable data operation mutate rows

Bigtable data operation mutate rows

---

BigQuery/composer.json
BigQueryDataTransfer/composer.json
Bigtable/composer.json
Container/composer.json
Dataproc/composer.json
Datastore/composer.json
Debugger/composer.json
Dialogflow/composer.json
Dlp/composer.json
ErrorReporting/composer.json
Firestore/composer.json
Iot/composer.json
Kms/composer.json
Language/composer.json
Logging/composer.json
Monitoring/composer.json
OsLogin/composer.json
PubSub/composer.json
Redis/composer.json
Spanner/composer.json
Speech/composer.json
Storage/composer.json
Tasks/composer.json
TextToSpeech/composer.json
Trace/composer.json
Translate/composer.json
VideoIntelligence/composer.json
Vision/composer.json

Replaces #1216.
I used `v1.23` which is not yet released. The next release of the library will make that version available.

Update required version of google/cloud-core

---

Core/src/ClientTrait.php

Fix `Undefined index: suppressKeyFileNotice` error

Fix suppressKeyFileNotice check

---

Core/src/Iterator/PageIteratorTrait.php
Datastore/src/EntityPageIterator.php
Storage/src/ObjectPageIterator.php

Towards: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1272
/cc @yehudahkay would you please be able to check this out and see if it helps improve the performance?

Improve performance of fetching nested resources in an array

---

Core/src/Batch/BatchJob.php
Core/src/Batch/HandleFailureTrait.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1298

Initialize the failure file

---

Storage/src/Bucket.php
Storage/src/Connection/ConnectionInterface.php
Storage/src/Connection/Rest.php
Storage/src/Connection/ServiceDefinition/storage-v1.json
Storage/src/StorageClient.php
Storage/src/StorageObject.php
Storage/tests/Snippet/BucketTest.php
Storage/tests/Unit/BucketTest.php
Storage/tests/Unit/Connection/RestTest.php
tests/system/Storage/BucketLockRetentionPolicyTest.php
tests/system/Storage/HoldObjectsTest.php

This has been reviewed and ported over from the private repository. Please hold off merging until the public beta.
/cc @frankyn, @mohammadnasre

Introduce bucket retention policy and locks

---

Core/src/Lock/FlockLock.php
Core/src/Retry.php
Datastore/src/Key.php
Datastore/tests/Unit/DatastoreClientTest.php
Datastore/tests/Unit/TransactionTest.php
Spanner/tests/System/pcntl/AbortedErrorCausesRetry.php
Spanner/tests/System/pcntl/ConcurrentTransactionsIncrementValueWithExecute.php
Spanner/tests/System/pcntl/ConcurrentTransactionsIncrementValueWithRead.php
Spanner/tests/System/pcntl/forked-process-test.php

Less opcodes for us: https://3v4l.org/gABQl/vld#output vs. https://3v4l.org/fdLjt/vld#output :smile:

Use combined assignment operators when possible

---

Firestore/tests/System/QueryTest.php
Firestore/tests/Unit/QueryTest.php

Remove auxiliary variables when they are return right away

---

Bigtable/tests/Conformance/ReadRowsTest.php

Provide test name in message for conformance test

Provide test name in message for conformance test

---

Storage/tests/System/BucketLockRetentionPolicyTest.php
Storage/tests/System/HoldObjectsTest.php
Storage/tests/System/ManageBucketsTest.php

Towards: https://github.com/googleapis/google-cloud-php/pull/1359

Storage system test fixes

---

Translate/tests/System/TranslateTest.php

Towards: https://github.com/googleapis/google-cloud-php/pull/1359

Translate system test fixes

---

Bigtable/src/DataClient.php
Bigtable/src/Mutations.php
Bigtable/src/RowMutation.php
Bigtable/tests/Snippet/DataClientTest.php
Bigtable/tests/System/DataClientCheckAndMutateRowTest.php
Bigtable/tests/Unit/DataClientTest.php
Bigtable/tests/Unit/MutationsTest.php
Bigtable/tests/Unit/RowMutationTest.php

checkAndMutateRow api implementation

Bigtable: checkAndMutateRow api implementation

---

BigQuery/README.md
README.md

Fix bigquery readme

---

Firestore/src/ValueMapper.php
Firestore/tests/Unit/ValueMapperTest.php

Fixes handling of null values in Firestore.
Replaces https://github.com/googleapis/google-cloud-php-firestore/pull/2.

Fix Firestore null value handling

---

Bigtable/src/DataClient.php
Bigtable/src/Mutations.php
Bigtable/tests/Snippet/DataClientTest.php
Bigtable/tests/System/DataClientMutateRowsTest.php
Bigtable/tests/Unit/DataClientTest.php

Bigtable: mutateRow api

---

Bigtable/README.md
README.md
docs/contents/cloud-bigtable.json

This should follow https://github.com/googleapis/google-cloud-php/pull/1387 :)

Prep Bigtable handwritten client for release

---

dev/src/ReleaseBuilder/ReleaseBuilder.php

This change to the release builder will use the pull request title when generating notes for autosynth PRs if the commit message was not updated.

Use pull request title for autosynth PRs

---

Vision/src/V1/ImageAnnotatorClient.php
Vision/tests/Snippet/V1/ImageAnnotatorClientTest.php
Vision/tests/Unit/V1/ImageAnnotatorClientExtensionTest.php

Add a helper for product search

---

.kokoro/continuous/run-tests.sh
Bigtable/composer.json

Also run google-cloud integraiton in the continuous job

Add erusev/parsedown to require-dev.

---

Spanner/src/Result.php

Addresses: https://github.com/googleapis/google-cloud-php/issues/1208#issuecomment-443085845
/cc @castaneai

Allow retries for initial valid call

---

Iot/src/V1/DeviceManagerClient.php
Iot/tests/Unit/V1/DeviceManagerClientPartialVeneerTest.php
Redis/src/V1/CloudRedisClient.php
Redis/src/V1beta1/CloudRedisClient.php
Redis/tests/Unit/V1/CloudRedisClientPartialVeneerTest.php
Redis/tests/Unit/V1beta1/CloudRedisClientPartialVeneerTest.php
Spanner/tests/Unit/V1/SpannerClientPartialVeneerTest.php

Add unit test coverage to partial veneer methods

---

.gitignore
Asset/synth.py
Dataproc/synth.py
Dialogflow/synth.py
Iot/synth.py
Tasks/synth.py

Fixes synth.py scripts for copyright year replacements.
* Tasks
* IOT
* Dialogflow
* Dataproc
* Asset

Fix synthtool copyright years

---

Storage/src/StorageObject.php
Storage/tests/System/SignedUrlTest.php
Storage/tests/Unit/StorageObjectTest.php

urlencode() Signed URL quotes around saveAsName value.

---

Scheduler/phpunit.xml.dist
dev/src/ComponentIntegration/Command/ComponentIntegration.php

I goofed in the previous PR and forgot to include the test config. Also fixed a problem which caused the integration test to choke on unreleased components.

Fix integration test

---

BigQuery/src/Connection/Rest.php
BigQuery/src/LoadJobConfiguration.php
BigQuery/src/QueryJobConfiguration.php
BigQuery/tests/Snippet/BytesTest.php
BigQuery/tests/Snippet/DateTest.php
BigQuery/tests/Snippet/ExtractJobConfigurationTest.php
BigQuery/tests/Snippet/InsertResponseTest.php
BigQuery/tests/Snippet/LoadJobConfigurationTest.php
BigQuery/tests/Snippet/QueryJobConfigurationTest.php
BigQuery/tests/Snippet/TableTest.php
BigQuery/tests/System/LoadDataAndQueryTest.php
BigQuery/tests/System/RegionalizationTest.php
BigQuery/tests/Unit/BigQueryClientTest.php
BigQuery/tests/Unit/Connection/RestTest.php
BigQuery/tests/Unit/CopyJobConfigurationTest.php
BigQuery/tests/Unit/ExtractJobConfigurationTest.php
BigQuery/tests/Unit/InsertResponseTest.php
BigQuery/tests/Unit/LoadJobConfigurationTest.php
BigQuery/tests/Unit/QueryJobConfigurationTest.php

Cleaned up a bunch of unused imports, hence the high number of changed files.

Add support for BigQuery Clustering

---

AutoMl/composer.json

This will fix the continuous build. I'm investigating means of validating all our autoload statements to keep this from recurring.

Fix AutoML Composer

---

Storage/src/Bucket.php
Storage/src/Connection/ServiceDefinition/storage-v1.json
Storage/src/StorageClient.php
Storage/tests/System/IamConfigurationTest.php

One of the system tests is not passing because of a cache issue. Still working on ironing that out.
/cc @frankyn

Add support for Bucket Policy Only

---

Spanner/src/V1/resources/spanner_grpc_config.json

Reverts googleapis/google-cloud-php#1590
Context:
https://github.com/GoogleCloudPlatform/grpc-gcp-php/pull/33

Revert "Disable gRPC channel pooling pending resolution of issues"

---

Spanner/src/Result.php
Spanner/tests/Unit/ResultTest.php

Fix retry when error occurs in opening executeStreamingSql stream

---

Firestore/src/Connection/Grpc.php
Firestore/src/FirestoreClient.php
Firestore/tests/Snippet/FirestoreClientTest.php

Firestore emulator

---

Firestore/src/FirestoreClient.php
Firestore/src/PathTrait.php
Firestore/tests/System/DocumentAndCollectionTest.php
Firestore/tests/Unit/PathTraitTest.php

Fix list root collections

---

CONTRIBUTING.md

Updating the contributing doc with information about a common error I encounter when I don't have the correct environment variables set up.

Updating the contributing doc

---

WebRisk/README.md

@dwsupplee can you please review? I don't think we need to release this immediately but would be good to at least land in master.

Add note re API whitelist, signup for Beta

---

WebRisk/synth.py

The artman config name will be updated to match the format used by the other services shortly.

Update WebRisk synth config

---

Spanner/tests/Perf/Config.php
Spanner/tests/Perf/Operation.php
Spanner/tests/Perf/README.md
Spanner/tests/Perf/Report.php
Spanner/tests/Perf/pkb/workloada
Spanner/tests/Perf/pkb/workloadb
Spanner/tests/Perf/ycsb.php

Replaces #864.
Everything works in the same manner, but I reorganized it, cleaned up some smells, added a README, made it a bit more robust (on small operation counts, some values will be 0, which caused issues).

Add YCSB performance test

---

Storage/tests/Snippet/StorageObjectTest.php

This is a fix for the component integration test

Ensure a parser instance is available

---

Storage/tests/Unit/SigningHelperTest.php

Prevent transient failures in Signed URL v4 unit tests.

---

docs/contents/cloud-kms.json

correct client name

---

Datastore/src/Connection/Grpc.php

Addresses invalid serialization of timestamps

---

Storage/tests/System/ManageBucketsTest.php

Since we pass bucket metadata as received by and from the API, and since the location type field is an output-only field, the only part of the location type change which impacts our client is the requested system test coverage. This change adds that. Following Ruby's implementation, this change does not modify the storage class available options documentation.
cc @frankyn 
(added do not merge because of Frank's request on the Ruby PR: https://github.com/googleapis/google-cloud-ruby/pull/3303)

test: Add system tests for storage location type

---

Storage/tests/System/ManageBucketsTest.php

test: Fix location type system test expectations

---

PubSub/src/Connection/Grpc.php
PubSub/src/Subscription.php
PubSub/tests/Snippet/SubscriptionTest.php
PubSub/tests/System/ManageSubscriptionsTest.php
PubSub/tests/System/PubSubTestCase.php
PubSub/tests/Unit/Connection/GrpcTest.php
PubSub/tests/Unit/SubscriptionTest.php

fix: Fix update subscription method

---

Core/src/TimeTrait.php
Core/tests/Unit/TimestampTest.php
PubSub/src/Connection/Grpc.php
PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
PubSub/src/Message.php
PubSub/src/Subscription.php
PubSub/src/Topic.php
PubSub/tests/System/ManageSubscriptionsTest.php
PubSub/tests/Unit/MessageTest.php
PubSub/tests/Unit/SubscriptionTest.php

Replaces #1952.
Closes #1845; Closes #1908.

fix: Add documentation for new pubsub features and fix Duration handling.

---

PubSub/src/Subscription.php

docs: Fix subscription expiration ttl documentation

---

PubSub/src/Subscription.php

I put `updateMask` in the wrong param before.

Docs: Fix Subscription::update() argument documentation.

---

Dialogflow/synth.py

Closes: https://github.com/googleapis/google-cloud-php/issues/2390

chore: Explicitly define artman configuration path

---

Storage/tests/System/KmsTest.php

test: Use core encryption testing util

---

dev/src/DocGenerator/Parser/CodeParser.php

It looks like we don't always need to append the projectRoot, it is already included with calls to `getFileName`.

fix: fix doc generator

---

Storage/src/StreamWrapper.php
Storage/tests/System/StreamWrapper/DirectoryTest.php
Storage/tests/System/StreamWrapper/ImageTest.php
Storage/tests/System/StreamWrapper/ReadTest.php
Storage/tests/System/StreamWrapper/RenameTest.php
Storage/tests/System/StreamWrapper/StreamWrapperTestCase.php
Storage/tests/System/StreamWrapper/UrlStatTest.php
Storage/tests/System/StreamWrapper/WriteTest.php
Storage/tests/Unit/StreamWrapperTest.php

Closes #2491; Closes #2492.
@javiermarinros please take a look as well. :)

fix: fix is_dir() and scandir() behavior in stream wrapper

---

BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/tests/System/BigQueryTestCase.php
BigQuery/tests/System/ManageDatasetsTest.php
BigQuery/tests/System/ManageModelsTest.php

Closes #2356, Closes #2334.
Relies on #2376.
The model test is currently failing; waiting on guidance from the API team.

test: add tests for dataset and model encryption config

---

AutoMl/synth.py
Firestore/synth.py
Talent/synth.py
WebRisk/synth.py

ref: #2573, #2578, #2577, #2572.
fixes copyright years in synth.py files.

chore: update synth replacements to fix copyright dates

---

PubSub/src/Connection/Grpc.php
PubSub/src/IncomingMessageTrait.php
PubSub/src/Message.php
PubSub/src/Subscription.php
PubSub/tests/Snippet/MessageTest.php
PubSub/tests/System/ManageSubscriptionsTest.php
PubSub/tests/Unit/Connection/GrpcTest.php
PubSub/tests/Unit/Connection/RestTest.php
PubSub/tests/Unit/MessageTest.php
PubSub/tests/Unit/SubscriptionTest.php

I refactored the Grpc.php unit test file, the provider is too difficult to manage.
Closes #2571.

feat: add support for dead letter policies

---

Tasks/synth.py

fixes breaking changes in #2652.

chore: fix backwards compatibility via synth

---

ErrorReporting/synth.py

Reverts googleapis/google-cloud-php#2665
Non-GA client, can accept breaking changes.

revert: undo synth fixes

---

Firestore/src/PathTrait.php
Firestore/tests/Unit/PathTraitTest.php

fix: allow root-level collection named projects

---

Firestore/src/DocumentSnapshot.php
Firestore/tests/Unit/DocumentSnapshotTest.php

Fixes the getting of null values in Firestore

fix: fix getting null values

---

Storage/src/SigningHelper.php
Storage/src/StorageObject.php
Storage/tests/Snippet/StorageObjectTest.php
Storage/tests/System/SignedUrlTest.php
Storage/tests/Unit/SignedUrlConformanceTest.php
Storage/tests/Unit/SigningHelperTest.php
Storage/tests/Unit/data/signed-url-v4-testdata.json

Closes #2628.
Closes #2626.
Closes #2627.
Closes #2629.

feat: implement new GCS signed URL features

---

.travis.yml

I tested this on my fork with push docs, and stages appeare to continue to function as expected.

chore: remove HHVM testing

---

BigQuery/src/BigQueryClient.php
BigQuery/tests/System/ManageJobsTest.php

docs: add parentJobId to list jobs

---

README.md
SecurityCenter/README.md
SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
SecurityCenter/src/V1/SecurityCenterClient.php
SecurityCenter/synth.py

There are some potential breaking changes in the pipeline here, so let's keep this beta for now to be safe.

chore: move security center to beta

---

BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/src/LoadJobConfiguration.php
BigQuery/src/QueryJobConfiguration.php
BigQuery/tests/Snippet/LoadJobConfigurationTest.php
BigQuery/tests/Snippet/QueryJobConfigurationTest.php
BigQuery/tests/System/LoadDataAndQueryTest.php
BigQuery/tests/System/ManageTablesTest.php
BigQuery/tests/Unit/LoadJobConfigurationTest.php
BigQuery/tests/Unit/QueryJobConfigurationTest.php

feat: add integer range partitioning

---

PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
PubSub/src/Subscription.php
PubSub/tests/System/ManageSubscriptionsTest.php

feat: make dead letter policies available to rest transport

---

Storage/src/SigningHelper.php
Storage/tests/Unit/data/signed-url-v4-testdata.json

fix: add bucket to v4 post policy conditions

---

Core/src/GrpcTrait.php
Core/tests/Unit/GrpcTraitTest.php
Logging/src/Connection/Grpc.php
Logging/tests/Unit/Connection/GrpcTest.php

fix: support http request latency in grpc transport

---

Storage/src/StreamWrapper.php
Storage/tests/System/StreamWrapper/DirectoryTest.php
Storage/tests/Unit/StreamWrapperTest.php

fix: correct object names for root level scandir, readdir

---

BigQuery/tests/Unit/BigQueryClientTest.php
BigQuery/tests/Unit/DatasetTest.php
BigQuery/tests/Unit/JobTest.php
BigQuery/tests/Unit/ModelTest.php
BigQuery/tests/Unit/QueryResultsTest.php
BigQuery/tests/Unit/RoutineTest.php
BigQuery/tests/Unit/TableTest.php

Replaces Argument::any() -> Argument::allOf()
Closes #3111.

test: use stronger assertions for unit tests

---

PubSub/src/Connection/Grpc.php
PubSub/src/Connection/Rest.php
PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
PubSub/src/Subscription.php
PubSub/tests/System/ManageSubscriptionsTest.php
PubSub/tests/Unit/SubscriptionTest.php

feat: add retry policy

---

PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
PubSub/src/Subscription.php
PubSub/tests/System/ManageSubscriptionsTest.php

feat: add support for subscription filtering

---

Asset/src/V1/Gapic/AssetServiceGapicClient.php
Asset/src/V1/resources/asset_service_rest_client_config.php

Fixes https://github.com/googleapis/google-cloud-php/issues/3169

fix: address issues in asset client

---

Storage/src/Connection/Rest.php
Storage/src/StorageClient.php
Storage/tests/System/RequesterPaysTest.php
Storage/tests/System/StreamWrapper/ImageTest.php
Storage/tests/Unit/Connection/RestTest.php

Closes #2563. Replaces #2788.
cc @frankyn

feat: add support for apiEndpoint config

---

RecommendationEngine/synth.py

Closes: https://github.com/googleapis/google-cloud-php/issues/3234

chore: migrate to bazel

---

Storage/src/Connection/ServiceDefinition/storage-v1.json
Storage/src/Lifecycle.php
Storage/tests/Snippet/LifecycleTest.php
Storage/tests/System/ManageBucketsTest.php
Storage/tests/Unit/LifecycleTest.php

feat: add support for noncurrent and custom time lifecycle rules

---

Spanner/src/Session/CacheSessionPool.php
Spanner/tests/Unit/Session/CacheSessionPoolTest.php

fix: fix expiration time key in CacheSessionPool#maintain()

---

BigQuery/src/BigQueryClient.php
Core/src/RequestWrapper.php
Core/src/RequestWrapperTrait.php
Core/tests/Unit/RequestWrapperTest.php
Datastore/src/DatastoreClient.php
Firestore/src/FirestoreClient.php
Logging/src/LoggingClient.php
PubSub/src/PubSubClient.php
Spanner/src/SpannerClient.php
Speech/src/SpeechClient.php
Storage/src/StorageClient.php
Trace/src/TraceClient.php
Translate/src/V2/TranslateClient.php
Vision/src/VisionClient.php

Depends upon: https://github.com/googleapis/google-auth-library-php/pull/299

feat: add support for setting/detecting a quota project

---

Translate/src/V3/resources/translation_service_rest_client_config.php

Closes: https://github.com/googleapis/google-cloud-php/issues/3288

fix: add LRO bindings for rest configuration

---

BigQuery/src/BigQueryClient.php
BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/src/Dataset.php
BigQuery/src/ExtractJobConfiguration.php
BigQuery/src/Model.php
BigQuery/src/Table.php
BigQuery/tests/Snippet/BigQueryClientTest.php
BigQuery/tests/Snippet/ExtractJobConfigurationTest.php
BigQuery/tests/Snippet/ModelTest.php
BigQuery/tests/System/ManageModelsTest.php
BigQuery/tests/System/ManageTablesTest.php
BigQuery/tests/Unit/BigQueryClientTest.php
BigQuery/tests/Unit/ExtractJobConfigurationTest.php
BigQuery/tests/Unit/ModelTest.php
BigQuery/tests/Unit/TableTest.php

feat: add model extract and move job methods to client

---

Firestore/src/CollectionReference.php
Firestore/src/Query.php
Firestore/tests/Snippet/CollectionReferenceTest.php
Firestore/tests/Unit/CollectionReferenceTest.php

feat: add parent() method for CollectionReference

---

Firestore/src/Query.php
Firestore/tests/Snippet/QueryTest.php
Firestore/tests/System/QueryTest.php
Firestore/tests/Unit/QueryTest.php

cc @schmidt-sebastian for review

feat: add support for query limit-to-last

---

Core/src/Testing/System/SystemTestCase.php
Core/tests/Snippet/Testing/System/SystemTestCaseTest.php

test: allow skipping system tests not supported by emulators

---

PubSub/tests/System/ManageIAMPoliciesTest.php
PubSub/tests/System/ManageSubscriptionsTest.php
PubSub/tests/System/ManageTopicsTest.php
PubSub/tests/System/PubSubTestCase.php

test: detect PubSub emulator and skip unsupported system tests

---

Core/src/RestTrait.php
Core/tests/Unit/RestTraitTest.php

feat: add parameter prettyPrint=false to REST API requests

---

BigQuery/src/Connection/ConnectionInterface.php
BigQuery/src/Connection/IamTable.php
BigQuery/src/Connection/Rest.php
BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/src/Table.php
BigQuery/tests/Snippet/TableTest.php
BigQuery/tests/System/ManageTablesTest.php
BigQuery/tests/Unit/Connection/RestTest.php
BigQuery/tests/Unit/TableTest.php

feat: implement IAM for tables

---

Firestore/src/Query.php
Firestore/tests/Unit/QueryTest.php
Firestore/tests/Unit/conformance/v1/query-invalid-operator.json

See https://firebase.googleblog.com/2020/09/cloud-firestore-not-equal-queries.html

feat: add support for the not equal (!=) operator

---

.github/workflows/docs.yml

shamelessly copied from https://github.com/googleapis/gax-php/pull/302

chore: fix docs generation

---

Vision/README.md

Please **merge for me** once approved. Thanks!

chore(vision): fix typo

---

PubSub/src/Connection/Grpc.php
PubSub/tests/Unit/PubSubClientTest.php

Implemented this requested feature: https://github.com/googleapis/google-cloud-php/issues/3656
Closes #3656.

feat: allow user-specified gapic clients

---

Core/src/Batch/SysvConfigStorage.php

fix: do not attempt to serialize SysvSemaphore in PHP8

---

BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/src/LoadJobConfiguration.php
BigQuery/tests/Snippet/LoadJobConfigurationTest.php
BigQuery/tests/System/LoadDataAndQueryTest.php

feat: add support for hive partitioning

---

AUTHENTICATION.md

Fixes: https://github.com/googleapis/google-cloud-php/issues/3833

chore: update auth link

---

AUTHENTICATION.md

Fix Authentication guide link

---

Compute/synth.metadata

should fix https://github.com/googleapis/google-cloud-php/issues/3899

fix: synth.metadata for Compute

---

.github/CODEOWNERS
Container/.repo-metadata.json

chore: add cicd team to codeowners

---

Storage/src/Bucket.php
Storage/src/Connection/ServiceDefinition/storage-v1.json
Storage/tests/System/IamConfigurationTest.php

closes #3564.
Do not merge pending GCS team signoff.
cc @shaffeeullah @tritone

feat: add support for public access prevention

---

README.md

Fixes https://github.com/googleapis/google-cloud-php/issues/4205

chore(docs): Update README for Compute BETA

---

Dataproc/README.md

Closes: https://github.com/googleapis/google-cloud-php/issues/4520

chore: correct dataproc readme

---

.github/.OwlBot.lock.yaml

Related:
https://github.com/googleapis/repo-automation-bots/issues/2792
I'm trying to manually updating the lock file to see if the lock file will be stored in the database.

chore: update owlbot lock

---

AccessContextManager/.OwlBot.yaml
AccessContextManager/owlbot.py

chore(AccessContextManager): migrate to owlbot

---

home.html

docs: fixes syntax error in example code

---

Build/composer.json
composer.json

Should fix failing tests in #4958

fix: autoload for Build metadata

---

.github/.OwlBot.lock.yaml

I thought it's automatic, but I don't see any PRs.
@SurferJeffAtGoogle FYI

chore: update digest for the new php owlbot image

---

Core/src/Batch/HandleFailureTrait.php

feat: allow failure file env-var to prevent logging

---

VideoIntelligence/owlbot.py

See https://github.com/googleapis/google-cloud-php/pull/5044

chore: [VideoIntelligence] fix phpdoc in postprocessing

---

README.md

In preparation for our new version support page

chore: add Supported PHP Versions to the README

---

Storage/src/StorageClient.php

Closes https://github.com/googleapis/google-cloud-php/issues/5163

docs(Storage): Document dual-region bucket support

---

AiPlatform/.repo-metadata.json
CertificateManager/.repo-metadata.json
CommonProtos/CODE_OF_CONDUCT.md
CommonProtos/SECURITY.md
DataCatalog/CODE_OF_CONDUCT.md
DataCatalog/SECURITY.md
Dataplex/.repo-metadata.json
ErrorReporting/CODE_OF_CONDUCT.md
ErrorReporting/SECURITY.md
EventarcPublishing/.repo-metadata.json
Ids/.repo-metadata.json
Logging/CODE_OF_CONDUCT.md
Logging/SECURITY.md
Monitoring/CODE_OF_CONDUCT.md
Monitoring/SECURITY.md
Talent/CODE_OF_CONDUCT.md
Talent/SECURITY.md
VideoLiveStream/.repo-metadata.json
VideoStitcher/.repo-metadata.json
VmMigration/.repo-metadata.json

compliance between all packages

chore: Add Code of Conduct, Security, repo metadata

---

Kms/CODE_OF_CONDUCT.md
Kms/SECURITY.md
Scheduler/CODE_OF_CONDUCT.md
Scheduler/SECURITY.md
Speech/CODE_OF_CONDUCT.md
Speech/SECURITY.md
Tasks/CODE_OF_CONDUCT.md
Tasks/SECURITY.md

Final round of missing COC and Security MD files

chore: add the rest of COC and Security

---

Core/composer.json

chore: raise minimum versions of Guzzle in core

---

Storage/src/Lifecycle.php
Storage/tests/System/ManageBucketsTest.php

feat(Storage): Add OLM matchesPrefix and matchesSuffix

---

Storage/src/Connection/ServiceDefinition/storage-v1.json

Unblocks https://github.com/googleapis/google-cloud-php/pull/5392
Copy pasted the output of [https://storage.googleapis.com/$discovery/rest?version=v1](https://storage.googleapis.com/$discovery/rest?version=v1) into Storage service definition.

chore: updating storage service discovery

---

Core/src/Blob.php
Core/src/GeoPoint.php
Core/src/Int64.php
Core/src/Timestamp.php

Closes: https://github.com/googleapis/google-cloud-php/issues/5420

chore: add attribute to suppress php 8 notice

---

phpunit-perf.xml.dist
phpunit-php5-snippets.xml.dist
phpunit-php5-system.xml.dist
phpunit-php5.xml.dist
phpunit-snippets.xml.dist
phpunit-system.xml.dist
phpunit.xml.dist

Fixing missed attr from PR: https://github.com/googleapis/google-cloud-php/pull/5383 for the issue https://github.com/googleapis/google-cloud-php/issues/5382.

chore: adding name attr to testsuite for phpunit config

---

README.md

Addresses: https://github.com/googleapis/google-cloud-php/issues/5534

chore: updating README with stackoverflow channel

---

Storage/src/Bucket.php
Storage/src/StorageClient.php
Storage/tests/System/ManageBucketsTest.php
Storage/tests/Unit/BucketTest.php

Reverts googleapis/google-cloud-php#5487
I will redo this PR later.

revert: feat(storage): adding tests for autoclass

---

.github/workflows/tests.yaml

This is temporary to workaround https://github.com/grpc/grpc/issues/31772.

chore: pin to grpc-1.49.0

---

Core/src/ExponentialBackoff.php
Core/src/RequestWrapper.php
Core/src/RestTrait.php
Storage/composer.json
Storage/src/Connection/Rest.php

Implemented addition of retry id's on retry request calls by the Retry API.

feat(Storage): GCS Retry Invocation ID header

---

BigQuery/.repo-metadata.json
LongRunning/.repo-metadata.json
Storage/.repo-metadata.json

fixes https://github.com/googleapis/google-cloud-php/issues/5776

chore: update api_shortname for repo-metadata.json

---

GkeMultiCloud/README.md

Quick fix to update to the correct documentation link.

chore: update docs link

---

Spanner/src/Session/CacheSessionPool.php
Spanner/tests/System/SessionTest.php
Spanner/tests/Unit/Session/CacheSessionPoolTest.php

Resolve #5595  and https://github.com/googleapis/google-cloud-php/issues/5364

chore(Spanner): Throw session create exception correctly

---

Datastore/src/Connection/ServiceDefinition/datastore-v1.json

Needed to implement query count (aggregations) in Datastore

chore(datastore): update service discovery

---

AUTHENTICATION.md

fixes https://github.com/googleapis/google-cloud-php/issues/3135

chore(docs): clarify authentication

---

BigQueryStorage/composer.json
BigQueryStorage/metadata/descriptor_fix.php
composer.json

Attempted fix for #5131 
Requires review from @haberman and @mkruskal-google

fix: add internal descriptor override

---

.kokoro/docs/docker/Dockerfile
.kokoro/docs/publish.sh

fixes https://github.com/googleapis/google-cloud-php/issues/5871 and b/279645000
- upgrades PHP 8.0 to latest version
- fails script immediately
- fixes find regex

chore(docs): fix docs gen

---

Core/tests/Unit/ExponentialBackoffTest.php

Added an assertion, to ensure it gets validated and risky warning isn't thrown.

chore: ExponentialBackoff UT throws risky warning

---

StorageInsights/README.md
StorageInsights/composer.json
StorageInsights/samples/V1/StorageInsightsClient/create_report_config.php
StorageInsights/samples/V1/StorageInsightsClient/delete_report_config.php
StorageInsights/samples/V1/StorageInsightsClient/get_location.php
StorageInsights/samples/V1/StorageInsightsClient/get_report_config.php
StorageInsights/samples/V1/StorageInsightsClient/get_report_detail.php
StorageInsights/samples/V1/StorageInsightsClient/list_locations.php
StorageInsights/samples/V1/StorageInsightsClient/list_report_configs.php
StorageInsights/samples/V1/StorageInsightsClient/list_report_details.php
StorageInsights/samples/V1/StorageInsightsClient/update_report_config.php

fix(StorageInsights): Regenerate component to add samples

---

Workflows/.OwlBot.yaml
Workflows/owlbot.py

chore: fix workflows owlbot config

---

DiscoveryEngine/.OwlBot.yaml

chore: configure owlbot for discoverengine:v1

---

Datastore/tests/System/DatastoreMultipleDbTestCase.php

[b/264530286](http://b/264530286)
Seeking to fix the datastore system tests which fail for Kokoro test runs.

chore: fix datastore system tests

---

dev/src/DocFx/Page/PageTree.php
dev/src/DocFx/Toc/NamespaceToc.php
dev/tests/fixtures/docfx/NewClient/toc.yml

Addresses some issues raised in https://github.com/googleapis/google-cloud-php/issues/6321

chore(dev): sort beta clients to bottom, remove new and previous labels

---

Core/composer.json
Core/tests/Unit/RequestWrapperTest.php
Core/tests/Unit/Upload/MultipartUploaderTest.php
Storage/composer.json
Storage/src/StorageObject.php
Storage/tests/Snippet/BucketTest.php
Storage/tests/Snippet/StorageObjectTest.php
Storage/tests/Unit/BucketTest.php
Storage/tests/Unit/Connection/RestTest.php
Storage/tests/Unit/StorageObjectTest.php

chore: suppport guzzle/promises:v2

---

README.md

Woops, we missed this as part of #6014

chore(docs): update min PHP version in README

---

Storage/src/Bucket.php
Storage/src/Connection/ServiceDefinition/storage-v1.json
Storage/tests/System/ManageObjectsTest.php

feat(Storage): Add support for matchGlob listObjects parameter

---

.github/workflows/release.yml
dev/src/Command/SplitCommand.php
dev/src/Packagist.php

feat(dev): automatically submit new packages to packagist

---

PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
PubSub/tests/System/ManageSubscriptionsTest.php
PubSub/tests/System/PublishAndPullTest.php
PubSub/tests/System/SchemaTest.php

Resolves https://github.com/googleapis/google-cloud-php/issues/6459 and https://github.com/googleapis/google-cloud-php/issues/6463

chore(pubsub): Update Pubsub service definition file for REST calls

---

.github/workflows/backwards-compatibility-check.yaml

fixes #6502 
- tested in https://github.com/googleapis/google-cloud-php/pull/6504 and it works as expected

feat(ci): require BREAKING_CHANGE_REASON for breaking labels

---

.github/workflows/backwards-compatibility-check.yaml

fixes https://github.com/googleapis/google-cloud-php/issues/6507

feat(ci): add unexpected major version check

---

dev/src/Command/SplitCommand.php
dev/src/GitHub.php
dev/src/Packagist.php

Needed for the release of https://github.com/googleapis/google-cloud-php/pull/6530

feat(dev): fix packagist submission and add webhook

---

Core/src/Batch/HandleFailureTrait.php
Core/src/Batch/Retry.php
Core/tests/System/Batch/BatchRunnerTest.php
Core/tests/Unit/Batch/HandleFailureTraitTest.php
Core/tests/Unit/Batch/RetryTest.php

Fixes #5308 
*Full Context: b/234355684*

fix(Core): Fix Batch failure file's content with end of line character.

---

AnalyticsAdmin/README.md

chore: [AnalyticsAdmin] update README

---

Vision/src/Annotation/Face.php

chore(Vision): rename print_R to print_r

---

Storage/src/StorageObject.php
dev/src/DocFx/Node/MethodNode.php
dev/tests/Unit/DocFx/NodeTest.php

feat(dev): add see tags to method content

---

BigQuery/src/BigQueryClient.php
BigQuery/src/Dataset.php
BigQuery/src/Job.php
BigQuery/src/Model.php
BigQuery/src/QueryJobConfiguration.php
BigQuery/src/QueryResults.php
BigQuery/src/Table.php
Core/src/Batch/InMemoryConfigStorage.php
Core/src/Batch/InterruptTrait.php
Core/src/Report/EmptyMetadataProvider.php
Core/src/Report/GAEMetadataProvider.php
Core/src/Report/MetadataProviderInterface.php
Core/src/Report/SimpleMetadataProvider.php
Storage/src/Acl.php
Storage/src/Bucket.php
Storage/src/ObjectIterator.php
Storage/src/ObjectPageIterator.php
Storage/src/StorageClient.php
dev/src/DocFx/Node/ClassNode.php
dev/src/DocFx/Page/PageTree.php
dev/tests/Unit/DocFx/PageTest.php
dev/tests/fixtures/docfx/NewClient/V1.Client.SecretManagerServiceClient.yml
dev/tests/fixtures/docfx/Vision/V1.BatchOperationMetadata.yml
dev/tests/fixtures/docfx/Vision/V1.ImportProductSetsResponse.yml
dev/tests/fixtures/docfx/Vision/V1.ProductSearchClient.yml

See #6658 
Fixes in phpdocs and phpdoc parser which were uncovered through running the validation script.

chore(docs): fixes found from running the validator

---

GkeHub/owlbot.py

This should fix https://github.com/googleapis/repo-automation-bots/issues/5247 and unblock #6744

chore: fix GkeHub copy config

---

Datastore/src/Connection/ServiceDefinition/datastore-v1.json

Required for sum/avg feeature.
Updated from https://datastore.googleapis.com/$discovery/rest?version=v1

chore(Datastore): Update Service Definition to revision 20231103

---

dev/templates/phpunit.xml.dist.twig
dev/tests/fixtures/component/CustomInput/phpunit.xml.dist
dev/tests/fixtures/component/SecretManager/phpunit.xml.dist

Ref: https://github.com/googleapis/google-cloud-php/pull/6053

chore: phpunit migrate configuration

---

Firestore/src/FirestoreClient.php

chore(Firestore): database option in FirestoreClient phpdoc

---

AUTHENTICATION.md

Update to coordinate better with Cloud authentication documentation.

docs: Update AUTHENTICATION.md

---

.github/workflows/tests.yaml
Debugger/composer.json
composer.json

should fix [failing GAX test](https://github.com/googleapis/gax-php/actions/runs/8085825118/job/22094210882?pr=546) for the release

chore: update dev dependency kreait/firebase-php

---

SecurityCenter/.OwlBot.yaml

PiperOrigin-RevId: 613632579
b/328626713

chore(SecurityCenter): Update .OwlBot.yaml to release V2

---

Storage/src/StreamWrapper.php
Storage/tests/System/StreamWrapper/WriteTest.php

Fixes https://github.com/googleapis/google-cloud-php/issues/5118

feat(Storage): implement touch on streams

---

Translate/tests/System/V2/TranslateTest.php
Translate/tests/System/V3/TranslationServiceSmokeTest.php

[b/332676509](http://b/332676509)

chore(Translate): fix system tests

---

Storage/tests/System/StreamWrapper/UrlStatTest.php

[b/332676887](http://b/332676887)

chore(Storage): fix system tests

---

Storage/tests/System/RequesterPaysTest.php

[b/315469910](http://b/315469910)

chore(Storage): fix risky test Requester Pays Test

---

Storage/src/Connection/ServiceDefinition/storage-v1.json

1. Used go/jsondiff to compare json
2. System tests pass
Unblocks https://github.com/googleapis/google-cloud-php/issues/7277

feat(Storage): Update Service Definition to enable hierarchical namespace

---

.repo-metadata-full.json
dev/src/Command/AddComponentCommand.php

Fix to ensure `.repo-metadata-full.json` is sorted alphabetically by key

chore: sort repo-metadata-full alphabetically

---

Spanner/src/Connection/Grpc.php
Spanner/src/Database.php
Spanner/tests/Unit/Connection/GrpcTest.php

- Adds a unit test for `Grpc::batchWrite`
- addresses misc review comments

chore(Spanner): add test for batchwrite, address review comments

---

.github/workflows/tests.yaml

fixes tests which started failing because of https://github.com/grpc/grpc/issues/37222

chore: pin grpc to fix failing tests

---

composer.json

fixes https://github.com/googleapis/google-cloud-php/issues/6867 for root package

chore: remove psr/log:3 conflict in root composer

---

.github/workflows/storage-emulator-retry-conformance-tests.yaml
Bigtable/src/ChunkFormatter.php
Bigtable/tests/Unit/SmartRetriesTest.php

addresses https://github.com/googleapis/google-cloud-php/issues/5858#issuecomment-2326879863

fix(Bigtable): prevent race condition

---

ApiKeys/README.md
Batch/README.md
BeyondCorpAppConnections/README.md
BeyondCorpAppConnectors/README.md
BeyondCorpAppGateways/README.md
BeyondCorpClientConnectorServices/README.md
BeyondCorpClientGateways/README.md
BigQueryAnalyticsHub/README.md
BigQueryDataPolicies/README.md
BigQueryMigration/README.md
GSuiteAddOns/README.md
Iam/README.md
SecurityPublicCA/README.md
VmwareEngine/README.md

chore(docs): update README to reflect GA status

---

Firestore/src/DocumentReference.php
Firestore/src/FirestoreClient.php

fixes https://github.com/googleapis/google-cloud-php/issues/7926

fix: [Firestore] deprecation from autoloading deprecated class

---

PubSub/src/PubSubClient.php

fix: add SERVICE_NAME constant to pubsub client

---

Core/src/TimeTrait.php
Core/tests/Unit/TimestampTest.php

fix: Avoid  modify TZ of DateTime

---

Bigtable/src/V2/Client/BigtableClient.php
Bigtable/tests/System/UniverseDomainTest.php

docs(Bigtable): document universe domain client option

---

Vision/README.md

Fixes https://github.com/googleapis/google-cloud-php/issues/8004

docs(Vision): fix sample in README

---

RecaptchaEnterprise/README.md

Fixes README as pointed out in https://github.com/googleapis/google-cloud-php/pull/8281

docs(RecaptchaEnterprise): fix sample in readme

---

PubSub/src/PubSubClient.php

addresses https://github.com/googleapis/google-cloud-php/issues/7735

docs(PubSub): fix client options phpdoc

---

.github/workflows/release.yml
dev/src/Command/SplitCommand.php
dev/src/Packagist.php

fixes https://github.com/googleapis/google-cloud-php/issues/7806

feat(dev): support packagist safe token

---

Core/src/Iterator/ItemIterator.php
Storage/src/Bucket.php
Storage/src/ObjectIterator.php

addresses https://github.com/googleapis/google-cloud-php/issues/6198

docs: add template for ObjectIterator

---

.github/run-package-tests.sh

... I mean comeon, [this line](https://github.com/googleapis/google-cloud-php/blob/78ff024d57c677cfc6a8688d96b21e2c84aadd70/.github/run-package-tests.sh#L48) is 236 characters long!

chore: cleanup run package scripts

---

.repo-metadata-full.json
ShoppingMerchantAccounts/README.md
ShoppingMerchantConversions/README.md
ShoppingMerchantDataSources/README.md
ShoppingMerchantInventories/README.md
ShoppingMerchantIssueResolution/README.md
ShoppingMerchantLfp/README.md
ShoppingMerchantNotifications/README.md
ShoppingMerchantOrderTracking/README.md
ShoppingMerchantProducts/README.md
ShoppingMerchantPromotions/README.md
ShoppingMerchantQuota/README.md
ShoppingMerchantReports/README.md

BEGIN_VERSION_OVERRIDE
ShoppingMerchantAccounts: 1.0.0
ShoppingMerchantConversions: 1.0.0
ShoppingMerchantDataSources: 1.0.0
ShoppingMerchantInventories: 1.0.0
ShoppingMerchantIssueResolution: 1.0.0
ShoppingMerchantLfp: 1.0.0
ShoppingMerchantNotifications: 1.0.0
ShoppingMerchantOrderTracking: 1.0.0
ShoppingMerchantProducts: 1.0.0
ShoppingMerchantPromotions: 1.0.0
ShoppingMerchantQuota: 1.0.0
ShoppingMerchantReports: 1.0.0
END_VERSION_OVERRIDE

chore: promote Shopping Merchant APIs to GA

---

dev/tests/fixtures/component/.OwlBot.yaml
dev/tests/fixtures/component/.OwlBot.yaml_do_not_use

This was causing issues with owlbot automation.  Will temporarily remove and revisit when php team is back
```
Step #6: Error: Cannot overwrite directory '/tmp/tmp-1-QaxZLehqQ3Zj/dest/src/V1' with non-directory '/tmp/tmp-1-MvcwBHYM4NLB/googleapis-gen/google/cloud/kms/v1/cloud.google.com/go/internal/generated/snippets/kms/apiv1/AutokeyAdminClient/GetAutokeyConfig/main.go'.
Step #6:     at Object.checkPathsSync (/usr/src/app/node_modules/fs-extra/lib/util/stat.js:81:13)
Step #6:     at Object.copySync (/usr/src/app/node_modules/fs-extra/lib/copy/copy-sync.js:27:38)
Step #6:     at copyFiles (/usr/src/app/build/src/copy-code.js:850:17)
Step #6:     at copyCodeIntoCommit (/usr/src/app/build/src/copy-code.js:174:9)
Step #6:     at async copyCodeAndAppendOrCreatePullRequest …
```

chore: update dev/tests/fixtures/component/.OwlBot.yaml name so its not picked up by owlbot automation

---

dev/src/DocFx/Node/MethodNode.php
dev/tests/fixtures/docfx/Vision/V1.BatchOperationMetadata.yml
dev/tests/fixtures/docfx/Vision/V1.Block.yml
dev/tests/fixtures/docfx/Vision/V1.FaceAnnotation.Landmark.yml
dev/tests/fixtures/docfx/Vision/V1.FaceAnnotation.yml
dev/tests/fixtures/docfx/Vision/V1.Feature.yml
dev/tests/fixtures/docfx/Vision/V1.OperationMetadata.yml
dev/tests/fixtures/docfx/Vision/V1.SafeSearchAnnotation.yml
dev/tests/fixtures/docfx/Vision/V1.TextAnnotation.DetectedBreak.yml

addresses https://github.com/googleapis/google-cloud-php/issues/8484 by linking to the corresponding enum types in the reference docs

docs: add enum types to protobuf enum getters and setters

---

.repo-metadata-full.json

fixes https://github.com/googleapis/google-cloud-php/issues/8569

chore: fix repo-metadata lint

---

Core/composer.json
Core/src/Batch/OpisClosureSerializer.php
Core/src/Batch/OpisClosureSerializerV4.php
Core/src/Batch/SerializableClientTrait.php
Core/tests/Unit/Batch/OpisClosureSerializerTest.php
ErrorReporting/tests/Unit/BootstrapTest.php
Logging/tests/Unit/LoggingClientTest.php
Logging/tests/Unit/PsrLoggerTest.php
composer.json
phpstan.neon.dist

fixes https://github.com/googleapis/google-cloud-php/issues/8423

feat: support ops/closure v4

---

dev/src/Command/NewComponentCommand.php

Fix error being thrown in the `new-component` command that a new component doesn't exist

fix(dev): new-component command
