googleapis/google-cloud-php

src/HttpRequestWrapper.php
tests/HttpRequestWrapperTest.php

Fix undefined variable error in HttpRequestWrapper

---

src/Storage/Connection/REST.php
tests/Storage/Connection/RESTTest.php

Minimum viable test for an array to string conversion error in `REST::sendRequest()`.
Before:
```bash
$ vendor/bin/phpunit
PHPUnit 4.8.23 by Sebastian Bergmann and contributors.
........................E.............
Time: 178 ms, Memory: 8.00Mb
There was 1 error:
1) Google\Gcloud\Tests\Storage\Connection\RESTTest::testGetObjectReturnsResponseArray
Array to string conversion
/Users/mike/Code/mcrumm/gcloud-php/src/Storage/Connection/REST.php:263
/Users/mike/Code/mcrumm/gcloud-php/src/Storage/Connection/REST.php:152
/Users/mike/Code/mcrumm/gcloud-php/tests/Storage/Connection/RESTTest.php:39
FAILURES!
Tests: 38, Assertions: 40, Errors: 1.
```
FWIW, I found this repo last night while looking for a [flysystem](flysystem.thephpleague.com) adapter for GCP.  Not finding one that I liked, I set …

Fix array to string conversion in REST::sendRequest()

---

composer.json
src/Logger/AppEngineFlexFormatter.php
src/Logger/AppEngineFlexHandler.php
tests/Logger/AppEngineFlexHandlerTest.php

Fixes #9 
This handler will format the logging message into a json format for a better presentation on the Cloud logging UI, in particular, with this format, you can filter the logs by severity, and also you should be able to bundle logs in a single request (unfortunately it doesn't work for me yet).
Downside is this PR adds monolog/monolog dependency. If you don't like big dependencies, please let me know. Potentially we can put these loggers in a different repo.

Added loggers for App Engine flexible environment.

---

src/RequestWrapper.php
tests/RequestWrapperTest.php

When using either `keyFile` or `keyFileStream` to provide credentials to the `ServiceBuilder`, if the user's credentials expire between requests, an error will occur when trying to load credentials from the file stream, because the pointer is at the end of the stream.
Here's the output from the test prior to calling `$keyFileStream->rewind()` within the `ServiceBuilder`:
```
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
.....................EE.......................................... 65 / 96 ( 67%)
...............................                                   96 / 96 (100%)
Time: 250 ms, Memory: 16.77Mb
There were 2 errors:
1) Google\Cloud\Tests\RequestWrapperTest::testCredentialsFromKeyFileStreamCanBeReadMultipleTimes with data set #0 (array(Closure Object (...), Closure …
```

Rewind the keyFileStream before each read

---

src/Storage/Connection/Rest.php
src/Upload/AbstractUploader.php

Content Type detection was not working correctly when uploading from the tmp uploads folder. To fix it, we're trying to detect the content type in the Storage REST connection. If the content type cannot be determined, the object will upload as `application/octet-stream`.

Detect contentType in the storage REST handler

---

src/RequestBuilder.php
tests/RequestBuilderTest.php
tests/fixtures/service-fixture.json

I wanted to get this in front of some eyes.
The basic problem is some schema resources are nested deeper than expected when the RequestBuilder was created.
The basic format we see in schema docs up to now was something like this (at the resources key):
````json
"resources": {
"bucketAccessControls": {
"methods": {
"delete": {
"id": "storage.bucketAccessControls.delete"
[...]
````
Compare that to the [pubsub discovery document](https://www.googleapis.com/discovery/v1/apis/pubsub/v1/rest):
````json
"resources": {
"projects": {
"resources": {
"topics": {
"methods": {
"setIamPolicy": {
"id": "pubsub.projects.topics.setIamPolicy",
[...]
````
To solve this problem, I added an optional 3rd parameter to the RequestBuilder constructor called `array $resourceRoot`. The resource root will be …

Support deeper nesting in the Json Schema

---

.gitignore
composer.json
src/Exception/ConflictException.php
src/Exception/GoogleException.php
src/Exception/NotFoundException.php
src/PubSub/Connection/ConnectionInterface.php
src/PubSub/Connection/Rest.php
src/PubSub/Connection/ServiceDefinition/pubsub-v1.json
src/PubSub/PubSubClient.php
src/PubSub/ResourceNameTrait.php
src/PubSub/Subscription.php
src/PubSub/Topic.php
src/RequestBuilder.php
src/RequestWrapper.php
src/ServiceBuilder.php
tests/PubSub/Connection/RestTest.php
tests/PubSub/PubSubClientTest.php
tests/PubSub/ResourceNameTraitTest.php
tests/PubSub/SubscriptionTest.php
tests/PubSub/TopicTest.php
tests/RequestBuilderTest.php
tests/RequestWrapperTest.php
tests/RestTraitTest.php
tests/ServiceBuilderTest.php
tests/UriTraitTest.php
tests/fixtures/service-fixture.json

* Preliminary pub/sub support
* Add different exception types and throw exception based on http status code. (When gRPC support starts coming, this will allow us to present a standard interface to end users).
* Extend my last change to the `RequestBuilder` to allow calling nested resource on a per-call basis.
* Full test coverage is still in progress
* IAM support (Some of the objects are there now, but are not implemented in the pubsub classes and will change a lot before they're ready.)
* Some docblocks need more complete documentation of `array $options` possible values.
Some discovery documents nest resources fairly deeply. For instance, a call to list subscriptions by topics would look like `$schema['resources']['projects']['resources']['topics']['resources']['subscriptions']['methods …

Add Pubsub client, Topic and Subscription APIs

---

src/PubSub/Topic.php

the [service definition for topic](https://github.com/GoogleCloudPlatform/gcloud-php/blob/master/src/PubSub/Connection/ServiceDefinition/pubsub-v1.json#L540) actually uses "name" as the parameter for the "create" method.

fixes pubsub topic::create

---

composer.json
src/BigQuery/BigQueryClient.php
src/ClientTrait.php
src/Exception/BadRequestException.php
src/Exception/ConflictException.php
src/Exception/GoogleException.php
src/Exception/NotFoundException.php
src/Exception/ServerException.php
src/Exception/ServiceException.php
src/PubSub/PubSubClient.php
src/RequestWrapper.php
src/Storage/StorageClient.php
tests/BigQuery/BigQueryClientTest.php
tests/ClientTraitTest.php
tests/Exception/ServiceExceptionTest.php
tests/PubSub/PubSubClientTest.php
tests/RequestWrapperTest.php
tests/fixtures/json-key-fixture.json

Upgrade gcloud-php to use Google/Auth@0.9. Includes auto-detection of project ID, when possible, so it fixes #32.
All service-related exceptions (i.e. `Google\Cloud\Exception\NotFoundException` and anything else that wraps a guzzle exception for REST, and in the future wraps a grpc/toolkit exception for gRPC) now extend `Google\Cloud\Exception\ServiceException` rather than `Google\Cloud\Exception\GoogleException`.
`ServiceException` includes the optional 3rd parameter `$serviceException` for passing the base service exception (from guzzle or toolkit code) up to the user. `GoogleException` can be used directly for non-service related library errors. I use it for when a projectId isn't provided and one cannot be detected, for instance.

Upgrade auth

---

README.md

Repository homepage is showing a build error even though master is good because the last build was a PR that errored.

Show coverage status for master branch

---

src/PubSub/Subscription.php
src/PubSub/Topic.php
tests/PubSub/SubscriptionTest.php
tests/PubSub/TopicTest.php

* Dave found a bug in Topic::subscriptions(). The iterator was expecting $subscription to be an array, but the API returns a string. This is fixed.
* I added a name() method to Topic and Subscription. There was not an easy way to get the name of either type without calling info(), which in many cases will trigger an API call. The new method will expose the name without needing a service call.

Fix subscription list method and add name() methods

---

src/RequestBuilder.php

In the case where a request body does not exist it is not valid to pass an empty array.

pass null instead of empty array to Request

---

src/ExponentialBackoff.php
src/RequestWrapper.php
tests/ExponentialBackoffTest.php
tests/RequestWrapperTest.php

Toying with the idea of using `ExponentialBackoff` for polling jobs. What do you guys think? 
Usage:
```php
$backoff = new ExponentialBackoff(10);
$backoff->execute(function () use ($job) {
printf('Waiting for job to complete' . PHP_EOL);
$job->reload();
if (!$job->isComplete()) {
throw new \Exception('Failed to complete job: Maximum retries exceeded');
}
});
```
In this example, the job is retried 10 times and then throws the exception.

Moves Request-specific logic out of ExponentialBackoff

---

scripts/DocGenerator.php
src/BigQuery/BigQueryClient.php
src/BigQuery/Dataset.php
src/BigQuery/Table.php
src/Logging/LoggingClient.php
src/PubSub/PubSubClient.php
src/PubSub/Subscription.php
src/PubSub/Topic.php
src/Storage/Bucket.php
src/Storage/StorageClient.php
src/Vision/VisionClient.php

Until now, methods returning Generators have been missing information about what type of value is yielded. This change updates the doc generator to render type information in Generators.
Example:
Your PHPdoc should look like this:
````
* @return \Generator<Google\Cloud\Veneer\ClassName>
````
The leading slash in `\Generator` is optional, but should be used for correctness.

Support Generator type docs in return

---

docs/manifest.json

I've updated the <kbd>manifest.json</kbd> file with a key that was recently added - `moduleName`. 
This key is used to generate all the links to stuff like GitHub/StackOverflow/etc. Since your repo name has changed recently, I thought I'd save you some trouble and update it for you!

docs: update repo name for links

---

src/Storage/Bucket.php

When listing objects of an empty bucket, previously a notice was raised, which breaks strict environments, since the empty response contains no 'items' index.
The generator was modified to break execution when 'items' isn't present.

BUGFIX: Do not yield storage object when response contains no items

---

src/Storage/Object.php

Since `metadata`, if set, is always an [object](https://cloud.google.com/storage/docs/json_api/v1/objects#resource) and therefore casts to an array in php, an `echo $info['metadata']` leads to a PHP notice:
```
PHP Notice:  Array to string conversion in [..]
```
The `size` key instead should not raise any notices and should always be filled.

update doc example for Google\Cloud\Storage\Object::info()

---

README.md
src/RequestBuilder.php
src/ServiceBuilder.php
src/Translate/Connection/ConnectionInterface.php
src/Translate/Connection/Rest.php
src/Translate/Connection/ServiceDefinition/translate-v2.json
src/Translate/TranslateClient.php
tests/ClientTraitTest.php
tests/ServiceBuilderTest.php
tests/Translate/Connection/RestTest.php
tests/Translate/TranslateClientTest.php

Ready for review/feedback!
[Official Translate API docs](https://cloud.google.com/translate/docs/)
- The constructor accepts a `target` language which is used by default in any requests that require a target language (defaults to english if not provided). It is possible to override this in each method if preferred as well.
- Public methods implemented
- `public function translate($string, array $options = [])` 
- `public function translateBatch(array $strings, array $options = [])`
- `public function detectLanguage($string, array $options = [])`
- `public function detectLanguageBatch(array $strings, array $options = [])`
- `public function languages(array $options = [])`
- `public function localizedLanguages(array $options = [])`

Introduce translate API

---

composer.json
tests/CallTraitTest.php
tests/ClientTraitTest.php
tests/ExponentialBackoffTest.php
tests/JsonFileTest.php
tests/RequestBuilderTest.php
tests/RequestWrapperTest.php
tests/RestTraitTest.php
tests/ServiceBuilderTest.php
tests/UriTraitTest.php
tests/fixtures/schema/composer.json.schema
tests/fixtures/schema/manifest.json.schema
tests/fixtures/schema/toc.json.schema

We've got a few json files that are curated by hand, including composer.json, docs/toc.json and docs/manifest.json. If any changes to those files were invalid, it could cause serious problems until resolved.
This change adds a test case to check those three json files for valid JSON, and it also validates the contents against their respective schema documents. If any violations are found, the test will fail, giving us an early alert of potential problems in the documents.
This change adds `league/json-guard` as a dev dependency. Keep in mind that this dependency will not be installed by consuming applications.
I also added a group annotation to each test case in the root `tests` folder.

Verify that human-curated json files are valid

---

src/BigQuery/BigQueryClient.php
src/BigQuery/QueryResults.php
src/Compute/Metadata.php
src/Datastore/DatastoreClient.php
src/Iam/PolicyBuilder.php
src/Logging/Logger.php
src/Logging/LoggingClient.php
src/Logging/Metric.php
src/Logging/PsrLogger.php
src/Logging/Sink.php
src/NaturalLanguage/NaturalLanguageClient.php
src/PubSub/PubSubClient.php
src/PubSub/Subscription.php
src/PubSub/Topic.php
src/Speech/SpeechClient.php
src/Storage/StorageClient.php
src/Translate/TranslateClient.php
src/Vision/Image.php
src/Vision/VisionClient.php

Mostly moving examples of obtaining an instance from the constructor to the class level. Some other standardizations, chiefly removing the config array (this will be required in the future for integration tests).

Standardize documentation and add some missing examples

---

scripts/DocGenerator.php
src/ClientTrait.php
src/Datastore/Operation.php
src/ValidateTrait.php
src/Vision/VisionClient.php
tests/ClientTraitTest.php
tests/ValidateTraitTest.php
tests/Vision/VisionClientTest.php

This PR started out as me changing the return value of VisionClient::annotateBatch(). It had been a generator, but that didn't make a ton of sense, because the number of annotations should always be equal to the number of input images. This'll be **a breaking change**.
Then I did a bit of other work and included it here. I can pull back on things if needed.
* DocGenerator threw an error that I hadn't seen before. May have been an update in the phpdoc lib. In any case, I added logic to keep it quiet.
* I abstracted the GCE projectId detection a bit so that I could unit test that code block. I also unit tested that code block.
* I moved `Google\Cloud\Datastore\Operation::validateBatch()` to a new trait called `Google\Cloud\ValidateTrait` so that we can use it elsewhere. I implemented it in …

Change return value of VisionClient::annotateBatch()

---

.travis.yml
composer.json
dev/deploy-docs.sh
dev/google-cloud
dev/readme.md
dev/src/DocGenerator/Command/Docs.php
dev/src/DocGenerator/DocGenerator.php
dev/src/DocGenerator/Parser/CodeParser.php
dev/src/DocGenerator/Parser/MarkdownParser.php
dev/src/DocGenerator/Parser/ParserInterface.php
dev/src/DocGenerator/TypeGenerator.php
dev/src/DocGenerator/Writer.php
dev/src/Release/Command/Release.php

The main goal of this PR is to clean up the way docs are generated now, and to allow us to parse markdown files in `src` into files which can be included in the docs site. For instance, `src/PubSub/README.md` would become accessible in the docs site as `docs/master/pubsub/readme`. This will allow us to provide additional documentation, such as core concepts, API overviews and more without being tied to relating it to a specific file.
* Replaced dependency on `phpDocumentor/phpDocumentor` with `phpDocumentor/reflection`.
* Replaced `composer docs` with `composer google-cloud [release|docs]`.
* Renamed `scripts/` to `dev/`.
* Renamed `scripts/release-generator` to `dev/google-cloud`.
* Moved `scripts/docs.php` into the console app.
* Refactored `scripts/DocGenerator` into multiple files …

Add Symfony console command for doc generation

---

composer.json
dev/readme.md
dev/src/Release/Command/Release.php

You can now create releases by specifying the release type:
* `composer google-cloud release major` (v0.8.1 -> v1.0.0)
* `composer google-cloud release minor` (v0.8.1 -> v0.9.0)
* `composer google-cloud release patch` (v0.8.1 -> v0.8.2)
* `composer google-cloud release v0.8.2` (v0.8.1 -> v0.8.2)
It also no longer matters if you specify `v` at the beginning of a version. Given versions will be validated and sanitized as needed, and a `\RuntimeException` will be thrown if the version is hopelessly mangled.

Add release incrementor support

---

src/Storage/Bucket.php
src/Storage/Connection/ConnectionInterface.php
src/Storage/Connection/Rest.php
src/Storage/EncryptionTrait.php
src/Storage/StorageObject.php
tests/Storage/BucketTest.php
tests/Storage/Connection/RestTest.php
tests/Storage/EncryptionTraitTest.php
tests/Storage/StorageObjectTest.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/144
New public methods implemented:
- `Bucket`
- `public function compose(array $sourceObjects, $name, array $options = []) : StorageObject`
- `StorageObject`
- `public function rewrite($destination, array $options = []) : StorageObject`
- `public function rename($name, array $options = []) : StorageObject`
Additionally, while it was possible to provide [customer-supplied encryption keys](https://cloud.google.com/storage/docs/encryption#customer-supplied) previously, there is now better support and it is more clearly documented.

New Storage functionality

---

src/Datastore/DatastoreClient.php
src/Datastore/Key.php
src/Datastore/Operation.php
tests/Datastore/KeyTest.php
tests/Datastore/OperationTest.php

If you're using `Key::STATE_COMPLETE`, you should update to `Key::STATE_NAMED`. The former constant still exists for now, but it may be removed in the future.
If you're checking the underlying constant value (i.e. `$key->state() === 'complete'`), this is a BC break. 😢

Renamed `complete key` to `named key` and add documentation

---

src/Datastore/Connection/Rest.php
src/Datastore/DatastoreClient.php
src/PubSub/PubSubClient.php

Add support for the Datastore emulator

---

src/Datastore/Operation.php
tests/Datastore/OperationTest.php

Fix readOptions on runQuery

---

src/Datastore/Query/Query.php
tests/Datastore/Query/QueryTest.php

Fixes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/190

fix query direction constants

---

docs/manifest.json
src/ServiceBuilder.php

* Incorrect projection path in Datastore Query Builder has been fixed. (#188)
* Mistake in Query order constants has been fixed.  (#191)
* Bug preventing source code links has been fixed. (#197)

Prepare v0.10.1

---

src/Datastore/Operation.php
tests/fixtures/datastore/query-results.json

Semantically, limiting query results should be a hard limit rather than a results-per-page limit. This change will cause `Operation::runQuery()` to respect limits and endCursors rather than continuing past the limits set by the user.
Once improvements to the Iterator are released, we should return the endCursor to the user along with the moreResultsType value (i.e. `MORE_RESULTS_AFTER_LIMIT`, `MORE_RESULTS_AFTER_CURSOR`) and allow them to fetch as they see fit.

Queries now STOP once the limit has been reached.

---

src/Storage/StorageObject.php
tests/Storage/StorageObjectTest.php

This let's retrieve the body of the `StorageObject` as a stream. Inspired by PSR-7 response method `getBody`. This method returns a PSR-7 `StreamInterface` which enables the user to decide whether they want to write stream to another stream or get the contents as a string.
I also propose to remove `downloadAsString` and `downloadToFile` in the next major release since the functionality of these methods is easily achieved using `getBody` and having the other methods can be confusing.

Added downloadAsStream method to StorageObject

---

src/Datastore/DatastoreClient.php
src/Datastore/EntityMapper.php
src/Datastore/Key.php
src/Datastore/Operation.php
src/Datastore/Query/Query.php
src/Datastore/Transaction.php
tests/Datastore/KeyTest.php
tests/Datastore/OperationTest.php
tests/Datastore/Query/QueryTest.php
tests/fixtures/datastore/entity-batch-lookup.json

Fixes #187, #186, #175.
Lookup sort only applies when $options['sort'] is set to `true`, and only sorts found entities.

Datastore query and lookup improvements

---

README.md
docs/toc.json
src/PubSub/IncomingMessageTrait.php
src/PubSub/Message.php
src/PubSub/PubSubClient.php
src/PubSub/Subscription.php
src/PubSub/Topic.php
src/RequestWrapper.php
tests/PubSub/IncomingMessageTraitTest.php
tests/PubSub/MessageTest.php
tests/PubSub/SubscriptionTest.php
tests/PubSub/TopicTest.php

This change improves PubSub by standardizing how message payload encoding is handled for Rest and gRPC transports, and by easing the handling and acknowledgement of incoming messages.
It introduces some breaking changes to the library.
* Added `Message` to represent incoming messages.
* Added `PubSubClient::consume()` method. This method can be used by pushDelivery servers to convert an HTTP request into an instance of `Message`.
* `Subscription::pull()` now returns `Generator<Message>`.
* `Subscription::acknowledge()` and `Subscription::modifyAckDeadline()` now accept an instance of `Message` as their first argument.
* `Subscription::acknowledgeBatch()` and `Subscription::modifyAckDeadlineBatch()` now accept `Message[]` as their first argument.
* Whether message payloads should be …

Refactor PubSub encoding and messages

---

docs/manifest.json
src/ServiceBuilder.php

This release includes a number of backwards-compatibility breaks. Please read
the release notes carefully if you are using Google Cloud Datastore or Google
Cloud Pub/Sub in your application. BC breaks are denoted by the prefix
:heavy_exclamation_mark: **BREAKING CHANGE**.
* Incoming PubSub messages are now represented as an instance of
`Google\Cloud\PubSub\Message` rather than as a simple array. (#168)
* `Google\Cloud\PubSub\PubSubClient::consume()` has been added to facilitate the
conversion of messages send via Push Delivery to an instance of
`Google\Cloud\PubSub\Message`. (#168)
* Datastore batch lookups now support sorting entities in the `found` result to
match the order in which keys were supplied. Set `$options['sort']` to `true`
to enable sorting. (#189)
* Datastore Queries now …

Prepare v0.11.0

---

docs/manifest.json
src/ServiceBuilder.php

**NOTE**: This patch fixes a regression introduced in the previous release. If
you are upgrading from a version older than v0.11.0, please take a moment to
review the v0.11.0 release notes, as there are some backward incompatabilities
you should be aware of.
* Fixed a regression in Datastore in which a namespace ID was not passed into
new Key instances causing errors on Queries and lookups which did not return
a record. (#204)

Prepare v0.11.1

---

src/Datastore/Operation.php
tests/Datastore/OperationTest.php
tests/fixtures/datastore/entity-lookup-bigsort.json

Added tests to make sure results come back properly when sort is enabled and disabled, and that the sort still works when results are missing.
@tmatsuo running this against your example suite before merge would be much appreciated!

Flatten lookupBatch sort to improve performance.

---

src/Datastore/Operation.php

Other spots where namespaces are used allow for overriding the value set in the client constructor, but runQuery does not.
This small change fixes that with no BC issues. The documented way to set a namespaceId is on the client. This is undocumented, but it does have legit use cases (see #213)

Allow per-query overrride of the datastore namespaceId

---

src/Datastore/DatastoreSessionHandler.php
tests/Datastore/DatastoreSessionHandlerTest.php

It's great if you give early feedback!

Adding a custom session handler with Cloud Datastore.

---

src/Datastore/EntityMapper.php
tests/Datastore/EntityMapperTest.php

When type of property in datastore is array and is empty, Datastore responds with `"field": {}`.
Test incoming.

fix Datastore entity deserialisation when arrayValue empty

---

README.md
src/BigQuery/BigQueryClient.php
src/Datastore/DatastoreClient.php
src/GrpcTrait.php
src/Logging/LoggingClient.php
src/NaturalLanguage/NaturalLanguageClient.php
src/PubSub/PubSubClient.php
src/RequestWrapper.php
src/RequestWrapperTrait.php
src/ServiceBuilder.php
src/Speech/SpeechClient.php
src/Storage/StorageClient.php
src/Vision/VisionClient.php
tests/GrpcTraitTest.php
tests/RequestWrapperTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/172
Example using [Stash](https://github.com/tedious/Stash):
``` php
<?php
require 'vendor/autoload.php';
use Google\Cloud\Storage\StorageClient;
use Stash\Driver\FileSystem;
use Stash\Pool;
$driver = new FileSystem([]);
$pool = new Pool($driver);
$storage = new StorageClient([
'authCache' => $pool
]);
```

Implement retries and expose caching for access tokens

---

src/Datastore/DatastoreClient.php
src/Datastore/Key.php
src/Datastore/Operation.php
src/Datastore/Transaction.php
tests/unit/Datastore/DatastoreClientTest.php
tests/unit/Datastore/DatastoreSessionHandlerTest.php
tests/unit/Datastore/KeyTest.php
tests/unit/Datastore/OperationTest.php
tests/unit/Datastore/TransactionTest.php

Until now, `Operation`, which is a class used to provide a common gateway for transactional and non-transactional Datastore operations, has been responsible for maintaining a list of enqueued mutations.
`Operation` is created on instantiation of `DatastoreClient` and persists throughout the use of Datastore. This makes it a poor choice for storing state. Additionally, if a mutation was enqueued inside a `Transaction` but not committed, and an operation was run from `DatastoreClient`, the transactional mutation would be committed outside the transaction.
This change moves enqueued mutations into `Transaction`, preventing mutations from being improperly committed.
Additionally, two new helper methods have been added to `Key`. `Key::pathEndIdentifier()` will return the name or ID of the last …

Update Operation to be stateless

---

src/Logging/Connection/Grpc.php

Addresses an issue with gRPC connections where logging a severity with a numeric value would throw an error.

Logging: only lookup severity numeric value when dealing with a string

---

src/NaturalLanguage/Annotation.php
src/NaturalLanguage/Connection/ConnectionInterface.php
src/NaturalLanguage/Connection/Rest.php
src/NaturalLanguage/Connection/ServiceDefinition/language-v1beta1.json
src/NaturalLanguage/NaturalLanguageClient.php
tests/unit/NaturalLanguage/Connection/RestTest.php
tests/unit/NaturalLanguage/NaturalLanguageClientTest.php

Implement NaturalLanguage changes

---

src/ServiceBuilder.php
src/Translate/Connection/Rest.php
src/Translate/Connection/ServiceDefinition/translate-v2.json
src/Translate/TranslateClient.php
tests/unit/Translate/TranslateClientTest.php

Please hold this until 11/15.
* Support service account and application default credentials in Translate
* Add support for the new `model` field.
Note that this change does not switch the operation from GET to POST.

Update Translate API Client

---

docs/manifest.json
src/ServiceBuilder.php

* Added new `analyzeSyntax` method to
`Google\Cloud\NaturalLanguage\NaturalLanguageClient`. (#241)
* Google Translate now supports Service Account Credentials and Application
Default Credentials. This means that you no longer need to manage a separate
API key to authenticate Google Translate. API keys are still supported. (#240)
* Fixed a bug in Google Cloud Logging when using the gRPC transport. (#243)

Prepare v0.13.0

---

src/Logging/Connection/Grpc.php
src/Logging/LoggingClient.php
src/Logging/V2/ConfigServiceV2Api.php
src/Logging/V2/LoggingServiceV2Api.php
src/Logging/V2/MetricsServiceV2Api.php
tests/unit/Logging/Connection/GrpcTest.php
tests/unit/Logging/LoggingClientTest.php

uses resourceNames instead of projectId for Logging API entities.list

---

composer.json
src/Logging/Connection/Grpc.php
src/Logging/V2/ConfigServiceV2Client.php
src/Logging/V2/LoggingServiceV2Client.php
src/Logging/V2/MetricsServiceV2Client.php

Please wait for proto-client-php v0.6 to be published before merging (now released)
Regenerates logging with updates protos
Fixes issues with sslCreds and credentialsProvider
Renames XApi classes to XClient
Adds leading backslashes to doc types

Regenerate logging, bump proto-client-php version

---

docs/manifest.json
src/ServiceBuilder.php

* Fixed the `google/auth` version conflict with `google/apiclient` for real
this time. (#262)

Prepare v0.13.2

---

composer.json

Bump the gax version to 0.5
The current gax version is incompatible with grpc 1.0.1 which was recently released on pecl, and which rejects the Authorization header provided by gax.

Bump gax version

---

README.md
src/Logging/Logger.php
src/Logging/LoggingClient.php
src/Logging/PsrLogger.php
tests/system/Logging/WriteAndListEntryTest.php
tests/unit/Logging/LoggerTest.php
tests/unit/Logging/LoggingClientTest.php
tests/unit/Logging/PsrLoggerTest.php

closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/180
@bshaffer Curious about your thoughts on the approach of having `write` accept multiple types as opposed to `logText` and `logStruct` methods. Please let me know what you think :)

Logging: default resource type to global (BC Break)

---

src/Logging/LoggingClient.php
src/PubSub/PubSubClient.php

Add a note in the LoggingClient and PubSubClient documentation that gRPC support is at Alpha quality level.
Note: I have added this for pubsub as well as logging, even though pubsub is not going beta. I can remove this if you think it is not relevant.
cc @omaray

Add documentation of alpha status of gRPC

---

src/Datastore/DatastoreClient.php
src/Datastore/Entity.php
src/Datastore/EntityMapper.php
src/Int64.php
src/ServiceBuilder.php
tests/system/Datastore/DatastoreTestCase.php
tests/system/Datastore/SaveAndModifyTest.php
tests/unit/Datastore/EntityMapperTest.php
tests/unit/Datastore/EntityTest.php
tests/unit/Datastore/OperationTest.php
tests/unit/Datastore/Query/GqlQueryTest.php
tests/unit/Datastore/Query/QueryTest.php
tests/unit/Int64Test.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/259
Sample:
```php
require 'vendor/autoload.php';
use Google\Cloud\Datastore\DatastoreClient;
$datastore = new DatastoreClient([
'returnInt64AsObject' => true
]);
$key = $datastore->key('Example', 100);
$entity = $datastore->entity($key);
$entity['int64Example'] = $datastore->int64('9223372036854775807');
$datastore->insert($entity);
$entity = $datastore->lookup($key);
echo $entity['int64Example']->get(); // '9223372036854775807'
```

introduce int64 object for 32 bit systems

---

src/Logging/LoggingClient.php
src/Logging/PsrLogger.php
tests/system/Logging/WriteAndListEntryTest.php
tests/unit/Logging/PsrLoggerCompatabilityTest.php
tests/unit/Logging/PsrLoggerTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/267
Messages logged through the `PsrLogger` now log as `jsonPayload` with a customizable key containing the message contents instead of as `textPayload`. Placeholders are supported and any additional info in the context array is to be logged as part of the `jsonPayload`. In order to support logging stackdriver specific data (such as labels) the `stackdriverOptions` key has been reserved.
Much thanks to @CaptainJojo for the original report.

(BC Break) psr logger updates

---

src/Storage/Bucket.php
src/Storage/EncryptionTrait.php
src/Storage/StorageObject.php
tests/system/Storage/ManageObjectsTest.php
tests/system/Storage/UploadObjectsTest.php
tests/unit/Storage/EncryptionTraitTest.php
tests/unit/Storage/StorageObjectTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/266
@bshaffer Does this line up well with what you were thinking?

accept base64 encoded key instead of bytes and make sha optional

---

docs/toc.json
src/BigQuery/BigQueryClient.php
src/BigQuery/Bytes.php
src/BigQuery/Connection/ServiceDefinition/bigquery-v2.json
src/BigQuery/Date.php
src/BigQuery/Job.php
src/BigQuery/QueryResults.php
src/BigQuery/Time.php
src/BigQuery/Timestamp.php
src/BigQuery/ValueInterface.php
src/BigQuery/ValueMapper.php
src/Datastore/DatastoreClient.php
src/Datastore/EntityMapper.php
src/ServiceBuilder.php
tests/system/BigQuery/LoadDataAndQueryTest.php
tests/unit/BigQuery/BigQueryClientTest.php
tests/unit/BigQuery/BytesTest.php
tests/unit/BigQuery/DateTest.php
tests/unit/BigQuery/JobTest.php
tests/unit/BigQuery/QueryResultsTest.php
tests/unit/BigQuery/TimeTest.php
tests/unit/BigQuery/TimestampTest.php
tests/unit/BigQuery/ValueMapperTest.php

Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/246
Sample:
```php
$bq = new BigQueryClient();
// Named parameters
$bq->runQuery('SELECT * FROM people WHERE name = @name and birthDate >= @date', [
'parameters' => [
'name' => 'David',
'date' => $bq->date(new \DateTime('1970-01-01'))
]
]);
// Positional parameters
$bq->runQuery('SELECT * FROM people WHERE name = ?', [
'parameters' => ['David']
]);
```
When running a query returned types are now mapped appropriately. The following table includes a mapping:
```
| **PHP Type**                               | **BigQuery Data Type**               |
|--------------------------------------------|--------------------------------------|
| `\DateTimeInterface`                       | `DATETIME`                           |
| …
```

Bigquery params and type mapping

---

docs/manifest.json
src/ServiceBuilder.php

Have you heard? We're going beta with our four major APIs! (BigQuery, Datastore,
Logging and Storage.) We've skipped a few numbers to highlight the fact that
this isn't just another minor release.
* Datastore and BigQuery can now optionally represent integer values as an
object called `Google\Cloud\Int64`. This change improves support for 32-bit
environments, including Windows on PHP versions older than 7.0.0. To enable
integers-as-object, pass `['returnInt64AsObject' => true]` in the DatastoreClient
and BigQueryClient constructor or factory method (`ServiceBuilder::datastore()`,
`ServiceBuilder::bigQuery()`). (#282)
* BigQuery now supports Query value parameterization! Both named and positional
parameters are supported. (#271)
* [BC Break] Stackdriver Logging now uses "global" as its …

Prepare v0.20.0

---

tests/system/BigQuery/LoadDataAndQueryTest.php
tests/system/BigQuery/ManageDatasetsTest.php
tests/system/BigQuery/ManageJobsTest.php
tests/system/BigQuery/ManageTablesTest.php
tests/system/Datastore/AllocateKeyTest.php
tests/system/Datastore/RunQueryTest.php
tests/system/Datastore/RunTransactionTest.php
tests/system/Datastore/SaveAndModifyTest.php
tests/system/Logging/ManageMetricsTest.php
tests/system/Logging/ManageSinksTest.php
tests/system/Logging/WriteAndListEntryTest.php
tests/system/NaturalLanguage/AnalyzeTest.php
tests/system/PubSub/ManageIAMPoliciesTest.php
tests/system/PubSub/ManageSubscriptionsTest.php
tests/system/PubSub/ManageTopicsTest.php
tests/system/PubSub/PublishAndPullTest.php
tests/system/Storage/ManageAclTest.php
tests/system/Storage/ManageBucketsTest.php
tests/system/Storage/ManageObjectsTest.php
tests/system/Storage/UploadObjectsTest.php

Add groups to system tests to ease running a subset, and
fix strict standards pass-by-reference errors.

Update system tests

---

src/BigQuery/BigQueryClient.php
src/Datastore/DatastoreClient.php
src/Logging/LoggingClient.php
src/NaturalLanguage/NaturalLanguageClient.php
src/PubSub/PubSubClient.php
src/RequestWrapperTrait.php
src/ServiceBuilder.php
src/Speech/SpeechClient.php
src/Storage/StorageClient.php
src/Translate/TranslateClient.php
src/Vision/VisionClient.php

use correct type in documentation for keyFile

---

docs/manifest.json
src/ServiceBuilder.php

* Google Cloud API REST Service Definitions can now be overridden by implementors. This is an advanced feature which should be used carefully, but in certain cases can allow for early access of new features not yet supported by Google Cloud PHP. (#289)
* A documentation mistake which incorrectly marked a keyFile configuration parameter as a string has been fixed. (#297)

Prepare v0.20.1

---

.travis.yml
appveyor.yml
appveyor_install_php.ps1
tests/unit/Datastore/EntityMapperTest.php

This introduces PHP 7.1 testing with travis since it's the new stable release since December 1st.

Test PHP 7.1 compatibility and fix regressions

---

composer.json
src/Storage/Bucket.php
src/Storage/Connection/Rest.php

fixing #312. Making Rest helper set predefinedAcl to null by default for GCS objects.

fixing #312. Making Rest helper set predefinedAcl to null by default.

---

README.md

nit: it's standard to not include `<?php` in code snippets.

Removes php tags in README code snippets

---

docs/manifest.json
src/ServiceBuilder.php

* Added support for Stackdriver Monitoring via a generated gRPC client. See
`Google\Cloud\Monitoring\V3` for more information. (#308)
* Google Translate has been renamed Google Cloud Transation. At this time there
are no code changes required. Changes are limited to documentation. (#291)
* PubSub and Logging generated gRPC clients have been updated. (#305)
* PHP 7.1 compatibility is now tested as part of our normal continuous
integration process. Thanks to @cedricziel for the PR! (#303)
* Fixed Storage error in which `predefinedAcl` was assigned a value which was
not always a sensible default. Thanks to @amoiseiev for the PR! (#313)
* Fixed bug in which falsey values were incorrectly filtered out by
`array_filter()`. (#318)
* Fixed invalid translation response when strings is not …

Prepare v0.20.2

---

docs/manifest.json
src/ServiceBuilder.php

* Fixed a bug in which PHP was emitting `E_NOTICE` messages when storage object
info was incomplete or missing. (#347)

Prepare v0.21.1

---

src/Compute/Metadata.php
src/Compute/Metadata/Readers/ReaderInterface.php
src/Compute/Metadata/Readers/StreamReader.php
tests/snippets/Compute/MetadataTest.php

Working on covering the remainder of snippets. This is a separate PR because there are a couple substantive changes to that API I want to highlight.
I've added a `ReaderInterface` and changed `StreamReader` to implement it. I've updated `Metadata::setReader()` to require an instance of `ReaderInterface`, rather than `mixed`.
This is technically a breaking change, but if people are using the existing StreamReader class, everything should work with no changes.

Add snippet tests and ReaderInterface for Compute

---

src/PubSub/ResourceNameTrait.php
tests/unit/PubSub/ResourceNameTraitTest.php

This changes the visibility of the ResourceNameTrait methods to private, in line with other APIs which do not expose the means of formatting names. This is a breaking change.

Change ResourceNameTrait methods visibility

---

dev/src/Snippet/SnippetTestCase.php
src/Iam/PolicyBuilder.php
src/NaturalLanguage/Annotation.php
src/PubSub/Subscription.php
tests/snippets/BigQuery/JobTest.php
tests/snippets/BigQuery/QueryResultsTest.php
tests/snippets/Datastore/DatastoreClientTest.php
tests/snippets/Iam/IamTest.php
tests/snippets/Iam/PolicyBuilderTest.php
tests/snippets/Int64Test.php
tests/snippets/Logging/PsrLoggerTest.php
tests/snippets/NaturalLanguage/AnnotationTest.php
tests/snippets/NaturalLanguage/NaturalLanguageClientTest.php
tests/snippets/PubSub/PubSubClientTest.php
tests/snippets/PubSub/SubscriptionTest.php
tests/snippets/PubSub/TopicTest.php
tests/snippets/ServiceBuilderTest.php
tests/snippets/Speech/OperationTest.php
tests/snippets/Storage/BucketTest.php
tests/snippets/Storage/StorageClientTest.php
tests/snippets/Storage/StorageObjectTest.php
tests/snippets/Translate/TranslateClientTest.php
tests/snippets/Vision/Annotation/EntityTest.php
tests/snippets/Vision/Annotation/Face/LandmarksTest.php
tests/snippets/Vision/Annotation/FaceTest.php
tests/snippets/Vision/Annotation/SafeSearchTest.php
tests/snippets/bootstrap.php

This adds coverage for everything which wasn't covered, save for the Compute and ResourceNameTrait snippets, which are addressed elsewhere.

Snippet finish line

---

composer.json
src/ErrorReporting/V1beta1/ErrorGroupServiceClient.php
src/ErrorReporting/V1beta1/ErrorStatsServiceClient.php
src/ErrorReporting/V1beta1/ReportErrorsServiceClient.php
src/ErrorReporting/V1beta1/resources/error_group_service_client_config.json
src/ErrorReporting/V1beta1/resources/error_stats_service_client_config.json
src/ErrorReporting/V1beta1/resources/report_errors_service_client_config.json
src/Logging/V2/ConfigServiceV2Client.php
src/Logging/V2/LoggingServiceV2Client.php
src/Logging/V2/MetricsServiceV2Client.php
src/Logging/V2/resources/config_service_v2_client_config.json
src/Logging/V2/resources/logging_service_v2_client_config.json
src/Logging/V2/resources/metrics_service_v2_client_config.json
src/Monitoring/V3/GroupServiceClient.php
src/Monitoring/V3/MetricServiceClient.php
src/Monitoring/V3/resources/group_service_client_config.json
src/Monitoring/V3/resources/metric_service_client_config.json
src/PubSub/V1/PublisherClient.php
src/PubSub/V1/SubscriberClient.php
src/PubSub/V1/resources/publisher_client_config.json
src/PubSub/V1/resources/subscriber_client_config.json
src/Speech/V1beta1/SpeechClient.php
src/Speech/V1beta1/resources/speech_client_config.json

This includes the updated headers. It also includes changes to:
- Pubsub (adding new methods)
- Speech (adding streaming support)
- Client config json files (removing retry_codes_def)

Regenerate gapic code

---

src/RequestWrapper.php
tests/unit/RequestWrapperTest.php

- Conditionally set the Authorization header, but always send user agents
- Adds test case to cover this condition

Ensure user agents are sent when using an API key

---

src/PubSub/Subscription.php
tests/snippets/PubSub/MessageTest.php
tests/snippets/PubSub/SubscriptionTest.php
tests/system/PubSub/PublishAndPullTest.php
tests/unit/PubSub/SubscriptionTest.php

It doesn't appear `pull` supports paging:
https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/pull

[BC Break] Remove paging from Subscription::pull

---

.travis.yml
dev/src/Snippet/Parser/Parser.php
tests/snippets/bootstrap.php

Also, if snippets are uncovered, the suite will fail.

Ignore private methods on snippet test coverage

---

dev/src/DocGenerator/Parser/CodeParser.php
docs/external-classes.json
docs/toc.json
src/ErrorReporting/README.md
src/ErrorReporting/V1beta1/README.md
src/Logging/V2/README.md
src/Monitoring/README.md
src/Monitoring/V3/README.md
src/PubSub/V1/README.md
src/Speech/V1beta1/README.md

This change adds the generated GAPIC clients to the Google Cloud PHP docs site. It takes advantage of GoogleCloudPlatform/gcloud-common#213, so we'll need to rebuild the docs site before this is merged.
* Add all generated clients to the table of contents.
* Add simple landing pages (README.md) in empty folders.
* Modify doc generator to recognize external types specified in `docs/external-classes.json` and transform references into external links.
For an example, see https://jdpedrie.github.io/gcloud-php/#/docs/master/servicebuilder.
This closes #99.

Add GAPIC docs to docs site

---

README.md

Mirroring the changes in https://github.com/GoogleCloudPlatform/google-cloud-php/pull/274

Update README for Vision going beta

---

docs/manifest.json
src/ServiceBuilder.php

Wait for #382 before merging.
----
* :heavy_exclamation_mark: **BREAKING CHANGE** The return type of
`Google\Cloud\PubSub\Subscription::pull()` has changed from
`Generator<Google\Cloud\PubSub\Message>` to `Google\Cloud\PubSub\Message[]`.
(#375)
* Cloud Vision in Google Cloud PHP is now considered beta! That means that while
we're not quite ready to call it done, we're getting a lot closer. You should
expect more stability and fewer breaking changes between now and our 1.0
release. (#387)
* Fixed a bug where application identifying headers were not sent when using an
API key rather than a service account over the REST transport. (#378)

Prepare v0.23.0

---

src/Storage/StorageObject.php
tests/unit/Storage/StorageObjectTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/392

Don't set ACL when predefinedAcl is defined

---

src/BigQuery/Connection/Rest.php
src/Core/GrpcRequestWrapper.php
src/Core/GrpcTrait.php
src/Core/RequestWrapper.php
src/Core/RequestWrapperTrait.php
src/Core/RestTrait.php
src/Core/Upload/AbstractUploader.php
src/Storage/Connection/Rest.php
src/Storage/EncryptionTrait.php
src/Storage/StorageObject.php
src/Storage/StreamWrapper.php
tests/unit/Core/GrpcRequestWrapperTest.php
tests/unit/Core/GrpcTraitTest.php
tests/unit/Core/RequestWrapperTest.php
tests/unit/Core/RestTraitTest.php
tests/unit/Storage/Connection/RestTest.php
tests/unit/Storage/EncryptionTraitTest.php
tests/unit/Storage/StorageObjectTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/376

[BC Break] Add requestTimeout option to be shared between REST/gRPC

---

src/BigQuery/Dataset.php

Method returns a Table not a Dataset. This throws off IDEs and leads users to dive into the documentation to work out why they can't do:
```php
$table = $dataset->table($tableName);
$job = $table->load(...)
```

Fix incorrect return type in doc-comment

---

src/BigQuery/BigQueryClient.php
src/BigQuery/Dataset.php
src/BigQuery/Job.php
src/BigQuery/QueryResults.php
src/BigQuery/Table.php
src/Logging/Metric.php
src/Logging/Sink.php
src/ServiceBuilder.php
src/Storage/Bucket.php
src/Storage/StorageClient.php
src/Storage/StorageObject.php
tests/snippets/BigQuery/JobTest.php
tests/unit/BigQuery/JobTest.php

A BC break is introduced (though, it should not affect many users) in the `Job` class, as `ValueMapper` is now required and the parameter order has been shifted.

[BC Break] Results from doc audit

---

tests/system/Storage/ManageObjectsTest.php
tests/system/Storage/StorageTestCase.php

This tests that the client library does not normalize the string encoding, which would affect access to buckets with similar but differently-encoded names.
The test has a hard-coded bucket name - should this be a constant in `StorageTestCase`?

Add system test of string normalization in GCS

---

src/Core/RequestWrapper.php
src/Core/RequestWrapperTrait.php
src/Core/RetryDeciderTrait.php
src/NaturalLanguage/NaturalLanguageClient.php
tests/unit/Core/RetryDeciderTraitTest.php

This also includes a change to prevent the natural language client from attempting to retry on rate limit related errors.
Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/403

Allow the retry function to be overridden in the RequestWrapper

---

docs/contents/cloud-spanner.json
src/Core/Exception/AbortedException.php
src/Core/PhpArray.php
src/Spanner/Admin/Database/V1/DatabaseAdminClient.php
src/Spanner/Admin/Instance/V1/InstanceAdminClient.php
src/Spanner/Connection/ConnectionInterface.php
src/Spanner/Connection/Grpc.php
src/Spanner/Database.php
src/Spanner/Instance.php
src/Spanner/Operation.php
src/Spanner/Session/Session.php
src/Spanner/Session/SessionClient.php
src/Spanner/Session/SessionPool.php
src/Spanner/Session/SessionPoolInterface.php
src/Spanner/Session/SimpleSessionPool.php
src/Spanner/SpannerClient.php
src/Spanner/Transaction.php
src/Spanner/TransactionConfigurationTrait.php
src/Spanner/ValueMapper.php
tests/unit/Spanner/SpannerClientTest.php

The big change here is an addition to `Google\Cloud\Core\PhpArray::filterValue()` to short-circuit any decoding logic if the value given matches a null field type reference. This change passes the various test suites, but potential side effects should be investigated further.
Additionally, since SpannerClient relies indirectly on grpc constants which do not exist if gRPC is not installed, the entire SpannerClient file is skipped in the absence of the grpc extension.

Spanner fixes

---

src/Core/RestTrait.php
src/NaturalLanguage/Annotation.php
src/NaturalLanguage/Connection/ConnectionInterface.php
src/NaturalLanguage/Connection/Rest.php
src/NaturalLanguage/Connection/ServiceDefinition/language-v1beta2.json
src/NaturalLanguage/NaturalLanguageClient.php
tests/snippets/NaturalLanguage/NaturalLanguageClientTest.php
tests/unit/Core/RestTraitTest.php
tests/unit/NaturalLanguage/Connection/RestTest.php
tests/unit/NaturalLanguage/NaturalLanguageClientTest.php

I modified `Google\Cloud\Core\RestTrait` to accept an optional option called `$requestBuilder`, which if supplied and an instance of `Google\Cloud\Core\RequestBuilder`, will be used to construct the request in place of the default RequestBuilder instance.
* `google-cloud-php-natural-language`: minor version bump
* `google-cloud-php-core`: minor version bump

[core, language] Add support for Language method AnalyzeEntitySentiment

---

src/Core/Upload/StreamableUploader.php
tests/unit/Core/Upload/StreamableUploaderTest.php

Fixes #447 
When the user's PHP installation includes the curl extension (most do), the curl handler would fix the content length. This only surfaced for PHP instances without curl, but should still be fixed.

Ensure the correct Content-Length header when streaming uploads

---

docs/contents/cloud-speech.json
src/ServiceBuilder.php
src/Speech/Operation.php
src/Speech/Result.php
src/Speech/SpeechClient.php
tests/snippets/Speech/OperationTest.php
tests/snippets/Speech/ResultTest.php
tests/snippets/Speech/SpeechClientTest.php
tests/unit/Speech/OperationTest.php
tests/unit/Speech/ResultTest.php
tests/unit/Speech/SpeechClientTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/444 & https://github.com/GoogleCloudPlatform/google-cloud-php/issues/446 & https://github.com/GoogleCloudPlatform/google-cloud-php/issues/445
/cc @adziuk @pbogle
FYI: This introduces a breaking change.

Return all results and do not detect encoding/sample rate in the client

---

src/PubSub/Topic.php

Fix incorrect Pub/Sub example resulting in BadRequestException:
```
Fatal error: Uncaught Google\Cloud\Core\Exception\BadRequestException: {
"error": {
"code": 400,
"message": "Invalid value at 'messages[0].attributes[0].value' (TYPE_STRING), 1",
"status": "INVALID_ARGUMENT",
"details": [
{
"@type": "type.googleapis.com/google.rpc.BadRequest",
"fieldViolations": [
{
"field": "messages[0].attributes[0].value",
"description": "Invalid value at 'messages[0].attributes[0].value' (TYPE_STRING), 1"
}
]
}
]
}
}
```
As documented [1] attributes must look like this `map (key: string, value: string)`
[1] https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage

[Docs] Fix incorrect Pub/Sub example resulting in BadRequestException

---

composer.json
docs/contents/cloud-vision.json
src/Vision/V1/ImageAnnotatorClient.php
src/Vision/V1/README.md
src/Vision/V1/resources/image_annotator_client_config.json

Support for doc generation coming

Add vision GAPIC

---

src/Core/ClientTrait.php
src/Logging/LoggingClient.php
src/PubSub/PubSubClient.php
tests/unit/Core/ClientTraitTest.php
tests/unit/PubSub/PubSubClientTest.php

Choose rest over grpc for now.

---

src/Core/Iam/PolicyBuilder.php
tests/snippets/Core/Iam/PolicyBuilderTest.php
tests/unit/Core/Iam/PolicyBuilderTest.php

RFC: Adds removePolicy to Iam Policy Builder

---

docs/contents/cloud-core.json
docs/contents/cloud-pubsub.json

https://github.com/GoogleCloudPlatform/google-cloud-php/pull/462 included a change moving some classes from PubSub to Core. This follows up on that make sure our documentation is correct.

Update docs to include new core classes

---

docs/manifest.json
src/ServiceBuilder.php

Missed this in https://github.com/GoogleCloudPlatform/google-cloud-php/pull/493

Increase ServiceBuilder version for v0.29.0 release

---

src/Spanner/Connection/Grpc.php
tests/unit/Spanner/Connection/GrpcTest.php

I received the following error when using a composite key:
```sh
[Google\Cloud\Core\Exception\FailedPreconditionException (9)]  
Wrong number of key parts for TableName. Expected: 2. Got: [["2","2"]] 
```
Code:
```php
$keySet = $spanner->keySet(['keys' => [[2,2]]]);
$result = $t->read(
'TableName',
$keySet,
['ColumnName'],
['limit' => 1]
);
```
Looks like the connection class is wrapping keys in an array, I assume because single keys are actually a composite key of *one*. I believe changing the wrapping array into a cast is the proper way to fix this issue.

Cast keySet keys to arrays instead of wrapping them

---

src/Spanner/Admin/Database/V1/DatabaseAdminClient.php
src/Spanner/Admin/Database/V1/resources/database_admin_client_config.json
src/Spanner/Admin/Instance/V1/InstanceAdminClient.php
src/Spanner/Admin/Instance/V1/resources/instance_admin_client_config.json
src/Spanner/V1/SpannerClient.php
src/Spanner/V1/resources/spanner_client_config.json
src/Speech/V1beta1/SpeechClient.php
src/Speech/V1beta1/resources/speech_client_config.json
src/VideoIntelligence/V1beta1/VideoIntelligenceServiceClient.php

This updates the GAPICs for Spanner, which are slightly older, and picks up updated comments.
This also updates links in the Video intelligence GAPIC.

Update GAPICs for Spanner

---

src/Core/GrpcRequestWrapper.php
src/Core/GrpcTrait.php
src/Core/RestTrait.php
src/Core/WhitelistTrait.php
src/PubSub/Connection/Grpc.php
src/PubSub/Connection/Rest.php
tests/system/ServiceWhitelist/WhitelistTest.php
tests/system/bootstrap.php
tests/unit/Core/Exception/NotFoundExceptionTest.php
tests/unit/Core/WhitelistTraitTest.php

When a `NotFoundException` is thrown by a method which may be under whitelist restriction, the exception is intercepted and the error message is modified to indicate the possible problem to the user.
Still to come is integrating into system tests to help keep this up to date and alert us when a whitelist is removed.

Modify exceptions when a whitelist may be present

---

.travis.yml
dev/sh/test-composer
dev/sh/tests
src/ErrorReporting/composer.json
src/Monitoring/composer.json
tests/component/TestComposerInstall.php

This adds a test which will attempt to run `composer install` against all google-cloud-php components, making sure they can be installed side by side at their latest version.
~~The trouble with this is that it can't catch errors until the releases have been tagged. Therefore it may be useful to inform us after the fact, but it may not give us forewarning. Feedback and ideas on that are welcomed.~~
I'm now using path repositories, which lets me get the package at the local version. PTAL @dwsupplee

Test component composer integration, bump gax requirement

---

src/Spanner/Bytes.php
src/Spanner/Database.php
src/Spanner/Date.php
src/Spanner/Timestamp.php
src/Spanner/Transaction.php
src/Spanner/TransactionalReadTrait.php
tests/snippets/Spanner/BytesTest.php
tests/snippets/Spanner/DatabaseTest.php
tests/snippets/Spanner/DateTest.php
tests/snippets/Spanner/SnapshotTest.php
tests/snippets/Spanner/TimestampTest.php
tests/snippets/Spanner/TransactionTest.php
tests/system/Spanner/QueryTest.php
tests/unit/Spanner/DatabaseTest.php
tests/unit/Spanner/OperationTest.php
tests/unit/Spanner/TransactionTest.php
tests/unit/Spanner/ValueMapperTest.php

`ValueMapper` is not visible to an end-user in any context besides the type constants, so it makes sense to move the types to a class which the user will already be interacting with.

[BC Break] Move type constants to Database

---

composer.json
src/Core/composer.json
src/ErrorReporting/composer.json
src/Monitoring/composer.json
src/Spanner/composer.json
src/VideoIntelligence/composer.json

A new version of `google/auth` was tagged. There haven't been any important changes since `v0.11`, just the fact that we are finally calling it stable, which is nice.

upgrade to google/auth ^1.0

---

src/Spanner/SpannerClient.php

According to https://github.com/google/google-auth-library-php/blob/master/src/CredentialsLoader.php#L115 this should actually be the json-decoded array of the service credentials passed through, not the raw string. This is also mentioned here: https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Core/RequestWrapperTrait.php#L80

Fixing a documentation comment in SpannerClient class construct

---

src/Spanner/Database.php
tests/unit/Spanner/DatabaseTest.php

Closes #528.
Please note that while this change prevents calling `Database::runTransaction()` inside `Database::runTransaction()`, it only works *on a single `Database` instance*. There is no protection against a user creating a new instance of the client and injecting it into the runTransaction callback. If we must protect against this, it will require additional discussion and work, and would be much more challenging.
/cc @vkedia.
edit: Examples of what I explained above:
```php
use Google\Cloud\Spanner\SpannerClient;
$spanner = new SpannerClient();
$db = $spanner->connect('instance', 'database');
$db->runTransaction(function ($t) use ($db) {
// Exception thrown here.
$db->runTransaction(function (){});
});
```
```php
use Google\Cloud\Spanner\SpannerClient;
$spanner = new …
```

Prevent nested transactions

---

tests/snippets/Trace/RequestTracerTest.php

This fixes the openssl_sign errors which occurred during the shutdown phase of running the snippet test suite.
/cc @chingor13

Fix Trace snippet test

---

composer.json
src/ErrorReporting/composer.json
src/Monitoring/composer.json
src/PubSub/V1/SubscriberClient.php
src/Spanner/composer.json
src/VideoIntelligence/composer.json

- Bump gax version for 0.20.1 release, which contains bug fixes and updates the ApiException message format to match REST
- Bugfix renaming resourcesField->resourcesGetMethod

Bump gax version, fix for resource streaming

---

src/Speech/Result.php
src/Speech/SpeechClient.php
tests/unit/Speech/SpeechClientTest.php

cc @shinfan 
This PR adds support for the new wordTimeOffset feature in Speech.
Currently there are no system tests for the Speech API, but I have manually verified the change against our test project, which is whitelisted for this feature.

Add Speech wordTimeOffset support

---

src/Trace/README.md
src/Trace/TraceClient.php

Re-adding the example to the Trace README.md about using the `AsyncReporter`

Async trace reporter readme

---

docs/contents/google-cloud.json

This was missed when merging in DLP earlier and is required for content to show up in the nav bar on the doc site. I manually pushed the updates to the doc site, but we will want this for the future when generating new releases.

add dlp to includes

---

src/Core/Batch/BatchTrait.php
src/Logging/LoggingClient.php
src/Logging/PsrLogger.php
src/PubSub/Topic.php
src/Trace/Reporter/AsyncReporter.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/584
cc @tmatsuo 
How does this solution sound for right now?
As a future item, we could replace these fwrite calls with a generalized logging mechanism that could also be utilized elsewhere throughout the library for emitting debug information.
Let me know what you think! :)

Only emit debug information when debugOutput is enabled

---

dev/src/DocGenerator/DocGenerator.php
dev/src/DocGenerator/Parser/CodeParser.php
dev/src/DocGenerator/ReflectorRegister.php
docs/external-classes.json

Explore what this looks like here: https://michaelbausor.github.io/gcloud-php/#/docs/google-cloud/master/core/upload/streamableuploader
Points to note:
- Classes now list superclasses and interfaces
- Classes include methods from superclasses and traits *inside Google\Cloud*
- Methods defined on **external** superclasses and traits are **NOT** included. This is because we cannot be sure they will have a docblock. We may want to consider including them anyway?
- Added a link the implementing class/trait on relevant methods
- Included links to build-in types and PSR classes/interfaces
Existing problem that isn't fixed: we don't link correctly when the docs specify a relative class name. See e.g. the param documentation in the existing docs (Duration and Timestamp): …

Update documentation generation

---

composer.json
src/Core/Batch/BatchDaemon.php
src/Core/Batch/BatchDaemonTrait.php
src/Core/Batch/BatchRunner.php
src/Core/Batch/SysvProcessor.php
src/Core/Lock/FlockLock.php
src/Core/Lock/LockTrait.php
src/Core/Lock/SemaphoreLock.php
src/Core/Lock/SymfonyLockAdapter.php
src/Core/SysvTrait.php
src/Spanner/Session/CacheSessionPool.php
src/Spanner/composer.json
tests/unit/Core/Batch/BatchDaemonTraitTest.php
tests/unit/Core/Batch/SysvConfigStorageTest.php
tests/unit/Core/Batch/SysvProcessorTest.php
tests/unit/Core/Lock/CommonLockTrait.php
tests/unit/Core/Lock/FlockLockTest.php
tests/unit/Core/Lock/MockGlobals.php
tests/unit/Core/Lock/SemaphoreLockTest.php
tests/unit/Core/SysvTraitTest.php
tests/unit/Spanner/Session/CacheSessionPoolTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/564
Included in this PR:
- Flock based lock
- Semaphore based lock
- Updates to Spanner to remove references to symfony/lock
- There were some useful methods in `Google\Cloud\Core\Batch\SysvTrait` that could be used outside of the context of batching, so it has been split out into two traits

Introduce flock/semaphore locking mechanisms

---

src/Core/Batch/BatchRunner.php
src/Core/Batch/ConfigStorageInterface.php
src/Core/Batch/InMemoryConfigStorage.php
src/Core/Batch/SysvConfigStorage.php
tests/unit/Core/Batch/SysvConfigStorageTest.php

If you attempt to store a closure into shared memory, it will error out
and leave corrupt data in shared memory. When the daemon tries to read
the corrupt data, it crashes, but currently does not clear the config.
Thus, the batch daemon will continue to crash until the shared memory is
manually cleared.
When we write data and serialization fails, we will clear the corrupt data from
shared memory. When we read data and deserialization fails, we will also clear the 
corrupt data from shared memory.
On the daemon side, the daemon will continue to poll for new config without crashing.

Batch daemon clear config

---

src/Core/Iterator/ItemIteratorTrait.php
src/Core/Iterator/PageIteratorTrait.php
tests/system/Logging/WriteAndListEntryTest.php
tests/system/PubSub/ManageSubscriptionsTest.php
tests/system/PubSub/ManageTopicsTest.php
tests/unit/Core/Iterator/ItemIteratorTest.php
tests/unit/Core/Iterator/PageIteratorTest.php

This PR addresses a few concerns in the system tests:
- Some of the logging write tests have intermittently been failing due to some concerns related to eventually consistency. To resolve this, iterators have been updated to make sure we continue paging as long a `nextResultToken` is set.
- A few pubsub tests were failing intermittently due to results not coming back in the same order they were created. To resolve this, the expected and actual results are now sorted using the same algorithm.

Iterator / PubSub Updates

---

dev/src/DocGenerator/Parser/CodeParser.php

Notes:
- Inheritdocs are only supported in class docblocks, not method docblocks.
- Two formats are supported: `{@inheritdoc}` and `{@inheritDoc}`. This is because those two are supported by [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), and php-cs-fixer will convert from `inheritDoc` to `inheritdoc`

Support inheritdoc tag in class docs

---

src/Core/RequestWrapper.php

In the default Google App Engine environment, the phpversion function is disabled and requires fiddling around to get it to work (currently overriding ini config, suhosin config and whitelist env do not work as intended). This change moves to using PHP_VERSION which is a constant available in PHP since 5.2.7 and provides the same information as the implementation of phpversion here.

Change RequestWrapper to use constant

---

src/BigQuery/BigQueryClient.php
src/Datastore/DatastoreClient.php
src/Language/LanguageClient.php
src/Logging/LoggingClient.php
src/PubSub/PubSubClient.php
src/Spanner/SpannerClient.php
src/Speech/SpeechClient.php
src/Storage/StorageClient.php
src/Trace/TraceClient.php
src/Translate/TranslateClient.php
src/Vision/VisionClient.php

adds RequestWrapperTrait options to applicable Client classes

---

.travis.yml

Until https://github.com/grpc/grpc/issues/12123 is resolved we will need to rely on an older version of gRPC for builds to pass.

CI: Temporarily require grpc-1.4.1

---

dev/src/DocGenerator/Parser/CodeParser.php
tests/unit/ServiceBuilderTest.php

@michaelbausor, building off your last doc generator change, this resolves some php warnings which it was causing. I searched through the generated docs site a fair bit and couldn't find it causing problems with the error or with my fix, but if you could take a look to verify that I'm not going against your intent, I'd appreciate it!
Error example is below:
```
Warning: trim() expects parameter 1 to be string, array given in /google-cloud-php/dev/src/DocGenerator/Parser/CodeParser.php on line 187
Call Stack:
0.0002     368592   1. {main}() /google-cloud-php/dev/google-cloud:0
0.0148    2309824   2. Symfony\Component\Console\Application->run() /google-cloud-php/dev/google-cloud:38
0.0228    2631144   3. Symfony\Component\Console\Application->doRun() …
```

Fix errors in doc generator, add servicebuilder test

---

src/BigQuery/Dataset.php
src/BigQuery/Table.php
tests/snippets/BigQuery/DatasetTest.php
tests/snippets/BigQuery/TableTest.php

Fixes #525 
This changes instances in docs of fetching the friendlyName to selfLink. It leaves calls that set the friendlyName (e.g. https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/BigQuery/Dataset.php#L127)

Updates documentation to use selfLink instead of friendlyName

---

dev/src/DocGenerator/Parser/CodeParser.php

Fixes #593 
See e.g. `authCache` and `credentialsFetcher` optional params here: https://michaelbausor.github.io/gcloud-php/#/docs/google-cloud/master/bigquery/bigqueryclient?method=__construct
Vs. the existing docs here: https://googlecloudplatform.github.io/google-cloud-php/#/docs/google-cloud/master/bigquery/bigqueryclient?method=__construct

Parse types for nested params

---

.travis.yml
src/Datastore/DatastoreSessionHandler.php
tests/unit/Datastore/DatastoreSessionHandlerTest.php

Fixes #506 
cc @tmatsuo @dwsupplee @jdpedrie 
Some notes:
- This is added as an option, not as the default behaviour, because that would be (I believe) a BC-break.
- It is slightly clumsy in the DatastoreSessionHandler because it is the second optional arg, so someone who wants to pass it will also need to set the $gcLimit parameter

Add options for entity calls in DatastoreSessionHandler

---

src/BigQuery/BigQueryClient.php
tests/snippets/BigQuery/BigQueryClientTest.php
tests/unit/BigQuery/BigQueryClientTest.php

This change modifies `BigQueryClient::runQuery()`. Rather than returning a `QueryResults` object which requires polling to retrieve a result, the poll will be executed within the method, and the return value will be an instance of `QueryResults` which is populated with result rows and can be immediately processed.
There's no BC break, though people currently using this method with the polling loops recommended in the past should consider removing extraneous polling operations.

Run query and wait for it to complete

---

README.md

Similar to [Node's getting started guide](https://github.com/GoogleCloudPlatform/google-cloud-node#quick-start), but including a short guide to authentication and ADC.
cc @michaelbausor @bjwatson @omaray

Add getting started and auth guide

---

src/BigQuery/Dataset.php
src/BigQuery/Table.php
src/Core/ConcurrencyControlTrait.php
tests/system/BigQuery/ManageDatasetsTest.php
tests/system/BigQuery/ManageTablesTest.php
tests/unit/BigQuery/DatasetTest.php
tests/unit/BigQuery/TableTest.php
tests/unit/Core/ConcurrencyControlTraitTest.php

I put the new trait in Core thinking it could be used elsewhere in the future. If you think it should be in BigQuery, I'm open to that too.

Add support for etags on bigquery tables and datasets

---

src/BigQuery/BigQueryClient.php
src/BigQuery/Job.php
src/BigQuery/QueryResults.php
tests/snippets/BigQuery/BigQueryClientTest.php
tests/snippets/BigQuery/JobTest.php
tests/snippets/BigQuery/QueryResultsTest.php
tests/unit/BigQuery/BigQueryClientTest.php
tests/unit/BigQuery/JobTest.php
tests/unit/BigQuery/QueryResultsTest.php

Introduced by this PR:
- It's no longer necessary to manually poll jobs for completion. `Google\Cloud\BigQuery\Job::waitUntilComplete()` has been added to help simplify the process. Closes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/89.
- `Google\Cloud\BigQuery\QueryResults` no longer inherits reload options.
- `Google\Cloud\BigQuery\Job::queryResults()` now blocks until the query is complete.
- `Google\Cloud\BigQuery\QueryResults::isComplete()` has been marked internal, as by the time 
`QueryResults` are passed back to the user rows are now guaranteed to be loaded.
- `Google\Cloud\BigQuery\QueryResults` now implements `IteratorAggregate`, allowing users to iterate directly over the `QueryResults`.
- `Google\Cloud\BigQuery\BigQueryClient::runQuery()` now implements …

[BC Break] Implement waitUntilComplete and block while waiting for query results

---

src/Core/GrpcTrait.php
tests/unit/Core/GrpcTraitTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/648

Fix timestamp formatting

---

src/Spanner/Session/CacheSessionPool.php
tests/unit/Spanner/Session/CacheSessionPoolTest.php

We are holding off on https://github.com/GoogleCloudPlatform/google-cloud-php/pull/646 until after beta. This PR implements changes we need to declare beta so that once we do merge #646 we will not introduce breaking changes.

[BC Break] Do not track failed session deletions

---

.travis.yml

For test preview, see [this log](https://travis-ci.org/jdpedrie/google-cloud-php/jobs/270450779)

Add PHP 7.2 to Travis CI

---

composer.json
dev/src/Release/Command/Release.php

The following works as expected:
```sh
$ php dev/google-cloud release -c google-cloud minor
Adding version 0.39.0 to Documentation Manifest for component google-cloud.
Setting component version constant to 0.39.0.
File Version.php VERSION constant updated to 0.39.0
File ServiceBuilder.php VERSION constant updated to 0.39.0
Release 0.39.0 generated!
```

adds version and servicebuilder to entry and release command

---

tests/unit/BigQuery/TableTest.php

Follow up to https://github.com/GoogleCloudPlatform/google-cloud-php/pull/669

Fix key used in TableData.List test

---

src/Dlp/V2beta1/Gapic/DlpServiceGapicClient.php
src/Logging/V2/Gapic/ConfigServiceV2GapicClient.php
src/Logging/V2/Gapic/LoggingServiceV2GapicClient.php
src/Spanner/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
src/Spanner/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
src/Speech/V1/Gapic/SpeechGapicClient.php
src/Speech/V1beta1/Gapic/SpeechGapicClient.php
src/VideoIntelligence/V1beta1/Gapic/VideoIntelligenceServiceGapicClient.php
src/VideoIntelligence/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php

Documentation update only, based on changes in toolkit and protos

Refresh GAPIC documentation

---

src/Spanner/Connection/Grpc.php
src/Spanner/Database.php
src/Spanner/Session/CacheSessionPool.php
src/Spanner/V1/SpannerClient.php
tests/unit/Spanner/Connection/GrpcTest.php
tests/unit/Spanner/Session/CacheSessionPoolTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/490
Please note, the circumvention of the GAPIC client is intended to be temporary until concurrent request support is built into the clients.

Implement automatic downsizing of session pool

---

src/Logging/Connection/Grpc.php

casts `$level` to an integer to ensure it can be handled by gRPC in `PsrLogger`. Otherwise, passing in a string (such as `"emergency"`) raises the following error:
```
PHP Notice:  Undefined index: warning in vendor/google/cloud-logging/Connection/Grpc.php on line 315
Notice: Undefined index: warning in vendor/google/cloud-logging/Connection/Grpc.php on line 315
[Exception]      
Expect integer.  
```

ensures PSR log level can be int or string

---

src/ErrorReporting/Bootstrap.php
tests/unit/ErrorReporting/BootstrapTest.php

The `Bootstrap` function can be used to hook into error reporting w/o requiring batch processing. This PR renames the logger's property to make this clear.

renames psrBatchLogger to psrLogger

---

src/Storage/Bucket.php
src/Storage/Connection/ConnectionInterface.php
src/Storage/Connection/Rest.php
src/Storage/Connection/ServiceDefinition/storage-v1.json
src/Storage/Notification.php
src/Storage/StorageClient.php
src/Storage/composer.json
tests/snippets/BigQuery/TableTest.php
tests/snippets/Storage/BucketTest.php
tests/snippets/Storage/NotificationTest.php
tests/snippets/Storage/StorageClientTest.php
tests/system/Storage/ManageNotificationsTest.php
tests/system/Storage/StorageTestCase.php
tests/unit/Storage/BucketTest.php
tests/unit/Storage/Connection/RestTest.php
tests/unit/Storage/NotificationTest.php
tests/unit/Storage/StorageClientTest.php
tests/unit/Storage/StorageObjectTest.php

For more information: https://cloud.google.com/storage/docs/pubsub-notifications
System tests to be added soon

Introduce Pub\Sub bucket notifications

---

tests/perf/LoggingPerfTestCase.php

https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Core/ClientTrait.php#L52
When the transport doesn't set, and the grpc extension is loaded, it will return "grpc" as the connection type.

LoggingPerfTestCase.php: fix rest start grpc client

---

phpunit-perf.xml.dist
tests/perf/BigQueryTest.php
tests/perf/LoggingPerfTest.php
tests/perf/README.md
tests/perf/fixtures/bigquery.json

Add BigQuery perf test, rename Logging perf test

---

src/Storage/Bucket.php
src/Storage/StorageClient.php
tests/system/Storage/RequesterPaysTest.php

Each of the callables in `requesterPaysMethods` is invoked twice -- once with a bucket without `userProject` (this case expects an exception), and once with a bucket with `userProject` (this case should succeed without an exception).
Delete notification is tested separately, because if there is no userProject, the create operation fails, which in turn will cause the delete to fail due to a NotFoundException, which is not expected.
This change also removes the whitelist notification.
/cc @frankyn

Add system test coverage for storage userProject

---

composer.json
src/Dlp/V2beta1/Gapic/DlpServiceGapicClient.php
src/Dlp/V2beta1/resources/dlp_service_client_config.json
src/ErrorReporting/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
src/ErrorReporting/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
src/ErrorReporting/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
src/Language/V1beta2/Gapic/LanguageServiceGapicClient.php
src/Logging/V2/Gapic/ConfigServiceV2GapicClient.php
src/Logging/V2/Gapic/LoggingServiceV2GapicClient.php
src/Logging/V2/Gapic/MetricsServiceV2GapicClient.php
src/Logging/V2/resources/config_service_v2_client_config.json
src/Logging/V2/resources/logging_service_v2_client_config.json
src/Logging/V2/resources/metrics_service_v2_client_config.json
src/Monitoring/V3/Gapic/GroupServiceGapicClient.php
src/Monitoring/V3/Gapic/MetricServiceGapicClient.php
src/PubSub/V1/Gapic/PublisherGapicClient.php
src/PubSub/V1/Gapic/SubscriberGapicClient.php
src/PubSub/V1/resources/publisher_client_config.json
src/PubSub/V1/resources/subscriber_client_config.json
src/Spanner/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
src/Spanner/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
src/Spanner/V1/Gapic/SpannerGapicClient.php
src/Spanner/V1/SpannerClient.php
src/Spanner/V1/resources/spanner_client_config.json
src/Speech/V1/Gapic/SpeechGapicClient.php
src/Speech/V1beta1/Gapic/SpeechGapicClient.php
src/VideoIntelligence/V1beta1/Gapic/VideoIntelligenceServiceGapicClient.php
src/VideoIntelligence/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
src/Vision/V1/Gapic/ImageAnnotatorGapicClient.php

(Mostly DLP)
The build will keep failing until  `google/proto-client ^0.25` and `google/gax ^0.25` are released.
Related PRs: 
https://github.com/googleapis/gax-php/pull/115
https://github.com/googleapis/proto-client-php/pull/41

Refresh GAPIcs

---

src/Dlp/V2beta1/Gapic/DlpServiceGapicClient.php
src/Dlp/V2beta1/resources/dlp_service_client_config.json
src/ErrorReporting/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
src/ErrorReporting/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
src/ErrorReporting/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
src/Language/V1beta2/Gapic/LanguageServiceGapicClient.php
src/Logging/V2/Gapic/ConfigServiceV2GapicClient.php
src/Logging/V2/Gapic/LoggingServiceV2GapicClient.php
src/Logging/V2/Gapic/MetricsServiceV2GapicClient.php
src/Monitoring/V3/Gapic/GroupServiceGapicClient.php
src/Monitoring/V3/Gapic/MetricServiceGapicClient.php
src/PubSub/V1/Gapic/PublisherGapicClient.php
src/PubSub/V1/Gapic/SubscriberGapicClient.php
src/Spanner/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
src/Spanner/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
src/Spanner/V1/Gapic/SpannerGapicClient.php
src/Speech/V1/Gapic/SpeechGapicClient.php
src/Speech/V1beta1/Gapic/SpeechGapicClient.php
src/VideoIntelligence/V1beta1/Gapic/VideoIntelligenceServiceGapicClient.php
src/VideoIntelligence/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
src/Vision/V1/Gapic/ImageAnnotatorGapicClient.php

1) Fix php-cs-fixer phpdoc_annotation_without_dot issue
2) Put back dlp gapic client class example

Fix generated PHP GAPIC classes

---

src/Translate/TranslateClient.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/758
@geekmeister thank you for filing the issue! Please let me know what you think of the updates to the documentation.

Update translation model documentation

---

src/Firestore/FirestoreClient.php
tests/snippets/Firestore/FirestoreClientTest.php
tests/unit/Firestore/FirestoreClientTest.php

Transaction callable now returns user value, not writeResult.
Implementation guide states:
> Transactions return the value provided by the user’s callback. It is not possible to obtain the WriteResult directly.
This change modifies the PHP client to better conform to requirements.

[Breaking Change] Change return value of FirestoreClient::runTransaction()

---

src/Datastore/Connection/Rest.php
src/Datastore/Entity.php
src/Datastore/EntityMapper.php
tests/system/Datastore/SaveAndModifyTest.php
tests/unit/Datastore/EntityMapperTest.php

cc @maksimru
This change adds support for excluding properties of embedded entities from datastore indexes.
```php
use Google\Cloud\Datastore\Entity;
$e = $datastore->entity('Person', [
'entity' => [
'prop' => 'val',
Entity::EXCLUDE_FROM_INDEXES => ['prop']
]
]);
$datastore->insert($e);
```
We've added a todo item for the next major version to improve on this, but for the time being this is the best option to avoid a backwards-compatibility break.

Add support for excludeFromIndexes in embedded entities

---

src/Firestore/DocumentReference.php
tests/unit/Firestore/DocumentReferenceTest.php

This change modifies the return value of mutation calls on DocumentReference. If multiple write results are found, the latest is now returned rather than the first. This is to better conform with the Firestore implementation guide, which states as follows:
> A single call to update() might return either one or two WriteResults (if there are DocumentTransforms). Since this generates an unexpected response, we should return only the latest of the WriteResults.
This change is not breaking.

Return latest write result

---

dev/src/Functions.php
src/Core/ClientTrait.php
src/Core/EmulatorTrait.php
src/Datastore/Connection/Rest.php
src/Datastore/DatastoreClient.php
src/PubSub/Connection/Grpc.php
src/PubSub/Connection/Rest.php
src/PubSub/PubSubClient.php
tests/unit/Core/ClientTraitTest.php
tests/unit/Core/EmulatorTraitTest.php

Disable authentication when using service emulator

---

src/BigQuery/composer.json
src/Datastore/composer.json
src/Firestore/composer.json
src/Language/composer.json
src/Logging/composer.json
src/PubSub/composer.json
src/Spanner/composer.json
src/Speech/composer.json
src/Storage/composer.json
src/Trace/composer.json
src/Translate/composer.json
src/Vision/composer.json

Closes #782. Replaces #786.
Question for the group: Would it be useful to script automated requirement bumps into the release process? i.e. when a new release of cloud-core is created, should we automatically update the requirement in all packages depending on cloud-core?

Update required cloud-core version

---

src/BigQuery/README.md
src/Bigtable/README.md
src/Core/README.md
src/Datastore/README.md
src/Dlp/README.md
src/ErrorReporting/README.md
src/Firestore/README.md
src/Language/README.md
src/Logging/README.md
src/Monitoring/README.md
src/PubSub/README.md
src/Spanner/README.md
src/Speech/README.md
src/Storage/README.md
src/Trace/README.md
src/Translate/README.md
src/VideoIntelligence/README.md
src/Vision/README.md

As suggested in #791 by @tswast. To help users understand the difference between versions of `google/cloud` and its various children.

Add badges to README files

---

README.md
src/Bigtable/README.md
src/Bigtable/composer.json
src/Dlp/README.md
src/Dlp/composer.json
src/ErrorReporting/composer.json
src/Firestore/FirestoreClient.php
src/Firestore/README.md
src/Firestore/composer.json
src/Language/README.md
src/Language/composer.json
src/Logging/LoggingClient.php
src/Logging/README.md
src/Logging/composer.json
src/Monitoring/README.md
src/Monitoring/composer.json
src/PubSub/PubSubClient.php
src/PubSub/README.md
src/PubSub/composer.json
src/Spanner/README.md
src/Spanner/SpannerClient.php
src/Spanner/composer.json
src/Speech/README.md
src/Speech/composer.json
src/VideoIntelligence/README.md
src/VideoIntelligence/composer.json
src/Vision/README.md

Closes #800.
Should we suggest this in other packages which support grpc, and in google-cloud-php as well?

Advise use of protobuf extension

---

src/BigQuery/BigQueryClient.php

With this change `BigQueryClient::runQuery` will wait for the job to complete before returning `QueryResults`, whereas currently `QueryResults` could be returned prior to job completion and the waiting would occur when a user goes to iterate the results.

When executing runQuery wait until complete before returning QueryResults

---

src/Core/ServiceBuilder.php
tests/unit/Core/ServiceBuilderTest.php
tests/unit/fixtures/json-key-fixture.json

So I've been investigating the report in #766, and found that the constructor `$config` is passed to services ONLY when no child `$config` is set.
For instance:
```php
use Google\Cloud\ServiceBuilder;
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/keyfile1.json');
$cloud = new ServiceBuilder([
'keyFilePath' => '/path/to/keyfile2.json'
]);
// uses `keyfile2.json`
$datastore = $cloud->datastore();
// uses `keyfile1.json`
$datastore = $cloud->datastore([
'namespaceId' => 'myApp'
]);
```
This strikes me as incorrect, as it prevents e.g. SpeechClient from setting a languageCode and using ServiceBuilder-level credentials. My proposed solution simply merges ServiceBuilder and factory method configuration, preferring keys given later.
If accepted, this PR closes #766.
edit: for a demonstration, …

Pass ServiceBuilder construct config into children

---

src/Core/Report/GAEFlexMetadataProvider.php
src/Logging/PsrLogger.php
tests/unit/Core/Report/GAEFlexMetadataProviderTest.php
tests/unit/Logging/PsrLoggerBatchTest.php

Also copy the traceid to the top level `trace` option.
Related to #827

Use GOOGLE_CLOUD_PROJECT for project id detection on App Engine Flex.

---

src/Storage/StorageObject.php
tests/system/Storage/SignedUrlTest.php
tests/unit/Storage/StorageObjectTest.php

Fixes additional report in #562.
This change modifies the signedUrl() method of StorageObject to url encode each piece of a path individually, preserving the forward-slashes as unencoded characters.

Encode signed URLs in nested folders correctly

---

src/Debugger/Daemon.php
src/Debugger/Debuggee.php
tests/snippets/Debugger/DaemonTest.php
tests/snippets/Debugger/DebuggeeTest.php
tests/unit/Debugger/DaemonTest.php
tests/unit/Debugger/DebuggeeTest.php

In order to correctly poll/wait for breakpoint configuration changes, you need to return the `nextWaitToken` to pass to the next breakpoint list call. In cleaning up the code design of `Debuggee#breakpoints`, we lost the next wait token.
* Added a `Debuggee#breakpointsWithWaitToken` that returns an associative array with the `nextWaitToken` and list of `breakpoints`.
* Fixes the Daemon to use this new method in its run loop.

Debugger: return nextWaitToken with breakpoints list

---

src/Debugger/Daemon.php
tests/snippets/Debugger/DaemonTest.php
tests/unit/Debugger/DaemonTest.php
tests/unit/Debugger/example/file.php
tests/unit/Debugger/example/nested/folder/file2.php

The extSourceContext field should be empty when there is no
`source-contexts.json` file available.
The default uniquifier should be based off a SHA1 of available files to
debug (.php files). We add the file size as a proxy for detecting
changes.

Debugger: Default source context and default uniquifier

---

dev/google-cloud
dev/src/AddComponent/Command/AddComponent.php
dev/src/AddComponent/ComponentTypeTrait.php
dev/src/AddComponent/Composer.php
dev/src/AddComponent/Contributing.php
dev/src/AddComponent/Info.php
dev/src/AddComponent/License.php
dev/src/AddComponent/Manifest.php
dev/src/AddComponent/PathTrait.php
dev/src/AddComponent/QuestionTrait.php
dev/src/AddComponent/Readmes.php
dev/src/AddComponent/TableOfContents.php
dev/src/AddComponent/templates/template-CONTRIBUTING.md.txt
dev/src/AddComponent/templates/template-README.md-both-grpc.txt
dev/src/AddComponent/templates/template-README.md-gapic-grpc.txt
dev/src/AddComponent/templates/template-README.md-gapic.txt
dev/src/AddComponent/templates/template-README.md.txt

To simplify the process of adding a new component and to make it easier for those not as familiar with the workings of Google Cloud PHP, we're adding an interactive CLI to configure new components.
This CLI is built with the intention of being used for gapic-only clients, but will work with handwritten veneers as well. I've tried to include explanations and suggestions wherever possible to make it as straightforward as possible.
Running it is simple:
```
$ dev/google-cloud component
```
I've created a branch with Bigtable completely uninitialized -- that is, the gapics are present, but no component setup has been done, in order to allow you to try it out. You can find it here: https://github.com/jdpedrie/google-cloud-php/tree/bigtable-uninitialized

Add CLI for creating new component.

---

src/Debugger/Breakpoint.php
tests/unit/Debugger/BreakpointValidationTest.php

Adds additional validation to a breakpoint by validating the source location.
* Ensure the file exists and is readable
* Ensure the file is a .php file
* Ensure the line is not empty or a comment line
The `Daemon` does the validation and immediately reports validation errors back to the stackdriver server.

Debugger: Validate breakpoint file and line

---

src/Debugger/DebuggerClient.php
tests/system/Debugger/BasicTest.php
tests/unit/Debugger/DebuggerClientTest.php

Catches a bug where the wrong parameter (`projectId` -> `project`) is being passed to the connection for `listDebuggees`

Adds debugger system test

---

src/Debugger/Breakpoint.php
src/Debugger/Debuggee.php
src/Debugger/SourceLocationResolver.php
tests/system/Debugger/BasicTest.php
tests/unit/Debugger/BreakpointTest.php
tests/unit/Debugger/DebuggeeTest.php
tests/unit/Debugger/JsonTestTrait.php
tests/unit/Debugger/SourceLocationResolverTest.php

* `resolvedLocation` should not be included in the json payload
* `resolvedLocation` should be relative to the sourceRoot - the extension
requires relative paths.

Debugger: resolvedLocation bugfix

---

tests/system/Bigtable/BigtableInstanceAdminTest.php
tests/system/Container/ClusterManagerClientTest.php
tests/system/Dataproc/ClusterControllerClientTest.php
tests/system/OsLogin/OsLoginServiceClientTest.php
tests/system/Spanner/SpannerTestCase.php

- Adds system tests for GAPIC clients w/o samples to test
- Fixes a bug in Spanner system tests

Adds system tests for GAPIC clients

---

src/Debugger/Connection/ConnectionInterface.php
src/Debugger/Connection/Rest.php
src/Debugger/Debuggee.php
tests/snippets/Debugger/DebuggeeTest.php
tests/system/Debugger/BasicTest.php
tests/unit/Debugger/Connection/RestTest.php
tests/unit/Debugger/DebuggeeTest.php

Most developers using Stackdriver Debugger will set their breakpoints from the Cloud Debugger UI Console (hence this functionality was not exposed previously). Surfacing this API will make end-to-end and system tests simpler.

Debugger: Expose setBreakpoint method

---

src/BigQuery/BigQueryClient.php
src/BigQuery/Table.php

We have received guidance to retry requests on a 502 error code.

Retry on 502 errors

---

dev/src/AddComponent/Command/AddComponent.php
dev/src/AddComponent/PathTrait.php
dev/src/AddComponent/PullRequestTemplate.php
dev/src/AddComponent/templates/template-pull_request_template.md.txt
dev/src/DocGenerator/DocGenerator.php
src/BigQuery/.github/pull_request_template.md
src/Bigtable/.github/pull_request_template.md
src/Container/.github/pull_request_template.md
src/Core/.github/pull_request_template.md
src/Dataproc/.github/pull_request_template.md
src/Datastore/.github/pull_request_template.md
src/Debugger/.github/pull_request_template.md
src/Dlp/.github/pull_request_template.md
src/ErrorReporting/.github/pull_request_template.md
src/Firestore/.github/pull_request_template.md
src/Language/.github/pull_request_template.md
src/Logging/.github/pull_request_template.md
src/Monitoring/.github/pull_request_template.md
src/OsLogin/.github/pull_request_template.md
src/PubSub/.github/pull_request_template.md
src/Spanner/.github/pull_request_template.md
src/Speech/.github/pull_request_template.md
src/Storage/.github/pull_request_template.md
src/Trace/.github/pull_request_template.md
src/Translate/.github/pull_request_template.md
src/VideoIntelligence/.github/pull_request_template.md
src/Vision/.github/pull_request_template.md

From time to time we've had pull requests opened against read-only repos. We're not able to accept those changes, and must redirect users to the parent repository. Github does not offer a way to disable pull requests on a repository.
This change adds a pull request template to each component, informing users that the pull request cannot be accepted and offering information on updating the pull and sending it to the correct repository. It also modifies the Add Component CLI to ensure that the PR template is added when a new component is created.

Add pull request template to sub packages

---

src/Core/Testing/StubTrait.php
src/Core/Testing/TestHelpers.php
src/Datastore/Connection/ServiceDefinition/datastore-v1.json
src/Datastore/DatastoreClient.php
src/Datastore/ReadOnlyTransaction.php
src/Datastore/Transaction.php
src/Datastore/TransactionTrait.php
tests/snippets/Datastore/DatastoreClientTest.php
tests/snippets/Datastore/ReadOnlyTransactionTest.php
tests/snippets/Datastore/TransactionTest.php
tests/unit/Datastore/DatastoreClientTest.php

This change adds support for Datastore Transaction Options and Read-Only Transactions.

Add support for read-only transactions and transaction options

---

src/Debugger/Daemon.php
src/Debugger/Debuggee.php
tests/unit/Debugger/DaemonTest.php

Adding `projectid`, `module`, and `version` labels to the `Debuggee` when registering allows the debugger UI to link a debugger instance with both logging (via resource labels), and App Engine (by providing a link to debugger from an AppEngine service or version page).

Debugger: Register Debuggee with labels

---

composer.json
src/Core/Batch/BatchTrait.php
src/Core/Batch/ClosureSerializerInterface.php
src/Core/Batch/OpisClosureSerializer.php
src/Core/composer.json
src/Debugger/Agent.php
src/Logging/LoggingClient.php
src/Logging/PsrLogger.php
src/PubSub/BatchPublisher.php
src/PubSub/Topic.php
tests/unit/Core/Batch/OpisClosureSerializerTest.php
tests/unit/Logging/LoggingClientTest.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/588
@chingor13 What do you think? The goal of this approach was to add a lower friction way for users to supply closures to configurations used in the batch daemon. I looked at making these changes in `Google\Cloud\Core\Batch\SysvConfigStorage` but was concerned it wasn't very straight forward to supply a custom interface [when initializing the daemon](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Core/bin/google-cloud-batch#L45).

Introduce options to serialize closures for batch processing

---

composer.json
src/Debugger/Agent.php
src/Debugger/CliDaemon.php
src/Debugger/Daemon.php
src/Debugger/README.md
src/Debugger/bin/google-cloud-debugger
src/Debugger/composer.json
tests/unit/Debugger/CliDaemonTest.php
tests/unit/Debugger/data/daemon_config.php
tests/unit/Debugger/data/daemon_config_wrong_return.php

* Updates README with how to install on windows vs. unix
* Agent will only try to start the Daemon via the unified batch/async daemon if batch daemon is running and sysv is available.
* Puts `google-cloud-debugger` bin script back
* Adds more command line options for specifying a config script
* Does not start the daemon if the batch daemon is running and sysv is available (it will be started by the Agent - inverse of the above scenario).

Debugger: Windows compatibility

---

src/Debugger/Agent.php

The default log name for logpoints should be `appengine.googleapis.com%2Frequest_log`. Note that the `/` is uri encoded here (@dwsupplee - I'm not sure if the user should be expected to escape the log name).
Naming the log name like this allows the Debug UI to show logpoints in a special location on the same page without having to navigate to the Logging UI.
Also prefixes the logpoint message with `LOGPOINT: ` to match what other languages' agents are doing.

Debugger: Logpoint name

---

appveyor.yml
appveyor_install_php.ps1
src/Core/Testing/DatastoreOperationRefreshTrait.php
src/Datastore/DatastoreClient.php
src/Datastore/EntityMapper.php
src/Datastore/Key.php
src/Datastore/Operation.php
src/Datastore/Transaction.php
tests/snippets/Datastore/DatastoreClientTest.php
tests/snippets/Datastore/ReadOnlyTransactionTest.php
tests/snippets/Datastore/TransactionTest.php
tests/unit/Datastore/DatastoreClientTest.php
tests/unit/Datastore/EntityMapperTest.php
tests/unit/Datastore/OperationTest.php
tests/unit/Datastore/TransactionTest.php

Closes #903.
I did some housecleaning as well. When I added the feature, I found that the tests were lacking in some ways, and that certain minor features of the client were in need of improvement.

Add allocate ID to upsert methods, refactor tests

---

appveyor.yml
dev/appveyor-grpc.ps1

This change adds support for running tests requiring gRPC in Windows environments.
Currently, the gRPC extension is build for >= PHP 7.0, therefore builds running on PHP 5.x continue to be excluded.
I chose to embed the extension download URI in the build matrix for a couple of reasons. First, it was quite difficult to predict the file name. Second, it makes updating when new versions of gRPC are released very straightforward.

Install gRPC on Windows CI when available

---

docs/manifest.json
src/ServiceBuilder.php
src/Version.php

The main package's version has been correctly incremented, there are no other changes in this release.

Prepare v0.57.1

---

composer.json
dev/src/ComponentIntegration/Command/ComponentIntegration.php
dev/src/GetComponentsTrait.php

When running `dev/google-cloud integration`, the new pre-release CLI, the umbrella package (i.e. `google/cloud`) version will be checked. If it has not been bumped for release, the CLI will return a non-zero exit code (i.e. an error).
This check can be disabled for development purposes by providing the `--umbrella|-u` option flag:
```
$ dev/google-cloud integration
$ dev/google-cloud integration -u
```
The version check will, as for each component, execute a Github API request, and thus it is recommended that you authenticate with github by setting the `GH_OAUTH_TOKEN` environment variable to a valid Github API token.
This change also adds a cleanup to remove `.testing` at the end of execution. Previously, in the case of error, the directory was not removed. A new option flag, …

Check that umbrella version has been bumped

---

Datastore/src/EntityMapper.php
Datastore/tests/System/SaveAndModifyTest.php
Datastore/tests/Unit/EntityMapperTest.php

Fixes #970.
ListValue cannot be nested within ListValue. Therefore we can assume that if an empty array is provided within a ListValue, it must be encoded as EntityValue to prevent error.
```php
$datastore->insert($datastore->entity($key, [
'arr' => [
['foo'], // This would raise an error. Can't nest ListValues inside ListValue.
[], // This will be encoded as an EntityValue.
]
]));
```
The behavior for top-level values is a bit different. This will also hold true in embedded entities. To encode empty arrays as EntityValue, you must use an object cast.
```php
$datastore->insert($datastore->entity($key, [
'arr' => [], // This will encode as a ListValue.
'obj' => (object) [] // This will encode as an EntityValue.
]));
```

Serialize empty objects in arrays as entities

---

BigQuery/src/BigQueryClient.php
BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/src/CopyJobConfiguration.php
BigQuery/src/Dataset.php
BigQuery/src/ExtractJobConfiguration.php
BigQuery/src/Job.php
BigQuery/src/JobConfigurationTrait.php
BigQuery/src/LoadJobConfiguration.php
BigQuery/src/QueryJobConfiguration.php
BigQuery/src/QueryResults.php
BigQuery/src/Table.php
BigQuery/tests/Snippet/BigQueryClientTest.php
BigQuery/tests/Snippet/CopyJobConfigurationTest.php
BigQuery/tests/Snippet/ExtractJobConfigurationTest.php
BigQuery/tests/Snippet/LoadJobConfigurationTest.php
BigQuery/tests/Snippet/QueryJobConfigurationTest.php
BigQuery/tests/System/BigQueryTestCase.php
BigQuery/tests/System/RegionalizationTest.php
BigQuery/tests/Unit/BigQueryClientTest.php
BigQuery/tests/Unit/CopyJobConfigurationTest.php
BigQuery/tests/Unit/ExtractJobConfigurationTest.php
BigQuery/tests/Unit/JobConfigurationTraitTest.php
BigQuery/tests/Unit/JobTest.php
BigQuery/tests/Unit/LoadJobConfigurationTest.php
BigQuery/tests/Unit/QueryJobConfigurationTest.php
Core/src/ServiceBuilder.php
phpunit-snippets.xml.dist

This change set introduces the ability to supply a location when managing jobs.
Some usage examples:
```php
use Google\Cloud\BigQuery\BigQueryClient;
// This default location will be used for creating datasets as well as any job activity
// where we can't infer the location from a network request.
$client = new BigQueryClient([
'location' => 'asia-northeast1'
]);
// All calls through this job will be routed to the `asia-northeast1` region, using
// the default supplied in the client config.
$job = $client->job('an-existing-job');
// Users can explicitly specify the location if they did not include one in the client
// config or want to override it. With an existing job...
$job = $client->job('an-existing-job', [
'location' => 'asia-northeast1'
]);
// And when creating a job …
```

Introduce BigQuery Regionalization Support

---

Firestore/src/FirestoreClient.php
Firestore/src/PathTrait.php
Firestore/src/SnapshotTrait.php
Firestore/src/Transaction.php
Firestore/tests/Snippet/TransactionTest.php
Firestore/tests/System/GetAllDocumentsTest.php
Firestore/tests/Unit/FirestoreClientTest.php
Firestore/tests/Unit/TransactionTest.php
tests/system/Firestore/GetAllDocumentsTest.php

To support retrieval of a specific set of document snapshots within transactions, this PR adds a method similar to FirestoreClient::documents(), accepting an array of paths or DocumentReference objects and returning a list of DocumentSnapshot instances.
cc @schmidt-sebastian

Add documents() method to Firestore Transaction

---

Debugger/src/Agent.php

The stackdriver_debugger extension ([0.2.0](https://pecl.php.net/package/stackdriver_debugger/0.2.0)) can now handle detecting and clearing opcache when setting breakpoints.

Debugger: Agent no longer needs to clear opcache.

---

Debugger/src/Breakpoint.php
Debugger/src/VariableTable.php
Debugger/tests/Unit/VariableTableTest.php

This is an optimization to reduce the payload size and time spent by the debugger.
stackdriver_debugger 0.2.0 adds an `id` field for captured variables (arrays, strings, objects). Implemented [here](https://github.com/GoogleCloudPlatform/stackdriver-debugger-php-extension/pull/41).
If provided, use that `id` to de-dup variables in the `VariableTable` (previously we used `spl_object_hash` which is only available for objects).
This is useful for large arrays (like `$_SERVER`) so that we don't need to have multiple copies of the same nested data structure when reporting variables to stackdriver.

Debugger: De-dup arrays and string in VariableTable

---

Spanner/tests/Unit/Connection/GrpcTest.php

The prophesy of `DeleteSessionRequest` is not used, and causes issues when running the unit tests with `ext-protobuf` enabled.

Remove unused proto class prophesy

---

Firestore/src/DocumentSnapshot.php
Firestore/tests/Snippet/DocumentSnapshotTest.php
Firestore/tests/System/DocumentAndCollectionTest.php
Firestore/tests/System/QueryTest.php
Firestore/tests/System/TransactionTest.php
Firestore/tests/Unit/DocumentSnapshotTest.php

Closes #990.
Rename DocumentSnapshot::fields() to data(), and return null if document doesn't exist.

[Breaking Change] Rename DocumentSnapshot::fields() to data().

---

README.md
Spanner/README.md
Spanner/src/Session/CacheSessionPool.php

See #989 
Preview available on:
https://github.com/tmatsuo/google-cloud-php/tree/docs-for-989
https://github.com/tmatsuo/google-cloud-php/tree/docs-for-989/Spanner
https://github.com/tmatsuo/google-cloud-php/blob/docs-for-989/Spanner/src/Session/CacheSessionPool.php

Added documentation for SysVCacheItemPool

---

Firestore/src/ValueMapper.php
Firestore/tests/Unit/ValueMapperTest.php

Currently it is not possible to encode an empty array as a Firestore [ArrayValue](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.ArrayValue). This change will encode `[]` as `ArrayValue`, and `(object) []` as [`MapValue`](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.MapValue). This is in line with changes made in other areas of the library, namely Datastore in #974.
This issue was first reported in #996.

Encode empty arrays as firestore arrays

---

appveyor.yml

We have been having a lot of trouble with appveyor builds failing because the composer download breaks and is not retried. This change switches from the appveyor DownloadFile utility to curl with retries enabled. I expect that this will limit the frequency of annoying failures.

[Appveyor] Retry composer download on failure

---

Debugger/src/Agent.php
Debugger/tests/Unit/AgentTest.php

When using the background batch runner, the Agent configures the Daemon's configuration. We should allow you to configure the Daemon's settings at this time.

[Debugger] Add Daemon options to Agent

---

Logging/tests/System/ManageSinksTest.php

The `-` causes a warning in PHP 7.1+.

Remove stray operator from system test

---

BigQuery/src/LoadJobConfiguration.php

A new source format, parquet, has been introduced for load jobs.

Add parquet format to load job configuration docs

---

Storage/src/Bucket.php
Storage/src/StorageClient.php
Storage/src/StorageObject.php
Storage/tests/Snippet/BucketTest.php
Storage/tests/System/KmsTest.php
Storage/tests/System/ManageNotificationsTest.php
Storage/tests/System/StorageTestCase.php

With this change set users can now supply a KMS key name while uploading or rewriting objects in order to take advantage of the KMS service.
Example:
```php
$fileHandle = fopen(__DIR__ . '/image.jpg', 'r');
$object = $bucket->upload($fileHandle, [
'metadata' => [
'kmsKeyName' => 'projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key'
]
]);
```

Introduce Cloud KMS key name support

---

ErrorReporting/src/Bootstrap.php
ErrorReporting/tests/Unit/BootstrapTest.php

Without the `reportLocation` property, the `exceptionHandler` function does not actually populate the serviceContext data. Also, we have the reportLocation data via the exception so we can plug it in.
I believe the intention here was the stack trace would be parsed, but this is not working as expected so we should just plug the actual data in.

adds context to exception handler

---

Debugger/src/Debuggee.php
Debugger/tests/Unit/DebuggeeTest.php

This fixes a bug where the debuggee may not correctly register. This fixes the E2E Debugger test.

Debugger: Fix loading source context as array from source-contexts.json

---

Debugger/bin/google-cloud-debugger

On our documentation we say PHP 7.0 is necessary to use Stackdriver, however this debugger library uses the `$optind` parameter for `getopt`, said parameter was only added on 7.1 and it throws a Fatal error when using with PHP 7.0.
* Changelog: [http://php.net/manual/en/function.getopt.php#refsect1-function.getopt-changelog](http://php.net/manual/en/function.getopt.php#refsect1-function.getopt-changelog)
* [Documentation Stackdriver](https://cloud.google.com/debugger/docs/setup/php)
This PR removes it since it's not being used to keep the library compatible with 7.0

Removing $optind variable

---

Logging/src/LoggingClient.php
Logging/src/PsrLogger.php
Logging/tests/Unit/LoggingClientTest.php
Logging/tests/Unit/PsrLoggerTest.php

Fixes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1107

Ensure all batch related options can be passed through to PSR logger

---

Core/src/Iterator/ItemIteratorTrait.php

The return type lists `array|null`, however it can actually return any type. E.g., in `EntityIterator`, it returns `Entity|null`.

Fix return type for ItemIteratorTrait->current

---

Firestore/tests/System/DocumentAndCollectionTest.php
Firestore/tests/System/FirestoreTestCase.php
Firestore/tests/System/GetAllDocumentsTest.php
Firestore/tests/System/QueryTest.php
Firestore/tests/System/README.md
Firestore/tests/System/TransactionTest.php
Firestore/tests/System/ValueMapperTest.php
Firestore/tests/System/bootstrap.php

This change fixes an issue where if system test artifacts remain, the next test run will fail.
All test collections are uniquely named and will not conflict with previous test executions. Additionally, the cleanup process has been improved to make it simpler to be sure all artifacts are removed upon test completion.

Cleanup Firestore system test artifacts

---

Bigtable/README.md
Dataproc/README.md
Dlp/README.md
Kms/README.md
Redis/README.md
TextToSpeech/README.md
VideoIntelligence/README.md

Replaces https://github.com/GoogleCloudPlatform/google-cloud-php-redis/pull/1.
The [Redis page 404's](https://cloud.google.com/memorystore) if the trailing slash is not present. This seems to be somewhat inconsistent across cloud.google.com, so I added them where missing to be safe.

Add missing links and trailing slashes to README files

---

Vision/src/Annotation/SafeSearch.php
Vision/tests/Snippet/Annotation/SafeSearchTest.php
Vision/tests/System/AnnotationsTest.php
Vision/tests/Unit/Annotation/SafeSearchTest.php

The SafeSearch class included `is` functions for each SafeSearch feature (adult, spoof, medical, violence), but was missing Racy. This Pull Request adds `isRacy()` to the SafeSearch class.

Add isRacy() to SafeSearch

---

Core/src/Testing/FileListFilterIterator.php
Core/src/Testing/RegexFileFilter.php
Core/src/Testing/TestHelpers.php
dev/src/DocGenerator/Command/Docs.php

Exclude component vendor folder from snippet coverage

---

BigQuery/src/BigQueryClient.php
BigQuery/src/Connection/ConnectionInterface.php
BigQuery/src/Connection/Rest.php
BigQuery/tests/Snippet/BigQueryClientTest.php
BigQuery/tests/Unit/BigQueryClientTest.php
BigQuery/tests/Unit/Connection/RestTest.php

See:
https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/getServiceAccount

Add getServiceAccount to the BigQueryClient

---

Firestore/src/Query.php
Firestore/tests/Unit/QueryTest.php

* [Breaking] `Query::select()` now overwrites previous selects rather than merging/appending.
* [Bugfix] `Query::documents()` now correctly handles setting `maxRetries` to zero.

[Breaking Change] Fix firestore queries

---

dev/google-cloud
dev/src/AddComponent/Command/AddComponent.php
dev/src/AddComponent/Composer.php
dev/src/AddComponent/Info.php
dev/src/AddComponent/Manifest.php
dev/src/AddComponent/Readmes.php
dev/src/AddComponent/TableOfContents.php
dev/src/ComponentVersionTrait.php
dev/src/GetComponentsTrait.php
dev/src/QuestionTrait.php
dev/src/Release/Release.php
dev/src/ReleaseBuilder/ReleaseBuilder.php
dev/src/ReleaseBuilder/templates/release-notes.md.txt

This change adds an interactive CLI to the `dev/google-cloud` tool to create releases.
```sh
$ dev/google-cloud rb
```
The tool makes use of the Github API. To avoid rate-limiting errors, set `GH_OAUTH_TOKEN` environment variable to a Github OAuth token.
Please take it for a test drive and let me know what you think. I'm sure that as it is used, we'll find ways to tweak it and improve its usefulness.

Add an interactive release builder.

---

Storage/src/Connection/ConnectionInterface.php
Storage/src/Connection/Rest.php
Storage/src/StorageClient.php
Storage/tests/Snippet/StorageClientTest.php
Storage/tests/System/KmsTest.php
Storage/tests/Unit/Connection/RestTest.php
Storage/tests/Unit/StorageClientTest.php

This adds a way to programmatically fetch the service account, similarly to https://github.com/GoogleCloudPlatform/google-cloud-php/pull/1167 for BigQuery.
Addresses https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1079#issuecomment-404871481

Add getServiceAccount method to StorageClient

---

Firestore/src/CollectionReference.php
Firestore/src/DocumentSnapshot.php
Firestore/src/FieldValue.php
Firestore/src/Query.php
Firestore/src/ValueMapper.php
Firestore/tests/Snippet/QueryTest.php
Firestore/tests/System/QueryTest.php
Firestore/tests/Unit/QueryTest.php

cc @schmidt-sebastian
Extracted from #923 and updated to address pull request comments.
Breaking change is the standardization in Query of using `InvalidArgumentException`, replacing various throws of `BadMethodCallException`.
Closes #851.

[Breaking Change] Add support for Document Snapshots in Firestore Query Cursors

---

BigQuery/src/BigQueryClient.php
BigQuery/tests/System/ManageJobsTest.php
BigQuery/tests/Unit/BigQueryClientTest.php

The spec is at:
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/list

Added a document for the time filter on BigQueryClient->jobs()

---

Core/src/Upload/ResumableUploader.php
Core/src/Upload/SignedUrlUploader.php
Storage/src/StorageObject.php
Storage/tests/System/SignedUrlTest.php
Storage/tests/Unit/StorageObjectTest.php

Fixes #1108, #1056, #1055.
This change attempts to add missing feature support for Cloud Storage Signed URLs and to make the existing functionality simpler and less error-prone.
* Added support for CORS on object upload. Calls to `StorageObject::beginSignedUploadSession()` now support the `origin` option.
* `StorageObject::signedUrl()` catches more fatal mistakes related to headers earlier, throwing an exception with useful errors rather than the cryptic error returned when an invalid URL is requested by a user.
* Setting `contentType` on `StorageObject::signedUrl()` no longer sets the value of `response-content-type`.
* Custom headers are sorted by their name within the client. Previously the user needed to provide properly ordered headers.
* Added additional system test coverage.

Improve Signed URLs

---

composer.json

The [latest patch to the auth library](https://github.com/google/google-auth-library-php/releases/tag/v1.3.2) includes fixes which allow us to loosen this requirement again.

Remove auth library restriction

---

Spanner/src/Operation.php
Spanner/tests/System/WriteTest.php
Spanner/tests/Unit/OperationTest.php

Allow setting field values to null

---

Firestore/src/CollectionReference.php

Clarifies the documentation for creating documents via CollectionReference. Since both of those methods generate a random document ID, this change adds a note on creating documents with specified IDs.
In response to #1210.

Update collection documentation for specifying document IDs

---

Core/src/ClientTrait.php
Core/tests/Unit/ClientTraitTest.php

Trigger notice if keyfile is missing a project ID

---

Debugger/src/Breakpoint.php

Following up on: https://github.com/GoogleCloudPlatform/google-cloud-php/pull/1223#discussion_r210728416

Update Breakpoint constants

---

Bigtable/src/DataClient.php
Bigtable/tests/Unit/DataClientTest.php

Bigtable Mutate rows optional parameter

Bigtable Mutate rows optional parameter

---

BigQueryDataTransfer/composer.json
Bigtable/composer.json
Container/composer.json
Core/composer.json
Dataproc/composer.json
Debugger/composer.json
Dialogflow/composer.json
Dlp/composer.json
ErrorReporting/composer.json
Firestore/composer.json
Iot/composer.json
Kms/composer.json
Language/composer.json
Logging/composer.json
Monitoring/composer.json
OsLogin/composer.json
PubSub/composer.json
Redis/composer.json
Spanner/composer.json
Spanner/src/V1/Gapic/SpannerGapicClient.php
Spanner/src/V1/resources/spanner_grpc_config.json
Speech/composer.json
Tasks/composer.json
TextToSpeech/composer.json
Trace/composer.json
VideoIntelligence/composer.json
Vision/composer.json
composer.json

This reverts commit e646b9cf9784a9eda14d08ff8e76aa39c0de5795.
This brings back the reverted changes on spanner grpc config, which was previously causing file descriptors leak on macOS.
Related fix: https://github.com/GoogleCloudPlatform/grpc-gcp-php/pull/25

Revert "Revert "Spanner grpc config" (#1240)"

---

Debugger/src/AliasContext.php

[GAX v0.37.0](https://github.com/googleapis/gax-php/releases/tag/0.37.0) updated some shared protobuf classes to our new namespace format, this brings `Google\Cloud\Debugger\AliasContext`  into line with these changes.

Update AliasContext constants

---

Spanner/src/Database.php
Spanner/tests/Snippet/DatabaseTest.php
Spanner/tests/Unit/DatabaseTest.php

Delete all sessions when dropping database

---

Firestore/src/FieldValue.php
Firestore/src/FieldValue/ArrayRemoveValue.php
Firestore/src/FieldValue/ArrayUnionValue.php
Firestore/src/FieldValue/DeleteFieldValue.php
Firestore/src/FieldValue/DocumentTransformInterface.php
Firestore/src/FieldValue/DocumentTransformTrait.php
Firestore/src/FieldValue/FieldValueInterface.php
Firestore/src/FieldValue/FieldValueTrait.php
Firestore/src/FieldValue/ServerTimestampValue.php
Firestore/src/Query.php
Firestore/src/ValueMapper.php
Firestore/src/WriteBatch.php
Firestore/tests/Snippet/FieldValueTest.php
Firestore/tests/Snippet/QueryTest.php
Firestore/tests/System/DocumentAndCollectionTest.php
Firestore/tests/System/SentinelValueTest.php
Firestore/tests/Unit/FieldPathTest.php
Firestore/tests/Unit/FieldValueTest.php
Firestore/tests/Unit/QueryTest.php
Firestore/tests/Unit/WriteBatchTest.php

This change adds support for adding array elements and removing array elements. It also adds support for querying using the `array-contains` operator.
The bulk of the work is in a refactor of WriteBatch to improve handling of values from the FieldValue statics. The work is based heavily off of the latest iteration of [nodejs-firestore](https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/field-value.ts) and should allow much easier implementation of future DocumentTransform values.
The breaking changes are minor and should not impact users in normal (expected) usage, though should still be noted.
* `Google\Cloud\Firestore\FieldValue` method return values have changed.
* `Google\Cloud\Firestore\WriteBatch::REQUEST_TIME` moved to …

[Breaking Change] Firestore array operations

---

Core/src/Iterator/PageIteratorTrait.php
Datastore/src/EntityPageIterator.php
Storage/src/ObjectPageIterator.php

Renaming this private method ended up being a mistake, and can cause issues.

Revert back to old method name

---

Core/src/GrpcRequestWrapper.php
Core/src/GrpcTrait.php
Core/src/LongRunning/OperationResponseTrait.php

Closes: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1259
Our components with a handwritten layer rely on the core component up to version 2.0. When installing old versions of said components, it is possible to be relying on versions of GAX which cause conflicts with the latest version of the core component. One fix for this issue is to lock in to a specific version of core when installing the component, but with this solution users shouldn't have to do anything.
The two areas identified as problematic:
- A namespace update from `Google\GAX\*` to `Google\ApiCore\*`.
- A change in the way GAPICs configure credentials -  from accepting a key `credentialsLoader` with an instance of a class implementing `Google\Auth\FetchAuthTokenInterface` to accepting a key of …

Address gax changes in core

---

Storage/src/Bucket.php
Storage/src/Lifecycle.php
Storage/src/StorageClient.php
Storage/tests/Snippet/BucketTest.php
Storage/tests/Snippet/LifecycleTest.php
Storage/tests/System/ManageBucketsTest.php
Storage/tests/Unit/BucketTest.php
Storage/tests/Unit/LifecycleTest.php
Storage/tests/Unit/StorageClientTest.php

With this change set `Google\Cloud\Storage\StorageClient::createBucket()` and `Google\Cloud\Storage\Bucket::update()` can now both accept an instance of `Google\Cloud\Storage\Lifecycle` as opposed to a raw array.
Sample usage:
```php
use Google\Cloud\Storage\Bucket;
use Google\Cloud\Storage\StorageClient;
$storage = new StorageClient;
$bucket = $storage->createBucket('myBeautifulBucket', [
'lifecycle' => Bucket::lifecycle()
->addDeleteRule([
'age' => 50
])
]);
```
/cc @frankyn

Add more in-depth support for object lifecycle management

---

dev/sh/build-docs

This was used as debug information quite some time ago, and isn't really necessary anymore. Removing it should help make parsing the build logs a little easier.

Remove debug information from build

---

BigQuery/tests/System/LoadDataAndQueryTest.php
Datastore/tests/Unit/EntityMapperTest.php
Debugger/tests/Unit/AgentTest.php
Debugger/tests/Unit/VariableTableTest.php
Storage/tests/System/ManageBucketsTest.php
Storage/tests/System/ManageNotificationsTest.php
Storage/tests/System/UploadObjectsTest.php
Vision/tests/System/AnnotationsTest.php
Vision/tests/Unit/ImageTest.php
Vision/tests/Unit/VisionHelpersTraitTest.php

Use dedicated PHPUnit assertions

---

Bigtable/src/DataClient.php
Bigtable/src/DataUtil.php
Bigtable/src/ReadModifyWriteRowRules.php
Bigtable/tests/Snippet/DataClientTest.php
Bigtable/tests/System/DataClientReadModifyWriteRowTest.php
Bigtable/tests/Unit/DataClientTest.php
Bigtable/tests/Unit/DataUtilTest.php
Bigtable/tests/Unit/ReadModifyWriteRowRulesTest.php

Bigtable: Read modify write row model

---

Bigtable/src/DataClient.php
Bigtable/tests/Snippet/DataClientTest.php
Bigtable/tests/System/DataClientSampleRowKeysTest.php
Bigtable/tests/Unit/DataClientTest.php

Bigtable: Sample row keys api

---

Firestore/src/DocumentSnapshot.php
Firestore/tests/System/ValueMapperTest.php

The fix in #1377 exposed another issue, that `DocumentSnapshot::offsetExists()` uses an `isset()` check, which [according to the documentation](http://php.net/isset), returns `false` if the tested value is set to `null`. As `null` is a valid value, the `offsetExists()` test has been updated to use `array_key_exists()`.

Fix Firestore array offset exists check

---

Bigtable/src/BigtableClient.php
Bigtable/src/ChunkFormatter.php
Bigtable/src/Filter.php
Bigtable/src/ReadModifyWriteRowRules.php
Bigtable/src/Table.php
Bigtable/tests/Snippet/BigtableClientTest.php
Bigtable/tests/Snippet/ChunkFormatterTest.php
Bigtable/tests/Snippet/FilterTest.php
Bigtable/tests/Snippet/TableTest.php
Bigtable/tests/System/BigtableTestCase.php
Bigtable/tests/System/CheckAndMutateRowTest.php
Bigtable/tests/System/FilterTest.php
Bigtable/tests/System/MutateRowsTest.php
Bigtable/tests/System/ReadModifyWriteRowTest.php
Bigtable/tests/System/ReadRowsTest.php
Bigtable/tests/System/SampleRowKeysTest.php
Bigtable/tests/Unit/BigtableClientTest.php
Bigtable/tests/Unit/TableTest.php

@ajaaym I was having trouble verifying the system tests due to quota limits on my account. Would you be able to confirm the changes I made still pass?

Rename DataClient -> Table and add BigtableClient

---

Bigtable/README.md
Bigtable/src/BigtableClient.php

The README updates intend to help clarify the differences we are introducing by updating our client constructor options to more closely match the generated clients.
The `ClientTrait` is intended to be used with our "older" style of handwritten clients. We'll need to do a little refactoring to get back to the same functionality. We can follow up with this work shortly.

Update readme/projectID detection

---

Bigtable/src/DataUtil.php
Bigtable/tests/Unit/DataUtilTest.php

Since the DataUtil methods in Bigtable require a 64-bit build of PHP 5.6 or greater, this change adds a check to verify that the PHP version supports 64-bit ints and skips tests if it does not. This should fix the build failure in the other PR.
@ajaaym @dwsupplee

Add 64 or 32 bit test

---

Core/src/Report/GAEMetadataProvider.php
Core/src/Report/GAEStandardMetadataProvider.php
Core/src/Report/MetadataProviderUtils.php
Core/tests/Unit/Report/GAEStandardMetadataProviderTest.php
Core/tests/Unit/Report/MetadataProviderUtilsTest.php

Support log correlation on App Engine standard 2nd gen

---

Storage/src/StorageObject.php
Storage/tests/Unit/StorageObjectTest.php

When getting a signed URL from a storage object and passing the cname option the resource path should not include the bucket name, as that's implied by the cname.
This removes the bucket name from the resource path if a cname option is provided.

storage: use correct path with signed url cname

---

dev/src/ReleaseBuilder/ReleaseBuilder.php

If a commit message is missing the Pull Request reference, the release builder chokes. This is a fairly unlikely circumstances, but it's perfectly possible, so this change will prompt the user to provide the missing information.
(For whoever tags the next release, the missing PR reference is #1449. ;) )

Handle malformed PR/commit messages

---

Bigtable/composer.json

when using the [google/cloud-bigtable](https://packagist.org/packages/google/cloud-bigtable) package with composer version `1.8.0` i am unable to construct the client successfully without installing a package under the [`"require-dev"`](https://github.com/googleapis/google-cloud-php-bigtable/blob/2cbfb55f928a17d1a86d05564033c15da280f7ac/composer.json#L9-L11) key
```shell session
$ cat test.php
<?php
require __DIR__ . '/vendor/autoload.php';
use Google\Cloud\Bigtable\BigtableClient;
$bigtable = new BigtableClient(['projectId' => 'my-project']);
$ php ./test.php
Fatal error: Trait 'Google\Cloud\Core\ArrayTrait' not found in /home/mstarr/nextgenaz/vendor/google/cloud-bigtable/src/BigtableClient.php on line 41
$ php -d extension=phar.so composer.phar require google/cloud-core:1.23
$ php …
```

move google/cloud-core package from a development dependency to a production dependency in google/cloud-bigtable package

---

Storage/src/Bucket.php
Storage/src/StorageClient.php
Storage/tests/Snippet/BucketTest.php

This illustrates how one may programmatically update the permissions on the topic they would like to have receive notifications.
Closes: https://github.com/googleapis/google-cloud-php/issues/1079

Update storage bucket notification sample

---

Core/composer.json
Core/src/ExponentialBackoff.php
Core/src/RequestWrapper.php
Core/src/RequestWrapperTrait.php
Core/src/ServiceBuilder.php
Core/tests/Unit/ExponentialBackoffTest.php
Core/tests/Unit/RequestWrapperTest.php
Storage/composer.json
Storage/src/Connection/Rest.php
Storage/src/StorageObject.php
Storage/tests/Snippet/StorageObjectTest.php
Storage/tests/System/ManageObjectsTest.php
Storage/tests/Unit/Connection/RestTest.php
Storage/tests/Unit/StorageObjectTest.php

With this changeset users can now download objects asynchronously by utilizing [Guzzle Promises](https://github.com/guzzle/promises).
```php
use Google\Cloud\Storage\StorageClient;
use GuzzleHttp\Promise;
use Psr\Http\Message\StreamInterface;
$storage = new StorageClient;
$bucket->storage('my-bucket');
$promises = [];
foreach ($bucket->objects() as $object) {
$promises[] = $object->downloadAsStreamAsync()
->then(function (StreamInterface $data) {
echo $data->getContents();
});
}
Promise\unwrap($promises);
```

Storage async object downloads

---

dev/src/DocGenerator/Parser/CodeParser.php
dev/src/ReleaseBuilder/ReleaseBuilder.php
docs/external-classes.json

This change updates the external type transformer to use the installed dependency version in the URIs.
Some examples:
* http://jdpedrie.github.io/google-cloud-php/#/docs/google-cloud/master/asset/v1beta1/assetserviceclient?method=resumeOperation
* http://jdpedrie.github.io/google-cloud-php/#/docs/google-cloud/master/bigquery/bigqueryclient?method=__construct
* config['authCache']
* config['credentialsFetcher']
Closes #757.

Link to installed dependency version in generated docs

---

Trace/README.md

The Trace README has fallen out of date and contained some errors. This change provides up-to-date installation information and fixes the errors.

Update Trace README

---

dev/src/ComponentIntegration/Command/ComponentIntegration.php

This should fix the kokoro continuous error.
If a component is missing a test folder (`tests/Unit` or `tests/Snippet`), the commands for running those tests will be omitted.
If a component contains a test folder (`tests/Unit` or `tests/Snippet`), but is missing the PHPUnit configuration (`phpunit.xml.dist` or `phpunit-snippets.xml.dist` respectively), the test will fail.
If the configuration file exists but no test folder exists (as is the case for several gapic-only components), the test will proceed without error.

Component integration: Skip tests if folder does not exist

---

Trace/README.md

the sample code in Trace/README.md is incorrectly.
it should be 
`setStartTime` and `setEndTime`
also check:
https://github.com/googleapis/google-cloud-php/blob/master/Trace/src/Span.php#L215
https://github.com/googleapis/google-cloud-php/blob/master/Trace/src/Span.php#L253

Fix incorrect sample code in Trace/README.md

---

Datastore/src/Connection/Grpc.php

Addresses #1599.
This does not fix the underlying issue within protobuf, but it should allow use of the protobuf extension with Google Cloud PHP Datastore in the meanwhile.
@jhaboush would you mind giving this a try?

Rework keysList method to solve protobuf extension error

---

dev/src/QuestionTrait.php
dev/src/ReleaseBuilder/ReleaseBuilder.php

This change eliminates a question in the workflow for modifying the commit message or release type of a commit. It also allows changes to the message and release type to be applied to all components affected by a commit.

Improve modify message and release type flow

---

Storage/tests/System/ManageNotificationsTest.php
Storage/tests/System/RequesterPaysTest.php

The `{projectId}@gs-project-accounts.iam.gserviceaccount.com` format has been deprecated, utilizing the `getServiceAccount` request will make sure we are always using the correct format.

Use the new(er) getServiceAccount method instead of hard coding the storage service account

---

Bigtable/src/Table.php
Bigtable/tests/Unit/TableTest.php

previously `readRow` passed two arguments to `readRows` which accepts one argument preventing the ability to use filters with `readRow`

add ability to use filters with #readRow()

---

Firestore/src/CollectionReference.php
Firestore/src/Connection/ConnectionInterface.php
Firestore/src/Connection/Grpc.php
Firestore/tests/Snippet/CollectionReferenceTest.php
Firestore/tests/System/DocumentAndCollectionTest.php
Firestore/tests/Unit/CollectionReferenceTest.php
Firestore/tests/Unit/Connection/GrpcTest.php

Adds `CollectionReference::listDocuments()` and implements the `ListDocuments` RPC.

Firestore list documents

---

Spanner/src/Result.php
Spanner/tests/Unit/ResultTest.php

Towards: https://github.com/googleapis/google-cloud-php/issues/1717

Handle error/exception types outside of ServiceExceptions more gracefully

---

Firestore/src/FieldValue.php
Firestore/src/FieldValue/ArrayRemoveValue.php
Firestore/src/FieldValue/ArrayUnionValue.php
Firestore/src/FieldValue/DeleteFieldValue.php
Firestore/src/FieldValue/DocumentTransformInterface.php
Firestore/src/FieldValue/DocumentTransformTrait.php
Firestore/src/FieldValue/IncrementValue.php
Firestore/src/FieldValue/ServerTimestampValue.php
Firestore/src/WriteBatch.php
Firestore/tests/Snippet/FieldValueTest.php
Firestore/tests/System/FieldValueTest.php
Firestore/tests/Unit/FieldValueTest.php
Firestore/tests/Unit/WriteBatchTest.php

This pull request adds support for the increment DocumentTransform.
```php
use Google\Cloud\Firestore\FieldValue;
$document->update([
['path' => 'loginCount', 'value' => FieldValue::increment(1)]
]);
```

Add Firestore FieldValue::increment().

---

Core/src/ClientTrait.php
Core/tests/Unit/ClientTraitTest.php
PubSub/tests/Snippet/PubSubClientTest.php

Since the emulator is always used when the *_EMULATOR_HOST environment
variable is set, there should not be any case where the ADC credentials
are needed.
Using the ADC credentials may cause confusion when they are set on the
CLI but not in the webserver, leading to different projectIds for the
same code.
Also see https://github.com/googleapis/google-cloud-php/issues/1739

Prefer emulator project when pub/sub emulator is detected

---

Vision/src/Annotation.php
Vision/src/Annotation/AbstractFeature.php
Vision/src/Annotation/CropHint.php
Vision/src/Annotation/Document.php
Vision/src/Annotation/Entity.php
Vision/src/Annotation/Face.php
Vision/src/Annotation/Face/Landmarks.php
Vision/src/Annotation/FeatureInterface.php
Vision/src/Annotation/ImageProperties.php
Vision/src/Annotation/LikelihoodTrait.php
Vision/src/Annotation/SafeSearch.php
Vision/src/Annotation/Web.php
Vision/src/Annotation/Web/WebEntity.php
Vision/src/Annotation/Web/WebImage.php
Vision/src/Annotation/Web/WebPage.php
Vision/src/Connection/Rest.php
Vision/src/Image.php
Vision/src/VisionClient.php

* Marks handwritten vision classes as deprecated
* Adds runtime notices for constructed classes with custom error handlers
* VisionClient references ImageAnnotatorClience for new usage.

Marks Vision classes as deprecated in favor of gapic

---

BigQuery/src/BigQueryClient.php
Core/src/ExponentialBackoff.php
Core/src/Logger/AppEngineFlexFormatter.php
Core/src/RequestWrapper.php
Core/src/RetryDeciderTrait.php
Core/tests/Unit/ExponentialBackoffTest.php
Core/tests/Unit/RequestWrapperTest.php
Core/tests/Unit/RetryDeciderTraitTest.php
Language/src/LanguageClient.php
Storage/src/Connection/Rest.php

Closes: https://github.com/googleapis/google-cloud-php/issues/1813, https://github.com/googleapis/google-cloud-php/issues/1809
Big thanks to @paslandau for the reports! The `BigQueryClient` was incorrectly using the `restDelayFunction` to attempt to override the exponential delay calculation. This exposes a new option (`restCalcDelayFunction`) which allows this behavior to work as expected. Additionally, this addresses an issue when attempting to retry error messages sourced from guzzle exceptions.

Retry fixes

---

Core/src/Batch/BatchTrait.php

Closes: https://github.com/googleapis/google-cloud-php/issues/1741
We can prevent errors regarding the lack of the `STDERR` constant outside of CLI context when creating a resource manually through `fopen('php://stderr', 'w')`.

Avoid usage of STDERR constant

---

Storage/src/Bucket.php
Storage/src/StorageClient.php

This change updates the documentation on methods which create and modify buckets, adding as [requested](https://docs.google.com/document/d/1s8D8hJyuUFafYhnVM40HG2EmsjuQJRAqzjN0M21_TDI/edit?ts=5cb61781) links to the Bucket Policy Only documentation on cloud.google.com.
cc @frankyn

Add links to Bucket Policy Only documentation

---

Datastore/src/Operation.php
Datastore/src/Query/GqlQuery.php
Datastore/tests/Snippet/DatastoreClientTest.php
Datastore/tests/Snippet/ReadOnlyTransactionTest.php
Datastore/tests/Snippet/TransactionTest.php
Datastore/tests/System/DatastoreTestCase.php
Datastore/tests/System/QueryResultPaginationTest.php
Datastore/tests/Unit/OperationTest.php
Datastore/tests/Unit/Query/GqlQueryTest.php
Datastore/tests/Unit/fixtures/query-results.json

Fixes #1696.
This change adds support for automatic pagination with GQL queries.
Since GQL query positions are determined by query string binding values (i.e. `offset` and `limit`), programmatically paging is difficult using GQL. However, the server returns the computed value of the query in the first result batch when a GQL query is executed.
By dispatching subsequent requests using the computed query and discarding the GQL query, we can page through results in the same manner as with a query object.

Automatically paginate GQL Queries

---

Spanner/src/Database.php
Spanner/src/TransactionConfigurationTrait.php
Spanner/tests/Unit/DatabaseTest.php

`Database::execute()` runs operations within a single-use transaction, but due to the order in which the transaction was configured, single-use configuration options (`maxStaleness` and `minReadTimestamp`) were not available to that method.
Fixes #1830.

Fix transaction configuration for single-use transactions

---

Storage/tests/Unit/SigningHelperTest.php

Following #1829 and #1843. The previous attempt at fixing this didn't do the trick. This change manually sets the URL signing method timestamp to match the expected timestamp, eliminating the possibility of failures based on when the test is executed.

Fix flaky test

---

Spanner/src/Connection/Grpc.php

Fixes #1851 by only instantiating the Instance and Database admin clients when they are first used. The data client is still created upfront as it's the only one used in the course of the common usage.

Lazily instantiate admin and operations clients

---

ErrorReporting/README.md
README.md

Fixes #1737.
Sample is based on [`php-docs-samples` quickstart](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/83cbbeb2ee36a458db4d2dc868cd8e16812fa957/error_reporting/quickstart.php).

Add samples for using Bootstrap class

---

Firestore/tests/System/Admin/V1/FirestoreAdminClientSmokeTest.php

This should resolve the [CI failure](https://source.cloud.google.com/results/invocations/a48b8069-89bf-451c-b1d4-1d97d58af904/targets/github%2Fgoogle-cloud-php%2Fphp72%2Fsystem/tests), the project ID associated with the firestore enabled service account differs from the one in the environment variable `PROJECT_ID`.

Use correct projectId

---

Datastore/src/Connection/Grpc.php
Datastore/tests/System/QueryResultPaginationTest.php
Datastore/tests/Unit/Connection/GrpcTest.php

Hopes to address the system test failures by using a query that has strong consistency.
Also uncovered a bug related to property filters in queries, the fix for which is included in this change.

Fix pagination bug with filters and test flakiness

---

dev/src/ReleaseBuilder/ReleaseBuilder.php

Skipping a commit will omit it entirely from the release.

Skip commit in release builder

---

Firestore/src/Connection/Grpc.php
Firestore/src/FieldPath.php
Firestore/src/FirestoreClient.php
Firestore/src/Query.php
Firestore/src/SnapshotTrait.php
Firestore/tests/Snippet/CollectionReferenceTest.php
Firestore/tests/Snippet/FieldPathTest.php
Firestore/tests/Snippet/FirestoreClientTest.php
Firestore/tests/Snippet/QueryTest.php
Firestore/tests/System/CollectionGroupTest.php
Firestore/tests/System/FirestoreTestCase.php
Firestore/tests/Unit/CollectionReferenceTest.php
Firestore/tests/Unit/FieldPathTest.php
Firestore/tests/Unit/FirestoreClientTest.php
Firestore/tests/Unit/QueryTest.php

Adds support for Collection Group Queries to Cloud Firestore.
Also fixes a couple other issues:
* Add support for documents as strings in `where()` when the FieldPath is `__name__`. ([precedent](https://github.com/googleapis/nodejs-firestore/pull/136))
* Added `FieldPath::documentId()` to conform with other language APIs and better surface the available functionality.
* Removed the special character workaround added in #1122, as the GAPIC parser now has improved support. (https://github.com/googleapis/gax-php/issues/197)
cc @schmidt-sebastian @crwilcox

Add Collection Group Query support

---

Debugger/src/Agent.php

Fixes error in PHP 7.3:
```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /path/to/google-cloud-php/Debugger/src/Agent.php on line 210
```

Fix continue switch targeting warning in PHP 7.3

---

Language/tests/System/AnalyzeTest.php

This change fixes a persistent failure in the language system tests by allowing for some fluctuation in the returned value of entity sentiments.

Fix language system test

---

dev/src/DocGenerator/Parser/CodeParser.php

Fixes #1970.
Our external types link to various different sources. GitHub code, PHPDoc generated pages, etc. We can't predict an anchor type for each of these, so to fix the 404 errors, strip method names from the type reference.

Strip method reference in external type link

---

Core/composer.json
Core/src/ArrayTrait.php
Core/src/Batch/BatchRunner.php
Core/src/Batch/InterruptTrait.php
Core/src/Batch/JobTrait.php
Core/src/Batch/SimpleJob.php
Core/src/Compute/Metadata.php
Core/src/DebugInfoTrait.php
Core/src/GrpcRequestWrapper.php
Core/src/Iterator/ItemIteratorTrait.php
Core/src/PhpArray.php
Core/src/RequestWrapper.php
Core/src/RequestWrapperTrait.php
Core/src/Retry.php
Core/src/ServiceBuilder.php
Core/src/Testing/ArrayHasSameValuesToken.php
Core/src/Testing/Snippet/Coverage/Coverage.php
Core/src/Testing/Snippet/Coverage/ScannerInterface.php
Core/src/Testing/Snippet/Parser/InvokeResult.php
Core/src/Testing/Snippet/Parser/Parser.php
Core/src/TimeTrait.php
Core/src/Upload/ResumableUploader.php
Core/src/Upload/SignedUrlUploader.php
Core/tests/Unit/ArrayTraitTest.php
Core/tests/Unit/BlobTest.php
Core/tests/Unit/GrpcRequestWrapperTest.php

This change fixes minor errors or mistakes and does a bit of cleanup across Core. The only thing which may be controversial was my removal of support for the old `Google\GAX` classes from `GrpcRequestWrapper`. My reasoning is that, as we require gax v1.0, it is not possible to install a version of GAX which uses the old class names. If there is disagreement w.r.t. this, I can revert that part.

Cleanup minor issues in Core

---

BigQuery/src/BigQueryClient.php
BigQuery/src/QueryResults.php
BigQuery/tests/Unit/QueryResultsTest.php

Adds an option to return raw results from BigQuery

---

Redis/README.md

There is a typo in the PHP sample code in the Redis README file.
A variable (`$device`) is misnamed in the example. It should be `$instance`. Running the example as is will gives the following error(s):
```
PHP Notice:  Undefined variable: device
PHP Fatal error:  Uncaught Error: Call to a member function getDisplayName() on null
```
This PR corrects that typo.

Fix typo in Redis sample code

---

Firestore/src/Connection/Grpc.php
Firestore/src/PathTrait.php
Firestore/src/Query.php
Firestore/src/QuerySnapshot.php
Firestore/src/SnapshotTrait.php
Firestore/src/WriteBatch.php

Fixed some minor mistakes and one potential bug where user-provided options were not passed to a write as expected.

fix: Firestore cleanup and fixes

---

dev/src/AddComponent/Command/AddComponent.php
dev/src/AddComponent/Composer.php
dev/src/AddComponent/TestConfig.php
dev/src/AddComponent/templates/template-phpunit-snippets.xml.dist.txt
dev/src/AddComponent/templates/template-phpunit-system.xml.dist.txt
dev/src/AddComponent/templates/template-phpunit.xml.dist.txt

`dev/google-cloud component` now adds PHPUnit configuration files and namespaces for the component, component tests, and metadata to the main composer.json file.

fix: Add namespaces and test configs in component tool

---

Core/src/Compute/Metadata.php
Core/src/Compute/Metadata/Readers/HttpHandlerReader.php
Core/src/Compute/Metadata/Readers/StreamReader.php
Core/tests/Unit/Compute/Metadata/Readers/HttpHandlerReaderTest.php
Core/tests/Unit/Compute/Metadata/Readers/StreamReaderTest.php
Core/tests/Unit/Compute/MetadataTest.php

feat(core): Update Compute Metadata Reader

---

BigQueryDataTransfer/tests/System/V1/DataTransferServiceSmokeTest.php

The test file says it's generated, but it wasn't updated to take into account recent changes. This fixes the failing system test.

fix: Fix BigQueryDataTransfer smoke test

---

.kokoro/continuous/node10/release.sh
.kokoro/continuous/node10/test.cfg

Adds a script which runs when commits are merged and:
1. keeps a release PR (see: https://github.com/googleapis/google-cloud-php/pull/2055) up to date.
2. if it sees a merged release-pr, it uses the GitHub API to create a new GitHub release tag.

build: add release-please bin to CI

---

VideoIntelligence/src/V1/resources/video_intelligence_service_rest_client_config.php

Towards: https://github.com/googleapis/google-cloud-php/issues/2064
This is only a temporary solution. We are waiting on updates to land in https://github.com/googleapis/googleapis/tree/master/google/cloud/videointelligence/v1, at which point synthtool will take over.
/cc @bshaffer

fix: Use updated URIs for operations

---

Core/src/Upload/MultipartUploader.php
Core/tests/Unit/Upload/MultipartUploaderTest.php

PSR-7 allows a stream to indicate its size is unknown by returning null. This is really useful if the stream is being transformed as it's uploaded, for example.
Currently, the `MultiPartUploader` always adds a `Content-Length` header, even if the `Stream` returns null. Adding this invalid null value triggers a chain of assumptions in Guzzle and other API code that tries to resolve the size in ways that can cause unwanted side effects like trying to load the entire stream into memory, etc.
However, by detecting if the size is known or not, we can avoid all the issues and everything works great.
I haven't updated the other Uploader classes because the size does seem very relevant for their usecases (and also because I'm not using them :sweat_smile:)

Skip Content-Length if stream size is unknown

---

Storage/tests/System/SignedUrlTest.php

This operation is not necessary and may be responsible for kokoro test failures.

fix: Remove unset content type in system test

---

Datastore/README.md

App Engine users will experience extremely poor datastore performance if they use this component in the PHP 5 runtime. I presume there are a large number of developers using this component with their App Engine project, so I added a section that highlights how developers can avoid this pitfall. 
Background context on poor datastore performance in PHP 5: https://github.com/googleapis/google-cloud-php/issues/1937

Added suggested App Engine config to docs

---

BigQuery/src/Connection/ConnectionInterface.php
BigQuery/src/Connection/Rest.php
BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/src/Dataset.php
BigQuery/src/Model.php
BigQuery/tests/Snippet/DatasetTest.php
BigQuery/tests/Snippet/ModelTest.php
BigQuery/tests/System/ManageModelsTest.php
BigQuery/tests/Unit/Connection/RestTest.php
BigQuery/tests/Unit/DatasetTest.php
BigQuery/tests/Unit/ModelTest.php

* Updated discovery doc for bigquery
* Created model class
* Added model and models methods to BigQuery client
* Added network calls to ConnectionInterface and Rest connection

feat: Add support for BigQuery Models.

---

Core/src/Upload/ResumableUploader.php
Storage/composer.json
Storage/src/Bucket.php
Storage/src/Connection/Rest.php
Storage/tests/System/UploadObjectsTest.php
Storage/tests/Unit/Connection/RestTest.php
composer.json

This cannot be merged until [`google/crc32`](https://github.com/google/php-crc32) has a stable release.
cc @frankyn.

feat(storage): Add CRC32 Checksums to Cloud Storage uploads.

---

BigQuery/src/BigQueryClient.php
BigQuery/tests/System/ManageDatasetsTest.php

Closes #2118.
Adds documentation explaining existing support for filtering datasets via `BigQueryClient::datasets()` and a system test to exercise the functionality.

feat: Add explicit support for dataset filters

---

BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
BigQueryDataTransfer/synth.metadata
BigQueryDataTransfer/tests/System/V1/DataTransferServiceSmokeTest.php

Replaces #2052.
The upstream issue was fixed and the smoke test is now passing.

fix: Add locationName formatting method and update system test

---

ErrorReporting/src/Bootstrap.php

Removes use of  `STDERR` const, which is defined by [CLI SAPI](https://php.net/manual/en/features.commandline.io-streams.php) and so isn't available when PHP is executed through a web server

Removes STDERR const, which is defined by CLI SAPI

---

Core/src/ExponentialBackoff.php
Firestore/src/WriteBatch.php

Closes: https://github.com/googleapis/google-cloud-php/issues/2128
A snippet to replicate the issue:
```php
use Google\Cloud\Firestore\FirestoreClient;
$client = new FirestoreClient();
while (true) {
$collection = $client->collection('my-collection');
$document = $collection->document(uniqid('doc-'));
$document->set([
'one' => 1,
'two' => 2,
'three' => 3
]);
usleep(100000);
echo memory_get_usage() . PHP_EOL;
}
```

fix: Address Firestore memory leak (affects long running processes)

---

Core/src/RequestWrapper.php
Storage/src/Connection/ConnectionInterface.php
Storage/src/Connection/Rest.php
Storage/src/Connection/ServiceDefinition/storage-v1.json
Storage/src/CreatedHmacKey.php
Storage/src/HmacKey.php
Storage/src/StorageClient.php
Storage/tests/Snippet/CreatedHmacKeyTest.php
Storage/tests/Snippet/HmacKeyTest.php
Storage/tests/Snippet/StorageClientTest.php
Storage/tests/System/HmacKeyTest.php
Storage/tests/Unit/Connection/RestTest.php
Storage/tests/Unit/CreatedHmacKeyTest.php
Storage/tests/Unit/HmacKeyTest.php
Storage/tests/Unit/StorageClientTest.php

Closes #1868.
This change adds support for service account HMAC keys.
The change adds a new `Google\Cloud\Storage\HmacKey` class, which represents a single HMAC key. It also adds list, create and instantiate methods for HMAC keys to `Google\Cloud\Storage\StorageClient`.

feat(storage): Add support for service account HMAC keys

---

Firestore/src/Connection/Grpc.php
Firestore/tests/Unit/Connection/GrpcTest.php

Fixes #2197 by adding a dummy Authorization header to firestore requests when the emulator is enabled (as discussed [here](https://github.com/firebase/firebase-tools/issues/1363#issuecomment-498364771) and [here](https://github.com/googleapis/nodejs-firestore/pull/654)). Also allows custom headers to be passed to grpc calls in the Firestore client.

Fix: Provide headers required for Firestore emulator.

---

BigQuery/composer.json
Translate/composer.json

Changes to the RequestBuilder constructor are required for BigQuery and Translate to function properly. Once I implement `apiEndpoint` in Storage, it'll be needed there too, but I'll do that with the storage PR.

fix: Bump core dependency for BigQuery and Translate

---

Debugger/src/Debuggee.php
Debugger/tests/Unit/DebuggeeTest.php

fix: Prevent setting null debuggee ID

---

Core/src/Logger/AppEngineFlexFormatterV2.php
Core/src/Logger/AppEngineFlexHandler.php
Core/src/Logger/AppEngineFlexHandlerFactory.php
Core/src/Logger/AppEngineFlexHandlerV2.php
Core/src/Logger/FormatterTrait.php
Core/src/Testing/Snippet/Coverage/Coverage.php
Core/tests/Unit/Logger/AppEngineFlexHandlerFactoryTest.php
Core/tests/Unit/Logger/AppEngineFlexHandlerTest.php
composer.json
dev/src/DocGenerator/Parser/ClassReference.php
dev/src/DocGenerator/Parser/CodeParser.php

Hey everyone 👋
This is a follow up to #2293 and aims to add support for both monolog/monolog 1.x and 2.x.
Monolog 2.x was released on August 30th, 2019 and requires PHP ^7.2 whereas google/cloud keeps supporting PHP 5.6.
The specific issue is that Monolog 2.x adds method return types which are not supported by PHP 5.x. On the other hand, leaving the return type declarations out causes PHP 7.x to throw errors.
`AppEngineFlexHandler` and `AppEngineFlexFormatter` remain the implementation for Monolog 1.x.
`AppEngineFlexV2Handler` and `AppEngineFlexV2Formatter` are the new implementations for Monolog 2.x.
The new classes are the same as the old ones with the only difference being added return type declarations.
* I thought about extracting the common code instead of duplicating it, but I …

Add support for Monolog 2.x

---

.kokoro/continuous/node10/release.sh

ref: https://github.com/googleapis/release-please/issues/259
Prefer minor version bumps on pre-GA packages.

chore: Use minor version bump before GA

---

BigQuery/src/LoadJobConfiguration.php

This corrects a minor issue in the BigQuery `LoadJobConfiguration` where `useAvroLogicalTypes` isn't adhering to the documented return type.

Fix incorrect return value in LoadJobConfiguration

---

BigQuery/src/ExtractJobConfiguration.php
BigQuery/tests/Unit/CopyJobConfigurationTest.php
BigQuery/tests/Unit/ExtractJobConfigurationTest.php
BigQuery/tests/Unit/LoadJobConfigurationTest.php
BigQuery/tests/Unit/QueryJobConfigurationTest.php

Counterpart to #2327 and an extra assertion in the job configuration tests to make sure the last setter (the most likely to be newly added) returns as expected.

fix: Fix fluent setter in ExtractJobConfiguration

---

Core/composer.json
PubSub/src/Subscription.php
PubSub/tests/Snippet/SubscriptionTest.php
composer.json

Tests will not pass until https://github.com/googleapis/google-auth-library-php/pull/243 is merged and released.

feat: Add support for Authenticated Push

---

Firestore/src/FirestoreClient.php
Firestore/src/FirestoreSessionHandler.php
Firestore/tests/System/FirestoreSessionHandlerTest.php
Firestore/tests/Unit/FirestoreSessionHandlerTest.php

There are still a few issues:
- `session_gc` returns `false`, even though the records get deleted as expected. I do not know why.
- The `FirestoreTestCase` function to delete `$deletionQueue` does not get registered. This is because the call do do this, which is in `bootstrap.php`, does not exist in `system-bootstrap.php`.
- Even when the deletion function is registered, the collections registered to be deleted in these tests are not deleted. I suspect it has something to do with them running in separate processes but I can't figure it out.

Updates to FirestoreSessionHandler

---

Core/src/Testing/System/EncryptionManagement.php
Core/src/Testing/System/KeyManager.php

Since CMEK is propagating out in API implementations, it makes sense to abstract the testing utilities so they can be reused in various test suites.

feat: Extract KMS testing utilities

---

Core/src/Batch/HandleFailureTrait.php

When multiple processes try to create a directory at the same time `mkdir` is going to fail and return false. This should not warrant an exception.
This change ensures the directory exists - and only throws when it does not.

Only throw exception when creating directory really failed in HandleFailureTrait

---

Firestore/src/Query.php
Firestore/tests/Unit/QueryTest.php

This change allows better forward-compatibility with any future query operators added to the service, and adds documentation and short operator aliases for the recently added query comparison operators.

feat: Support any new query field filter operators

---

.kokoro/presubmit/run-tests.sh

solves the build failures whenever codecov is enabled.

chore: disable codecov

---

Container/synth.py

Fixes many occurrences of broken URLs, e.g.:
```diff
-      * [here](/compute/docs/gpus)
+      * [here](https://cloud.google.com/compute/docs/gpus)
```

chore: update synth config to fix container documentation links

---

Storage/src/Bucket.php
Storage/src/Lifecycle.php
Storage/src/StorageClient.php
Storage/tests/System/ManageBucketsTest.php

Closes #2425
cc @tritone for review.

feat: add support for ARCHIVE storage class

---

Spanner/src/Connection/Grpc.php
Spanner/src/Instance.php
Spanner/tests/System/AdminTest.php
Spanner/tests/Unit/Connection/GrpcTest.php
Spanner/tests/Unit/InstanceTest.php

Enabling `FieldMask` param in the `getInstance` call.
[Link](https://github.com/googleapis/googleapis/blob/master/google/spanner/admin/instance/v1/spanner_instance_admin.proto#L472) to proto

feat: enable 'FieldMask' param in Instance::reload() method options

---

Storage/src/StreamWrapper.php
Storage/tests/System/StreamWrapper/DirectoryTest.php
Storage/tests/System/StreamWrapper/StreamWrapperTestCase.php
Storage/tests/Unit/StreamWrapperTest.php

fix: allow mkdir() via stream wrapper when UBL is enabled

---

Spanner/src/Connection/Grpc.php

Update spanner lroResponseMappers to comply with changes in `Core` in PR #2536 
This PR should wait for #2536 to merge in order to update `google/cloud-core` dependency version.

refactor: update spanner lroResponseMappers to map types for `metadata` and `response` separately

---

Spanner/src/Connection/Grpc.php

Accidentally merged.
Need #2536 to be merged first.

revert: revert "refactor: update spanner lroResponseMappers to map types for `metadata` and `response` separately"

---

PubSub/src/BatchPublisher.php
PubSub/src/Connection/Grpc.php
PubSub/src/Message.php
PubSub/src/MessageBuilder.php
PubSub/src/PubSubClient.php
PubSub/src/Subscription.php
PubSub/src/Topic.php
PubSub/tests/Snippet/MessageBuilderTest.php
PubSub/tests/Snippet/MessageTest.php
PubSub/tests/System/ManageIAMPoliciesTest.php
PubSub/tests/System/ManageSubscriptionsTest.php
PubSub/tests/System/ManageTopicsTest.php
PubSub/tests/System/PubSubTestCase.php
PubSub/tests/System/PublishAndPullTest.php
PubSub/tests/Unit/BatchPublisherTest.php
PubSub/tests/Unit/MessageBuilderTest.php
PubSub/tests/Unit/MessageTest.php

replaces #2419. This PR demonstrates using a single batch job for multiple ordering keys RPCs in order to prevent crashes from exhausted shared memory.
Opening as a separate PR so that the changes may be compared.

feat: add support for ordering keys

---

ErrorReporting/synth.py

fixes renamed formatting method.

chore: fix breaking change in errorreporting gapic

---

Spanner/src/Database.php
Spanner/src/Instance.php
Spanner/tests/Unit/InstanceTest.php

feat: inject database info on list databases

---

Core/src/Testing/TestHelpers.php

We have `StubTrait::___getProperty()`, but it only works for classes which we create. This allows us to grab private properties from any object for testing, and is used by #2532.

feat: add getPrivateProperty test helper

---

Storage/tests/System/IamTest.php

Fixes, well... some of the broken system tests. will keep working on the rest as i have capacity (container and translate).

test: fix broken system test

---

Spanner/README.md

`maxSessions` and `minSessions` should be correct.
http://googleapis.github.io/google-cloud-php/#/docs/cloud-spanner/v1.24.0/spanner/session/cachesessionpool

docs: fix typo for CacheSessionPool config

---

Spanner/src/Connection/Grpc.php
Spanner/src/SpannerClient.php
Spanner/tests/Snippet/SpannerClientTest.php

Add support for emulators.
To use an emulator, set the environment variable to the host:port of the emulator:
e.g. `$ export SPANNER_EMULATOR_HOST=localhost:9010`
Avoid using http schemes in the emulator host as it can cause the gRPC DNS resolver to endlessly attempt to resolve.

feat(spanner): add emulator support

---

Spanner/tests/Unit/DatabaseTest.php

replace Argument::any() mocks with more restrictive Argument::allOf() and Argument::withEntry()

refactor(spanner): stronger assertions for Unit/DatabaseTest

---

Spanner/tests/Unit/Batch/BatchClientTest.php
Spanner/tests/Unit/InstanceConfigurationTest.php
Spanner/tests/Unit/InstanceTest.php
Spanner/tests/Unit/OperationTest.php
Spanner/tests/Unit/SpannerClientTest.php
Spanner/tests/Unit/TransactionTest.php
Spanner/tests/Unit/TransactionTypeTest.php

replace Argument::any() tokens with Argument::allOf() and Argument::withEntry()

refactor(spanner): stronger assertions for unit tests

---

Debugger/src/BreakpointStorage/FileBreakpointStorage.php

Closes: https://github.com/googleapis/google-cloud-php/issues/2068

fix: remove redundant extension from lock file name

---

BigQuery/src/BigQueryClient.php
BigQuery/src/Connection/ConnectionInterface.php
BigQuery/src/Connection/Rest.php
BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
BigQuery/src/Dataset.php
BigQuery/src/Routine.php
BigQuery/tests/Snippet/DatasetTest.php
BigQuery/tests/Snippet/RoutineTest.php
BigQuery/tests/System/ManageRoutinesTest.php
BigQuery/tests/Unit/BigQueryClientTest.php
BigQuery/tests/Unit/Connection/RestTest.php
BigQuery/tests/Unit/DatasetTest.php
BigQuery/tests/Unit/QueryResultsTest.php
BigQuery/tests/Unit/RoutineTest.php
BigQuery/tests/Unit/TableTest.php
Core/src/Testing/TestHelpers.php

~~This is ready except for handling partial updates.~~
~~@shollyman @tswast can you give any insight into how partial updates will be handled by the server? I'd really like to implement this in a way that will be forward-compatible for our users once the API is updated. Will it use a PATCH method? An Update Mask? If the latter, I can handle that on the client side now in a manner compatible with the existing field masks, then remove that code once the server accepts it.~~
Ready for review.

feat: add support for BigQuery routines

---

Storage/src/Bucket.php
Storage/src/SigningHelper.php
Storage/tests/Snippet/BucketTest.php
Storage/tests/System/PostPolicyTest.php
Storage/tests/Unit/ConformanceTest.php
Storage/tests/Unit/SigningHelperTest.php
Storage/tests/Unit/StorageConformanceTest.php
Storage/tests/Unit/data/signed-url-v4-testdata.json

note: this PR is based off of #2720, and that PR must be merged first. When reviewing, you may find it more convenient to view the [comparison between those two branches](https://github.com/jdpedrie/google-cloud-php/compare/storage-conformance...jdpedrie:post-policies) rather than the pull request diff.
This change does not include system tests yet.

feat: add support for signed post policies

---

BigQuery/composer.json
BigQuery/src/JobConfigurationTrait.php
Firestore/composer.json
Trace/composer.json
Trace/src/Trace.php
composer.json

Greetings 👋
- Replaced `"ramsey/uuid": "~3"` with `"ramsey/uuid": "^3.0|^4.0"` (`^` instead of `~` to match the other definitions)
- Replaced occurrences of `(string)` or implicit casts with `->toString()` (it's defined in the `UuidInterface` for both versions)
I searched the usages with full-text searches for `ramsey` and `uuid`, I hope I didn't miss anything 🤞
:octocat:

feat: add support for ramsey/uuid v4

---

Spanner/src/Connection/Grpc.php
Spanner/tests/System/BackupTest.php

Update spanner lroResponseMappers to comply with changes in Core in PR #2536
This PR should wait for #2536 to merge in order to update google/cloud-core dependency version.

fix: update spanner lroResponseMappers to map types for `metadata` and `response` separately

---

Spanner/composer.json
Spanner/src/Connection/Grpc.php
Spanner/tests/System/BackupTest.php

Deserialize responses and metadata returned by Instance#backupOperations() and Instance#databaseOperations().
Required for issue [#1050](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1050).

feat(spanner): deserialize response & metadata in operation lists

---

Spanner/composer.json

This will ensure the proper google/cloud-core version is used to enable proper LRO encoding updated in #2837

chore: update require version for google/cloud-core

---

Storage/src/Connection/Rest.php
Storage/tests/Unit/Connection/RestTest.php

The check for a user provided MD5 hash contains a typo which causes a new hash to be generated even if the user already provided one.
Fixes #2969

fix: fix check for user provided MD5 hash

---

Firestore/src/Query.php
Firestore/src/ValueMapper.php
Firestore/tests/System/QueryTest.php
Firestore/tests/Unit/ValueMapperTest.php

IN query filter [allows](https://firebase.google.com/docs/firestore/query-data/queries#in_and_array-contains-any) an array of arrays as its value, this could be written as
```php
$containsQuery = $citiesRef->where('regions', 'in', [['west_coast'], ['east_coast']]);
```
But currently this code throws an exception. RPC reference [says](https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.v1#google.firestore.v1.Value) that an array value "Cannot directly contain another array value", and `Firestore\ValueMapper` [checks it](https://github.com/googleapis/google-cloud-php/blob/master/Firestore/src/ValueMapper.php#L261-L263). But if we remove that check, this code works fine, and a query returns exactly what is expected.
This PR adds a "pseudotype" MultiValue, which is …

feat: allow array-of-arrays value for "in" query filter

---

Debugger/src/Breakpoint.php

When serializing the `Breakpoint` object the `evaluatedExpressions` were not being properly serialized. They need to be converted to a serializable format before running `json_encode()` on them, so we need to run the `info()` function on each of them, the same way that we are doing for the `stackFrames`
Fixes #2971

fix: correctly serialize evaluated expressions

---

Firestore/src/V1beta1/Gapic/FirestoreGapicClient.php
docs/contents/cloud-firestore.json

We don't generate updates to this client anymore, so synth change isn't needed.

feat: deprecate v1beta1 client

---

Spanner/tests/System/PartitionedDmlTest.php
Spanner/tests/System/WriteTest.php

The emulator now supports PDML so these tests no longer need to be skipped.

test: remove emulator skip for PDML

---

docs/toc.json

Related to #3135.
I updated the docs site to change the table of contents authentication guide to something more current. This removes obsolete links from the table of contents.

docs: update table of contents

---

Spanner/src/Session/CacheSessionPool.php
Spanner/tests/Unit/Session/CacheSessionPoolTest.php

Adds a public method for `Spanner\Session\CacheSessionPool` to maintain cached sessions and keep them alive.
Related to issue #2411. Implementation details are described [here](https://docs.google.com/document/d/1rBpvz3tGGysmsM5qoXxo5y-tI6hSquMMY0zKnb11gm8/edit?usp=sharing).

feat: add maintain() method for CacheSessionPool

---

Core/src/RequestWrapper.php

Currently, we are using our own retryFunction and track the percentiles of retry attempts for various instrumentation of our app. Since we have moved to purely async behavior we have lost this metrics which has helped us in triage in the past.

feat: Surface  to retryFunction for observation.

---

Firestore/src/Connection/Grpc.php

Recursion in protobuf messages causing out of memory errors when printed is a known issue. This change fixes #2581 by not printing the details of the generated client in traces and `print_r`. A similar pattern is used throughout Spanner for the same reasons.

fix: exclude generated client from debug dump

---

Core/composer.json
composer.json

Greetings 👋 ,
[Guzzle 7.0 has been released](https://github.com/guzzle/guzzle/releases). This PR widens the version constraint to be able to use it with the `google/cloud` library.
This is a non-breaking change by itself, but https://github.com/googleapis/google-auth-library-php/pull/256 and https://github.com/GoogleCloudPlatform/php-tools/pull/80 are needed to make the change effective.
```
❯ composer why guzzlehttp/guzzle
google/cloud        dev-guzzle7  requires  guzzlehttp/guzzle (^5.3|^6.0|^7.0)
google/auth         v1.9.0       requires  guzzlehttp/guzzle (~5.3.1|~6.0)
google/cloud-tools  v0.9.1       requires  guzzlehttp/guzzle (~5.3|~6.0)
```
:octocat:

Add support for Guzzle 7.x

---

Spanner/src/Connection/Grpc.php
Spanner/src/Instance.php
Spanner/src/InstanceConfiguration.php
Spanner/src/Operation.php
Spanner/src/Session/Session.php
Spanner/src/SpannerClient.php
Spanner/tests/Snippet/Batch/BatchSnapshotTest.php
Spanner/tests/Snippet/BatchDmlResultTest.php
Spanner/tests/Snippet/TransactionalReadMethodsTest.php
Spanner/tests/Unit/Batch/BatchClientTest.php
Spanner/tests/Unit/Batch/BatchSnapshotTest.php
Spanner/tests/Unit/Connection/GrpcTest.php
Spanner/tests/Unit/DatabaseTest.php
Spanner/tests/Unit/InstanceConfigurationTest.php
Spanner/tests/Unit/InstanceTest.php
Spanner/tests/Unit/OperationTest.php
Spanner/tests/Unit/SpannerClientTest.php

Currently many of the google-cloud-resource-prefix headers are being set to IDs rather than the fully qualified names that are expected. This PR ensures the google-cloud-resource-prefix headers are being correctly set as fully qualified names.

fix: correctly set google-cloud-resource-prefix headers

---

BigQuery/src/JobConfigurationTrait.php

Documentation for methods `dryRun` and `label` in `JobConfigurationTrait`  is not accurate, I'm taking the correct information from here: https://github.com/googleapis/google-cloud-php/blob/master/BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json#L1891-L1896
It looks like the incorrect description was taken from here: 
https://github.com/googleapis/google-cloud-php/blob/master/BigQuery/src/QueryJobConfiguration.php#L133-L149

docs: add accurate description to job configuration methods

---

Core/src/ExponentialBackoff.php
Core/src/Retry.php

In my initial PR, I missed a few call locations. This will allow us to pass in the retryAttempt for instrumentation purposes when we override the default retryFunction

feat: pass retryAttempt to all retryFunction calls

---

Firestore/src/WriteBatch.php
Firestore/tests/Unit/WriteBatchTest.php

When we want to set a document with the "merge" flag enabled, an empty arrays fields are not set because their path is removed. I'm not sure if the current behavior is correct, I suppose it's not.

fix: preserve empty arrays when using set() with merge enabled

---

Storage/src/StreamWrapper.php
Storage/tests/System/StreamWrapper/AppendTest.php
Storage/tests/System/StreamWrapper/FlushTest.php
Storage/tests/Unit/StreamWrapperTest.php

Closing #924.
Adds «a» (append) open mode for StreamWrapper. Example:
```php
$file = fopen('gs://my-bucket/my-object', 'a');
```
Adds an option to flush stream buffer using `fflush()` function. By default this function does nothing and returns false. Flushing is enabled by passing a stream context with `flush` option set to `true`. Example:
```php
$ctx = stream_context_create(['gs' => ['flush' => true]]);
$file = fopen('gs://my-bucket/my-object', 'w', false, $ctx);
fwrite($file, 'hello');
fflush($file); // my-object now contains 'hello'
fwrite($file, ' world');
fclose($file);
```
Both features are implemented using composite objects. When a non-empty object is opened for append or `fflush()` called current stream is closed and a «tail» object is created in the same bucket. All following …

feat: support fflush() and append mode in StreamWrapper

---

.github/workflows/docs.yml

Fixes the problem of the manifest not being updated. Results in a few extraneous files in the gh-pages branch, but no impact on users.

chore: deploy full docs folder

---

Bigtable/src/BigtableClient.php
Debugger/src/DebuggerClient.php
Language/src/LanguageClient.php

`LanguageClient` and `DebuggerClient` both use `RequestWrapper`, and so should have `quotaProject` mentioned in their constructor parameters
`Bigtable` uses GAPIC, so I'm not as sure where this stands
fixes #3253

fix: adds quota project doc to language, debugger and bigtable

---

BigQuery/src/BigQueryClient.php
BigQuery/src/Bytes.php
BigQuery/src/CopyJobConfiguration.php
BigQuery/src/Dataset.php
BigQuery/src/Date.php
BigQuery/src/ExtractJobConfiguration.php
BigQuery/src/InsertResponse.php
BigQuery/src/Job.php
BigQuery/src/LoadJobConfiguration.php
BigQuery/src/Model.php
BigQuery/src/Numeric.php
BigQuery/src/QueryJobConfiguration.php
BigQuery/src/QueryResults.php
BigQuery/src/Table.php
BigQuery/src/Time.php
BigQuery/src/Timestamp.php
BigQuery/tests/Snippet/BigQueryClientTest.php
BigQuery/tests/System/BigQueryTestCase.php
BigQuery/tests/System/LoadDataAndQueryTest.php
BigQuery/tests/System/ManageTablesTest.php
BigQuery/tests/System/RegionalizationTest.php
BigQuery/tests/Unit/BigQueryClientTest.php

Added optional `projectId` argument for `BigQueryClient#dataset()` method. Added `copy()`, `extract()`, and `load()` methods for `BigQueryClient` creating job configurations.
Closes #1512.

feat: create references to tables from other projects

---

Firestore/src/Query.php
Firestore/tests/System/QueryTest.php
Firestore/tests/Unit/QueryTest.php

I was looking for a way to query several documents by document IDs using `IN` query.
It turned out that the PHP library doesn't support that at all. Please consider adding this.
Please let me know if any style updates are necessary.

feat: add support for IN queries with documents IDs

---

Storage/tests/System/ManageObjectsTest.php
Storage/tests/System/StreamWrapper/DirectoryTest.php

Fixing two broken system tests:
* flaky `StreamWrapper\DirectoryTest` (results depend on tests run order)
* obsolete(?) `ManageObjectsTest#testStringNormalization()` (reads non-existing `storage-library-test-bucket`)

test: fix Storage system tests

---

Core/src/Batch/QueueOverflowException.php
Core/src/Batch/SysvProcessor.php
Core/tests/System/Batch/BatchRunnerTest.php
Core/tests/Unit/Batch/SysvProcessorTest.php

Relates to issue #1336.
`SysvProcessor#submit()` method now uses non-blocking `msg_send()` calls. When the item queue is full (e. g. batch daemon not running) an exception will be thrown.

fix: do not stall on Core\Batch\SysvProcessor#submit() when message queue overflows

---

Core/src/Testing/System/KeyManager.php

`Core\Testing\System\KeyManager` (used in `BigQuery` and `Storage` system tests) uses hardcoded keyring location `us-west1`. This leads to error 400 when created dataset or bucket uses different location (e. g. `us`).
This PR adds a way to set correct location for `KeyManager`.

test: allow changing location for KeyManager

---

BigQuery/tests/System/ManageDatasetsTest.php
BigQuery/tests/System/ManageModelsTest.php

Ensure that keyring and dataset used for system tests have the same location.

test: set correct location for KeyManager

---

.github/emulator/pubsub.sh
.github/workflows/pubsub-emulator-system-tests.yaml
.github/workflows/spanner-emulator-system-tests.yaml

@ava12 this pattern should work for other services as well. I think it would be worthwhile to extend this to other test suites which have emulators available, though not a high priority.

test: run PubSub system tests against emulator

---

.github/workflows/bigtable-emulator-system-tests.yaml

Adds `--group bigtable` parameter to skip `BigtableInstanceAdminClientTest`.

ci: fix Bigtable testing

---

.github/emulator/example-key.json
.github/workflows/bigtable-emulator-system-tests.yaml
.github/workflows/datastore-emulator-system-tests.yaml
.github/workflows/firestore-emulator-system-tests.yaml
.github/workflows/pubsub-emulator-system-tests.yaml

Related to #2721.
Adds a fake key file and sets `GOOGLE_CLOUD_PHP_TESTS_KEY_PATH` and `GOOGLE_CLOUD_PHP_WHITELIST_TESTS_KEY_PATH` required for system tests with emulators.

ci: add empty key file and env vars for emulator workflows

---

Storage/src/StorageClient.php

fixes https://github.com/googleapis/google-cloud-php/issues/3289
Adds IAM permission by default to ensure `signBlob` works when using Metadata credentials.
[NodeJS has similar scope defaults](https://github.com/googleapis/nodejs-storage/blob/master/src/storage.ts#L418)

fix: add IAM to StorageClient by default

---

PubSub/src/Message.php

My phpstan was bugging me when I was using the return type of the `publishMessage` function on a `Message` object and checked for `null`. The docblock says that this is not possible, while the code clearly shows that it is.

fix: Message::publishTime return type is nullable

---

.github/emulator/start-emulator.sh
.github/workflows/datastore-emulator-system-tests.yaml

Related to #2721.
Datastore emulator did not start because project id was not provided. This PR adds `--project` parameter to `start-emulator.sh`.

ci: add project id for Datastore tests

---

Core/src/Batch/BatchDaemon.php

Similar to https://github.com/googleapis/google-cloud-php/blob/a1144e8947b7d904f48315689966d3730fe061ea/Core/src/Batch/BatchJob.php#L151.

feat: run the Garbage Collector after each BatchDaemon iteration

---

Spanner/src/Operation.php
Spanner/src/Transaction.php
Spanner/tests/Snippet/TransactionTest.php
Spanner/tests/Unit/OperationTest.php
Spanner/tests/Unit/TransactionTest.php

This PR adds support for commit stats.
When calling `commit()` on a transaction, you can get commit statistics by specifying the `returnCommitStats` option. Example code:
```
$transaction->commit(['returnCommitStats' => true]);
$commitStats = $transaction->getCommitStats();
```
Currently, the commit stats only contains `mutation_count` which is the total number of mutations for the transaction. Knowing the `mutation_count` value can help you maximize the number of mutations in a transaction and minimize the number of API round trips. You can also monitor this value to prevent transactions from exceeding the system [limit](http://cloud.google.com/spanner/quotas#limits_for_creating_reading_updating_and_deleting_data).

feat(spanner): add commit stats support

---

Bigtable/src/ChunkFormatter.php
Bigtable/tests/Unit/ChunkFormatterTest.php

Although it's possible to write a row key of value "0" to Bigtable, the PHP Bigtable client currently doesn't support reading such rows. The reason is because there is currently a validation check that uses the ! operator, and the boolean value of "0" in PHP happens to be `false`.  
This change would instead use a strict value check for an empty row key string.

fix: add support for reading Bigtable key value of zero

---

Spanner/src/Backup.php
Spanner/src/Connection/Grpc.php
Spanner/tests/System/BackupTest.php
Spanner/tests/Unit/BackupTest.php

This PR adds support for PITR. It allows users to specify the timestamp for a consistent copy of a database when creating a new backup.
Sample code:
```
$operation = $backup->create($database->name(), $expireTime, [
"versionTime" => $versionTime,
]);
$operation->pollUntilComplete();
```

feat(spanner): add support for Point In Time Restore (PITR)

---

Bigtable/src/BigtableClient.php

Sets KeepAlive timer to 30s (Google Frontends are configured limits keepalive calls at 30s by default. If used below 30s, grpc automatically increases keepalive time by 2x after too_many_ping commands).
Sets KeepAliveTimeout to 10s (conservative)

feat: add keepalive setting in data client

---

Logging/README.md

the current URL results in a 404

docs: fix logging README link to API docs

---

Core/composer.json
Core/src/AnonymousCredentials.php
Core/tests/Unit/AnonymousCredentialsTest.php
composer.json

Anonymous credentials are being used in `google/cloud`, but they do not implement all the interfaces required by this library.
- Update `google/auth` to a minimum of `v1.12.0`, which is when `UpdateMetadataInterface` was added.
- Add `UpdateMetadataInterface` and `GetQuotaProjectInterface` to `AnonymousCredentials`
- **Note**: `SignBlobInterface` was left off because it doesn't really make sense with `AnonymousCredentials`.

fix: anonymous credentials

---

Core/src/RequestWrapperTrait.php

Motivation: This lets us cache the result of `ApplicationDefaultCredentials::onGce()`, saving us a ping to the metadata server.
Let me know if I'm missing something, or if there was a good reason to provide `null` here.

feat: Allow RequestWrapperTrait to use its auth cache when fetching ADC

---

README.md

Fixes broken Authentication Guide link in Readme(reoccurrence of #3897)

docs(Readme): Fixes "Authentication Guide" link

---

.github/workflows/spanner-emulator-system-tests.yaml
Spanner/src/ValueMapper.php

This PR pins the `grpc` version installed for the Spanner emulator Github action to 1.37.1 to prevent `UNAUTHENTICATED` errors. This was discussed in https://github.com/googleapis/google-cloud-php/issues/3911.
Successful emulator run: https://github.com/googleapis/google-cloud-php/pull/4112/checks?check_run_id=2846226392

ci(spanner): fix UNAUTHENTICATED emulator errors

---

.github/workflows/spanner-emulator-system-tests.yaml
Spanner/src/Connection/Grpc.php
Spanner/src/Instance.php
Spanner/tests/System/AdminTest.php
Spanner/tests/Unit/Connection/GrpcTest.php
Spanner/tests/Unit/InstanceTest.php
Spanner/tests/Unit/SpannerClientTest.php

This PR adds support for low cost instances. By using the new processing units option instead of nodes, users are able to create and manage instances that uses less resources than a single node.
Note: 1000 processing units = 1 node

feat(spanner): add support for LCI

---

Firestore/src/ValueMapper.php
Firestore/tests/System/ValueMapperTest.php
Firestore/tests/Unit/ValueMapperTest.php

Fix empty map #4250 
First (public) PR here: ran the unit, system and snippet tests successfully and checked `composer style`

fix: correctly decode empty map values

---

composer.json
dev/src/DocGenerator/DocGenerator.php

- Fix `T_READONLY` syntax error when generating docs by setting the emulator to use PHP 8.0 (See https://github.com/nikic/PHP-Parser/issues/799#issuecomment-885599753)
- Fix OOM errors in `AppEngineFlexHandlerTest` (See https://github.com/Seldaek/monolog/issues/1577)

fix: phpparser syntax error for 8.1 and OOM errors in AppEngineFlexHandlerTest

---

Logging/composer.json

On PHP 8.0, this package can be installed beside a psr library supporting `psr/log:2.0` or `psr/log:3.0`, and the interface is not compatible with our implementation. Therefore we need to define that this package is only compatible with `psr/log:^1.0`.
Looking into the [provide](https://getcomposer.org/doc/04-schema.md#provide) keyword in the composer JSON schema, this does not seem sufficient to prevent incompatible logging implementations, e.g:
```
"provide": {
"psr/logging-implementation: "^1.0"
}
```
has no effect on the packages which are allowed
I think we want to use [conflict](https://getcomposer.org/doc/04-schema.md#conflict) in the composer JSON schema, similar to how this is being used in [symfony/console](https://github.com/symfony/console/blob/5.3/composer.json#L46).

[Logging] fix: require the supported psr/log version

---

Storage/src/Bucket.php
Storage/src/Connection/ServiceDefinition/storage-v1.json
Storage/tests/System/IamConfigurationTest.php

The PR deals with the issue #4524 where in we need to change the references of 'unspecified' to 'inherited'.

Storage: Changed references of 'unspecified' to 'inherited'

---

Compute/tests/System/V1/AddressTest.php
Compute/tests/System/V1/SmokeTest.php

1) use LRO instead of custom methods
2) unskip test for a required field set to zero.

tests: update compute tests to use LRO instead of custom polling

---

.github/.OwlBot.lock.yaml

Updates to a new post processor that deletes the staging directory.

chore: update owlbot lock file

---

.github/workflows/release.yml
Core/unit-bootstrap.php

Without this, the component `split` command fails because the appropriate version of PHP (7.4) has not been set up

fix: step ordering for component release

---

Spanner/owlbot.py

See https://github.com/googleapis/google-cloud-php/pull/4888
Without this, tests are failing in spanner with the following error (because the `getTransport` method is being overwritten)
```
Prophecy\Exception\Doubler\MethodNotFoundException: Method `Double\Google\Cloud\Spanner\V1\SpannerClient\P73::getTransport()` not found.
```

fix: [Spanner] exclude partial veneer SpannerClient from owlbot

---

Bigtable/owlbot.py
Firestore/owlbot.py
Redis/owlbot.py
Speech/owlbot.py
Translate/owlbot.py

Partial veneer excludes were being greedy, also excluding `GrpcClient.php` classes, which are autogenerated and shouldn't be excluded, and in many cases excluding veneer classes which do not contain customizations.
This was causing the error in https://github.com/googleapis/google-cloud-php/pull/4887
We should be explicit whenever a veneer is customized. This will prevent unexpected behavior.

fix: make partial veneer client excludes explicit

---

.github/release-please.yml

Let release-please handle the GitHub tagging

build: switch release tagging to release-please

---

BigQuery/src/ValueMapper.php
Core/src/ArrayTrait.php
Core/tests/Unit/ArrayTraitTest.php

The new argument `$onEmpty` is returned when the input array is empty.
`ValueMapper` in `BigQuery` should receive a `false` on passing an empty array to `isAssoc`.
Should fix #3937's error message.

fix(Core): Add a default argument to ArrayTrait::isAssoc

---

Storage/composer.json
Storage/src/StreamWrapper.php

fix(storage): Added stream_set_option in StreamWrapper

---

Vision/owlbot.py

For some reason the Vision API was excluding `gapic_metadata.json`. I believe this is an error.
Also, we want to be explicit about which files (in this case, Client classes) we exclude

chore: [Vision] fix owlbot copy_excludes

---

Logging/src/PsrLogger.php
Logging/tests/Unit/PsrLoggerTest.php

In PHP 8.1, when implementing `Serializable` without implementing the magic `__serialize`/`__unserialize` methods, a deprecation warning will be generated.
This PR adds these methods and moves the logic as to not duplicate any code but still provide BC for >= PHP 7.2. Tests remain unchanged and working.
The `Serializable` interface will be removed in PHP 9.0:
- RFC: https://wiki.php.net/rfc/phase_out_serializable
- Deprecation Warning docs: https://www.php.net/manual/en/class.serializable.php
>As of PHP 8.1.0, a class which implements Serializable without also implementing __serialize() and __unserialize() will generate a deprecation warning.

fix(logging): Fix deprecation message in PsrLogger with PHP 8.1

---

BigQuery/src/QueryResults.php
Bigtable/src/ChunkFormatter.php
Bigtable/src/ResumableStream.php
Core/src/Iterator/ItemIteratorTrait.php
Core/src/Iterator/PageIteratorTrait.php
Core/src/Testing/FileListFilterIterator.php
Core/src/Testing/Snippet/Coverage/ExcludeFilter.php
Core/src/Testing/Snippet/Parser/Snippet.php
Datastore/src/DatastoreSessionHandler.php
Datastore/src/Entity.php
Datastore/src/EntityPageIterator.php
Datastore/src/Key.php
Datastore/src/Query/GqlQuery.php
Datastore/src/Query/Query.php
Datastore/tests/Unit/SampleEntity.php
Debugger/src/MatchingFileIterator.php
Firestore/src/DocumentSnapshot.php
Firestore/src/FirestoreSessionHandler.php
Firestore/src/QuerySnapshot.php
Spanner/src/Result.php
Storage/src/Lifecycle.php
Storage/src/ObjectPageIterator.php
Trace/src/Attributes.php

Closes #4554 
I honestly have no idea how to reliably test this, but what I did was open the project in PHPStorm, set the language level to PHP 8.1, and run the **Class Hierarchy Checks** inspection.
See https://php.watch/versions/8.1/internal-method-return-types#ReturnTypeWillChange
:octocat:
PS: This will probably not survive PHP 8.2 😅

fix: Improve PHP 8.1 compatibility by disabling deprecation notices

---

Monitoring/owlbot.py
Monitoring/src/V3/GroupServiceClient.php
Monitoring/src/V3/NotificationChannelServiceClient.php
Monitoring/src/V3/ServiceMonitoringServiceClient.php
Monitoring/src/V3/UptimeCheckServiceClient.php

We accidentally merged an update which broke backwards compatibility with some of the Monitoring Clients by removing the `projectName` static method. This adds them back.
See https://github.com/googleapis/google-cloud-php/pull/4917

fix: add back projectName methods for monitoring clients

---

composer.json
dev/sh/style-fix

This script is identical to our `composer style` script and should help contributors fix some lint errors automatically.

chore: Add a style-fix composer script

---

PubSub/src/ResourceNameTrait.php

Fixes #4869 by null-coalescing the second param of `preg_match()` to an empty string.
Alternative solutions:
- ensuring the param is non-nullable (which may be better overall given the type signature here, though it comes with a higher surface area of changes required)
- update it to accept a nullable `$name`, and `if $name === null return false;` (which makes sense - if only a `$type` is provided, it's not a fully-qualified _resource_ name)
edit:
* CLA signed

fix(PubSub): PHP8.1 deprecation warning on preg_match()

---

Core/src/EmulatorTrait.php
Core/src/InsecureCredentialsWrapper.php
Spanner/src/Connection/Grpc.php

fix of https://github.com/grpc/grpc/issues/29233, which is caused by https://github.com/grpc/grpc/pull/25586 which removed insecure channel.
Regardless whether Spanner connects to emulator or production server, gax-php always create a CredentialsWrapper (https://github.com/googleapis/gax-php/blob/v1.12.0/src/GapicClientTrait.php#L434) and add it to callstack (https://github.com/googleapis/gax-php/blob/v1.12.0/src/GapicClientTrait.php#L610).
When creating gRPC calls, GrpcTransport calls CredentialsWrapper (https://github.com/googleapis/gax-php/blob/v1.12.0/src/Transport/GrpcTransport.php#L258-L259) to setup a callback for auth token, which requires secure level to be equal or higher than GRPC_PRIVACY_AND_INTEGRITY which doesn’t work on an insecure channel.

fix: grpc issue (UNAUTHENTICATED errors against Cloud Spanner emulator in v1.45.0)

---

Datastore/src/Connection/Grpc.php
Firestore/src/Connection/Grpc.php
PubSub/src/Connection/Grpc.php

Adds `InsecureCredentialsWrapper` for emulators across applicable packages
https://github.com/googleapis/google-cloud-php/pull/5224

feat: fix emulator config for datastore, firestore, and pubsub

---

.github/release-please.yml

This was a bugfix in release-please - if there is a `packageName` configured for the app, it expects that the release tag will have the `packageName` as part of the tag.

build: release-please for component-less release should not use `packageName`

---

Monitoring/src/V3/GroupServiceClient.php
Monitoring/src/V3/NotificationChannelServiceClient.php
Monitoring/src/V3/ServiceMonitoringServiceClient.php
Monitoring/src/V3/UptimeCheckServiceClient.php
Monitoring/tests/Unit/V3/CustomMethodsTest.php

Found this error when running tests in the php docs samples:
```
3) Google\Cloud\Samples\Monitoring\monitoringTest::testCreateUptimeCheck
Error: Class 'Google\Cloud\Monitoring\V3\PathTemplate' not found
/tmpfs/src/github/php-docs-samples/monitoring/vendor/google/cloud-monitoring/src/V3/UptimeCheckServiceClient.php:43
/tmpfs/src/github/php-docs-samples/monitoring/src/create_uptime_check.php:56
/tmpfs/src/github/php-docs-samples/testing/sample_helpers.php:58
/tmpfs/src/github/php-docs-samples/monitoring/src/create_uptime_check.php:66
/tmpfs/src/github/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/TestTrait.php:133
/tmpfs/src/github/php-docs-samples/testing/vendor/google/cloud-tools/src/TestUtils/TestTrait.php:144 …
```

fix: missing monitor client imports

---

composer.json

Hey there 👋 
This change addresses the [CVE-2022-29248](https://github.com/advisories/GHSA-cwmx-hcrq-mhc3) security issue with Guzzle.
🐙

chore: Raise minimum versions of Guzzle

---

PubSub/composer.json

This will help ensure https://github.com/googleapis/google-cloud-php/pull/5240 works as intended.

chore: require latest version of core

---

Core/src/Exception/ServiceException.php

The constructor accepts a nullable exception for this property. The phpdoc however states that it's always an exception. This can lead to static analysis issues.

fix(core): Fixed return type for service exception

---

PubSub/src/Subscription.php

Helper added to retrieve transiently failed ackIds from an exception object.

PubSub: (1/3) Added helper to retrieve temporarily failed ackIds

---

Monitoring/owlbot.py

The Many APIs PR (#5404) is failing because changes were reverted to `UptimeCheckServiceClient` that were supposed to be excluded, but the wrong class was being excluded.

chore: fix monitoring owlbot excluse

---

Datastore/owlbot.py
Firestore/owlbot.py
Spanner/owlbot.py

We made manual changes to `Firestore`, `Datastore`, and `Spanner` in the last release in order to preserve backwards compatibility better in those libraries. This will make sure those changes do not get overwritten in the next owlbot release.

chore: readonly fix in owlbot

---

.github/workflows/tests.yaml

The addition of #5355 has caused an issue on OwlBot PRs, as every time an OwlBot PR is updated, the bot adds a `owlbot:run` label. This in turn kicks off an action run which gets skipped. The problem is that, the skipped action is then seen as the most recent one, and so the previous test run is no longer visible in the PR, and the PR is no longer mergeable unless `gh:run-tests` is added. This means every test suite would need to be run an _extra_ time.
I looked for a way to fix it and keep the label, but I believe the _intended_ way is to either:
1. Update a PR by merging in the `main` branch if there are changes we would like it to have (as was the case with the older owlbot PRs when we switched to GH actions). This is doable on the command line (as I did in the screenshot below).
- One …

chore: remove label action

---

Core/src/Testing/GcTestListener.php
Datastream/owlbot.py
Optimization/owlbot.py
phpunit-php5.xml.dist
phpunit.xml.dist

- Fix for `Datastream` and `Optimization` to ignore protobuf compatibility files in `owlbot.py`
- Fix autoloading for `GcTestListener` (this isn't super important but I put it in here anyway)

chore: fix owlbot configuration and GcTestListener autoloading

---

BigQuery/src/BigQueryClient.php
BigQuery/src/Connection/Rest.php
BigQuery/src/Dataset.php
BigQuery/src/ExtractJobConfiguration.php
BigQuery/src/InsertResponse.php
BigQuery/src/Job.php
BigQuery/src/JobConfigurationTrait.php
BigQuery/src/Model.php
BigQuery/src/QueryJobConfiguration.php
BigQuery/src/QueryResults.php
BigQuery/src/Routine.php
BigQuery/src/Table.php
BigQuery/src/ValueMapper.php

Using `phpdoc`, I was able to confirm that these changes will fix the previous references
I also marked `Connection\Rest` as `@internal`. This will allow the docs to leave it out of our reference documentation

chore: [BigQuery] fix class references in phpdoc

---

Firestore/tests/Snippet/FieldValueTest.php

Firestore emulator tests are failing currently with following error:
```
Google\Cloud\Firestore\Tests\Snippet\FieldValueTest::testDeleteField
TypeError: Google\Cloud\Firestore\DocumentReference::writeResult(): Argument #1 ($commitResponse) must be of type array, null given, called in /usr/local/google/home/vishwarajanand/github/google-cloud-php/Firestore/src/DocumentReference.php on line 302
/usr/local/google/home/vishwarajanand/github/google-cloud-php/Firestore/src/DocumentReference.php:427
/usr/local/google/home/vishwarajanand/github/google-cloud-php/Firestore/src/DocumentReference.php:302
/usr/local/google/home/vishwarajanand/github/google-cloud-php/Firestore/vendor/google/cloud-core/src/Testing/Snippet/Parser/Snippet.php:167
/usr/local/google/home/vishwarajanand/github/google-cloud-php …
```

fix(firestore): Fixing Firestore emulator tests

---

BigQuery/composer.json
Core/composer.json
Datastore/composer.json
Debugger/composer.json
ErrorReporting/composer.json
Firestore/composer.json
Language/composer.json
Logging/composer.json
PubSub/composer.json
Spanner/composer.json
Speech/composer.json
Storage/composer.json
Trace/composer.json
Translate/composer.json
Vision/composer.json
composer.json

For context please see: https://github.com/sebastianbergmann/phpunit/issues/5033

chore: explicitly import prophecy

---

AutoMl/README.md

Per https://github.com/googleapis/google-cloud-php/issues/5453, user is unable to `createDataset`. Upon checking, one of the issues is a missing import for `Dataset `.

fix: update sample code for automl create dataset

---

Firestore/src/PathTrait.php
Firestore/tests/Unit/PathTraitTest.php

If `relativeName()` ends up returning `null` then the subsequent call to `splitName()` will pass the same into `trim()` which causes a deprecation warning in PHP 8.1:
```
trim(): Passing null to parameter #1 ($string) of type string is deprecated
firebase/vendor/google/cloud-firestore/src/PathTrait.php:178
firebase/vendor/google/cloud-firestore/src/PathTrait.php:136
firebase/vendor/google/cloud-firestore/src/CollectionReference.php:298
```
This PR interrupts that chain at the most logical point for an early return.

Fix null trim

---

README.md

Partly addresses: https://github.com/googleapis/google-cloud-php/issues/5535
* CI builds stats should be upgraded to php7.4
* PHP 7.2 tests haven't been running since April
1. Get build status to green

chore: update CI status in README to php74

---

Spanner/tests/System/PgWriteTest.php

Removing the tests as JSONB array isn't supported yet.

chore(Spanner): Removed JSONB array system tests

---

.kokoro/docs/publish.sh
composer.json
dev/src/DocFx/Command/DocFx.php
dev/src/DocFx/Node/ClassNode.php
dev/src/DocFx/Node/ConstantNode.php
dev/src/DocFx/Node/MethodNode.php
dev/src/DocFx/Node/XrefTrait.php
dev/src/DocFx/Page/OverviewPage.php
dev/src/DocFx/Page/PageTree.php
dev/tests/Unit/DocFx/CommandTest.php
dev/tests/Unit/DocFx/NodeTest.php
dev/tests/fixtures/docfx/toc.yml

Fixes a small issue we found when staging - the TOC items needs to be wrapped in a "component" TOC item with the `name` and `uid`.
Also adds "beta" tag to any class in a versioned namespace containing `beta` or `alpha`
Also refactors out `XrefTrait::$protoPackages`, as this is deprecated in PHP 8.1

fix(docs): wrap TOC in component

---

.github/workflows/docs.yml
.github/workflows/release.yml

ref [github doc](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples), Github is migrating away from `set-output` and it causes warnings in our test logs.
With this change, we are migrating to `GITHUB_OUTPUT` for writing workflow logs.
Example of such logs:

chore: migrate away from set-output

---

Core/src/ExponentialBackoff.php
Core/src/RequestWrapper.php
Core/tests/Unit/RequestWrapperTest.php

Related to https://github.com/googleapis/google-auth-library-php/pull/422
When an empty token `[]` is returned from the `FetchAuthTokenInterface`, the `RequestWrapper` attempts to put this in the `Authorization Bearer` header and send it in anyway. It would be better to either skip adding the header (rather than send in an empty bearer token), or throw the exception early, so that we know where the problem is.

fix: throw an exception when the credentials fetcher cannot fetch a token

---

Storage/src/StorageObject.php
Storage/tests/System/ManageObjectsTest.php
Storage/tests/Unit/StorageObjectTest.php

Addresses : https://github.com/googleapis/google-cloud-php/issues/3347
Moving object seek before file creation while downloading a storage object.
Directly edited the `/vendor` folder in `php-docs-samples` and validated that:
1. File is created while object is present
`php src/download_public_file.php $GOOGLE_STORAGE_BUCKET sample.txt ./temp.txt` 
2. No file is created when object is not present (previously an empty file was being created)
`php src/download_public_file.php $GOOGLE_STORAGE_BUCKET no_sample.txt ./temp.txt`
3. Added a System test which evaluates against the network: (log is below, since system tests are not running on PR)
```
google-cloud-php/Storage % XDEBUG_MODE=debug vendor/bin/phpunit -c phpunit-system.xml.dist --filter="testDownloadsToFileShouldNotCreateFileWhenObjectNot …
```

fix(storage): seeking object before file creation

---

Storage/src/Bucket.php
Storage/src/StorageClient.php
Storage/tests/System/ManageBucketsTest.php
Storage/tests/Unit/BucketTest.php

Addresses https://github.com/googleapis/google-cloud-php/issues/5479
(couldn't test in local, since feature not enabled in my gcp proj)
Design doc: [go/php-storage-autoclass](http://goto.google.com/php-storage-autoclass)
ref: Test plan - [go/sat-client-library-request](https://goto.google.com/sat-client-library-request)
**Note:** Another PR with same changes were reverted before: https://github.com/googleapis/google-cloud-php/pull/5487

feat(storage): adding tests for autoclass

---

AccessApproval/phpunit.xml.dist

Fixes: https://github.com/googleapis/google-cloud-php/issues/5382
Checkout [latest test logs](https://pipelines.actions.githubusercontent.com/serviceHosts/0f3ab822-4928-4da8-b790-ff9c74861046/_apis/pipelines/1/runs/7060/signedlogcontent/23?urlExpires=2022-11-08T09%3A06%3A31.6074542Z&urlSigningMethod=HMACV1&urlSignature=Fi0N7sMRutepI6fzw9ENpWz50ZXaBveZArW%2FAjQ%2BuoQ%3D) have this unnecessary warning:
```
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 4:
- Element 'testsuite': The attribute 'name' is required but missing.
Test results may not be as expected.
```

chore: add name attr in phpunit config testsuite

---

dev/src/DocFx/Node/DocblockTrait.php
dev/src/DocFx/Node/FencedCodeBlockTrait.php
dev/src/DocFx/Node/XrefTrait.php
dev/src/DocFx/Page/PageTree.php
dev/tests/Unit/DocFx/NodeTest.php
dev/tests/fixtures/docfx/V1.ImageAnnotatorClient.yml
dev/tests/fixtures/docfx/V1.ProductSearchClient.yml
dev/tests/fixtures/docfx/toc.yml

- Fixes broken links for links that contained spaces (e.g. `[this link here][google.cloud.somepackage.SomeMessage]`)
- Fixes other broken links by refactoring how `$protoPackages` are determined
- Automatically adds `php` to the end of fenced code blocks if no language is specified (do we have any instances where this would be a different language?)

docs: fix cloud rad links, add php typehint to fenced codeblocks

---

BeyondCorpAppConnections/README.md
BeyondCorpAppConnections/composer.json
BeyondCorpAppConnectors/README.md
BeyondCorpAppConnectors/composer.json
BeyondCorpAppGateways/README.md
BeyondCorpAppGateways/composer.json
BeyondCorpClientConnectorServices/README.md
BeyondCorpClientConnectorServices/composer.json
BeyondCorpClientGateways/README.md
BeyondCorpClientGateways/composer.json
Firestore/composer.json

- Removes redundancy in BeyondCorp naming
- Makes description in `Firestore/composer.json` consistent

chore: fix typos in beyondcorp

---

Firestore/src/BulkWriter.php
Firestore/src/WriteBatch.php

Fixes documentation for bulkwriter docs:
1. [Link on main](https://googleapis.github.io/google-cloud-php/#/docs/google-cloud/main/firestore/writebatch) vs now:
2. [Link on main](https://googleapis.github.io/google-cloud-php/#/docs/google-cloud/main/firestore/bulkwriter?method=__construct) vs now:

chore: documentation fix for bulkwriter

---

.kokoro/continuous/run-tests.sh

In order to fix the build flag of this repo (https://github.com/googleapis/google-cloud-php/issues/5535), I tried updating the memory limit in test php images, https://github.com/googleapis/testing-infra-docker/pull/250 but the build fails.
So, as a fix, I am adding memory limit in the `phpunit` command.

fix: added memory limit to phpunit

---

renovate.json

Currently, we only use python in Cloud RAD for calling `docsuploader`, which uploads the zip files to GCS. This is a very small part of the process, and yet, we get [constant requests](https://github.com/googleapis/google-cloud-php/blob/main/.kokoro/docs/docker/requirements.txt) from renovate to keep these deps up-to-date. 
This PR configures minor/patch updates to python dependencies to be bundled in a single PR and automerged. This should help cut down on the noise from minor updates made to transitive dependencies in `.kokoro/docs/docker/requirements.txt`

chore(docs): configure automerge for python non-major dependencies

---

.gitignore

the `build/` entry in `.gitignore` conflicts with the `Build` component on case-insensitive filesystems like MacOSX

chore: remove build from gitgnore

---

dev/src/DocFx/Node/DocblockTrait.php
dev/tests/fixtures/docfx/V1.ProductSearchClient.yml

(potentially) temporary fix for https://github.com/googleapis/gapic-generator-php/issues/546
See https://github.com/protocolbuffers/protobuf/pull/11208 
Fixes difficult-to-read HTML escaping in [our public documentation](https://cloud.google.com/php/docs/reference/cloud-vision/latest/V1.ProductSearchClient) from
```
projects/&#42;&#47;{table_location=instances/&#42;}/tables/&#42;
```
to
```
projects/*/{table_location=instances/*}/tables/*
```

chore(docs): escape HTML entities

---

Spanner/src/Batch/BatchClient.php
Spanner/src/Connection/Grpc.php
Spanner/src/Database.php
Spanner/src/Instance.php
Spanner/src/Operation.php
Spanner/src/Session/CacheSessionPool.php
Spanner/src/SpannerClient.php
Spanner/tests/Snippet/InstanceTest.php
Spanner/tests/Snippet/Session/CacheSessionPoolTest.php
Spanner/tests/Snippet/SpannerClientTest.php
Spanner/tests/System/BatchTest.php
Spanner/tests/System/OperationsTest.php
Spanner/tests/System/SpannerTestCase.php
Spanner/tests/System/TransactionTest.php
Spanner/tests/Unit/Batch/BatchClientTest.php
Spanner/tests/Unit/DatabaseTest.php
Spanner/tests/Unit/InstanceTest.php
Spanner/tests/Unit/Session/CacheSessionPoolTest.php
Spanner/tests/Unit/SpannerClientTest.php
composer.json

This PR add the FGAC support for PHP Spanner library.
The FGAC integration tests are skipped in the emulator since it has not yet implemented the FGAC support.
Other languages also skips the same. Ref: https://github.com/googleapis/google-cloud-ruby/pull/19067/files#diff-3bf69404604fe1c87333533412f6e24d5867aab51a726e98843ebd63cd39b3a5R28

feat(Spanner): Support FGAC

---

Core/composer.json
Core/src/Exception/ServiceException.php
Core/src/Logger/AppEngineFlexFormatter.php
Core/src/Logger/AppEngineFlexFormatterV3.php
Core/src/Logger/AppEngineFlexHandler.php
Core/src/Logger/AppEngineFlexHandlerFactory.php
Core/src/Logger/AppEngineFlexHandlerV3.php
Core/src/Logger/FormatterTrait.php
Core/src/Testing/Reflection/ReflectionHandlerFactory.php
Core/src/Testing/Reflection/ReflectionHandlerV5.php
Core/tests/Unit/Logger/AppEngineFlexHandlerFactoryTest.php
Logging/composer.json
Logging/src/LogMessageProcessor/MonologMessageProcessor.php
Logging/src/LogMessageProcessor/MonologV3MessageProcessor.php
Logging/src/LogMessageProcessorFactory.php
Logging/src/LogMessageProcessorInterface.php
Logging/src/PsrLogger.php
Logging/tests/Unit/PsrLoggerCompatibilityTest.php
Logging/tests/Unit/PsrLoggerTest.php
composer.json

Hey everyone 👋,
this is a follow-up to #2302 and aims to add support for all currently available monolog/monolog versions.
* `AppEngineFlexHandlerV3` and `AppEngineFlexFormatterV3` are the new implementations for Monolog 3.x.
* The `formatPayload` method in the `FormatterTrait` should support arrays and the new `LogRecord` class
* ~https://github.com/phpDocumentor/Reflection/pull/247  is merged but not released (this PR uses ^5.x-dev for now)~
* ~https://github.com/googleapis/gax-php/pull/389 is not reviewed/merged/released (this PR uses my PR branch from over there for now)~
* ~https://github.com/GoogleCloudPlatform/grpc-gcp-php/pull/45 is not (yet) merged - if it's just because of the CLA, I can create a new PR there~
* The ReflectionHandlerV5 class is a 90% copy of the …

feat: Add support for Monolog 3.x

---

Core/src/Upload/AbstractUploader.php
Storage/src/Connection/Rest.php

chore(Storage): Merging gcs-uploads-retry branch to gcs-retry
Merging gcs-uploads-retry branch to gcs-retry so that all the changes are at a single place so that for further work, can take out a branch from this updated gcs-retry branch.

chore(Storage): Merging gcs-uploads-retry branch to gcs-retry

---

Translate/src/V2/TranslateClient.php
Translate/tests/System/V2/TranslateTest.php
Translate/tests/System/V3/TranslationServiceSmokeTest.php

1. `confidence` value was earlier digested inside `TranslateClient` due to `array_filter`. Now a custom comparator is used in `array_filter` to ensure it surfaces up.
2. Fixed wrong translation in `Translate/tests/System/V2/TranslateTest.php`
3. Now, `base` model is outdated and its redirected to `nmt`, so migrated tests to reflect that.
4. For empty strings, confidence is zero, but it was expected 1 which means 100% confident of the translation.
5. Migrating `assertStringContainsString` to `assertContains`  in case of array comparison.
[b/263478992](http://b/263478992)

fix(Translate): test failures addressed

---

Vision/tests/System/AnnotationsTest.php

Vision tests currently assert on the SafeSearch's likelihood param. These params can have following values:
```
// STRENGTH_HIGH 
'VERY_LIKELY'
// STRENGTH_MEDIUM
'LIKELY'
// STRENGTH_LOW
'POSSIBLE'
'UNLIKELY'
'VERY_UNLIKELY'
```
But due to constant improvements in the underlying models, responses seems to have deviated within the strength range and hence System tests are failing.
As a fix, we are migrating away from asserting on the exact likelihood param to a more sustainable, assert on strength.
```
google-cloud-php/Vision % vendor/bin/phpunit -c phpunit-system.xml.dist
.....R                                                              6 / 6 (100%)
Time: 4.89 seconds, Memory: 8.00 MB
There was 1 risky test:
1) …
```

fix(Vision): relax strict asserts on SafeSearch likelihood param

---

Logging/tests/System/ManageSinksTest.php

Currently, Logging system tests assert on `outputVersionFormat`. But per our docs [ref link](https://cloud.google.com/logging/docs/reference/v2/rest/v2/billingAccounts.sinks#get), this field is deprecated.
Removing asserts on `outputVersionFormat` and relying on asserts over`filter` property.
```
google-cloud-php/Logging % vendor/bin/phpunit -c phpunit-system.xml.dist --filter="ManageSinksTest"
............                                                      12 / 12 (100%)
Time: 51.76 seconds, Memory: 12.00 MB
OK (12 tests, 32 assertions)
google-cloud-php/Logging % 
```
ref: [b/263776172](http://b/263776172)

fix(Logging): outputVersionFormat is deprecated

---

Language/tests/System/AnalyzeTest.php

1. Language tests overtime have changed scores output for sentiments. 
2. `assertEquals` need to be migrated to `assertEqualsWithDelta` due to deprecation. 
`The optional $delta parameter of assertEquals() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertEqualsWithDelta() instead.`
```
google-cloud-php/Language % vendor/bin/phpunit -c phpunit-system.xml.dist                                                (git)-[main]-
......RR                                                            8 / 8 (100%)
Time: 6.81 seconds, Memory: 8.00 MB
There were 2 risky tests:
1) Google\Cloud\Language\Tests\System\V1\LanguageServiceSmokeTest::analyzeSentimentTest
This test did not perform any assertions …
```

fix(Language): fix scores and migrate assertEquals to assertEqualsWithDelta

---

Core/phpunit-system.xml.dist
Core/tests/System/Batch/BatchRunnerTest.php

1. bootstrap file path is wrong in `Core/phpunit-system.xml.dist`. @reviewers pls check whether this will cause failures in other tests.
2. `Core/tests/System/Batch/BatchRunnerTest.php` is generating warnings and failures due to frequent mutations (added sleep) and migrated `assertNotContains` to `assertStringNotContainsString` due to deprecation in latest PhpUnit.
```
google-cloud-php/Core % vendor/bin/phpunit -c phpunit-system.xml.dist              (git)-[fix_core_tests]-
Starting a child.
Running the job with 2 items
Running the job with 1 items
Running the job with 2 items
.                                                                   1 / 1 (100%)Shutting down, waiting for the children
BatchDaemon exiting
Time: 5.49 seconds, …
```

chore(tests): [Core] fixing BatchRunnerTests

---

Bigtable/src/Filter/Builder/FamilyFilter.php
Bigtable/src/Filter/Builder/KeyFilter.php
Bigtable/src/Filter/Builder/QualifierFilter.php
Bigtable/src/Filter/Builder/ValueFilter.php

BigTable typehints for `exactMatch` functions are passed to [`RegexTrait::escapeLiteralValue`](https://github.com/googleapis/google-cloud-php/blob/5b5a70131e1751e63bea8b23073c57d1c9528d20/Bigtable/src/Filter/Builder/RegexTrait.php#L50), which accepts `array|string`. This is seen in [our samples as well](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/main/bigtable/src/filter_composing_condition.php#L50) (the result of `unpack` is an array).
This was caught by static analysis. I believe these methods should be widened to also accept arrays.

chore(docs): bigtable typehint for exactMatch

---

VideoIntelligence/tests/System/V1/VideoIntelligenceServiceClientTest.php

Currently `VideoIntelligence/tests/System/V1/VideoIntelligenceServiceClientTest.php` fails because it has no permissions to the test resource (a video). With this change, the test resource link is changed.
1. Changing test resource link.
2. Style fix.
```
google-cloud-php/VideoIntelligence % vendor/bin/phpunit -c phpunit-system.xml.dist           
..R                                                                 3 / 3 (100%)
Time: 45.24 seconds, Memory: 8.00 MB
There was 1 risky test:
1) Google\Cloud\VideoIntelligence\Tests\System\V1\VideoIntelligenceServiceSmokeTest::annotateVideoTest
This test did not perform any assertions
/Users/vishwarajanand/github/google-cloud-php/VideoIntelligence/tests/System/V1/VideoIntelligenceServiceSmoke …
```

chore(VideoIntelligence): fixing test resource link

---

Spanner/tests/System/BackupTest.php

Currently system tests are failing due to use of wrong expected exceptions and lack of having a backup before performing a restore.
1. Migrate from `InvalidArgumentException` to `BadRequestException` in affected tests.
2. Add test dependency of `testCreateBackup` into `testRestoreToNewDatabase`.
```
google-cloud-php/Spanner % XDEBUG_MODE=debug vendor/bin/phpunit -c phpunit-system.xml.dist tests/System/BackupTest.php --filter="InvalidArgument"      
..                                                                  2 / 2 (100%)
Time: 4.94 minutes, Memory: 10.00 MB
OK (2 tests, 6 assertions)
google-cloud-php/Spanner %
```
Note: This wont fix all Spanner-> Backup tests, but will reduce failures count.
ref: …

fix(Spanner): Spanner test fixes

---

BigQuery/tests/System/ManageTablesTest.php
Storage/tests/System/RequesterPaysTest.php

Currently system tests are failing due to use of wrong keys which no longer exist. 
Move from `GOOGLE_CLOUD_PHP_WHITELIST_TESTS_KEY_PATH ` keys to `GOOGLE_CLOUD_PHP_FIRESTORE_TESTS_KEY_PATH`
```
google-cloud-php/BigQuery % 
google-cloud-php/BigQuery % vendor/bin/phpunit -c phpunit-system.xml.dist --filter="testCreatesExternalTable"
.                                                                   1 / 1 (100%)
Time: 12.09 seconds, Memory: 12.00 MB
OK (1 test, 1 assertion)
google-cloud-php/BigQuery % ../Storage
google-cloud-php/Storage % vendor/bin/phpunit -c phpunit-system.xml.dist --filter="RequesterPaysTest"        
............................................................... …
```

chore: tests should use correct keys

---

dev/src/DocFx/Node/DocblockTrait.php
dev/src/DocFx/Node/ParameterNode.php
dev/tests/Unit/DocFx/NodeTest.php
dev/tests/fixtures/docfx/V1.ImageAnnotatorClient.yml
dev/tests/fixtures/phpdoc/nestedparams.xml

- remove newline for snippet annotations
- fix nested param parsing with extra whitespace

docs: misc docfx fixes

---

Storage/tests/System/StreamWrapper/UrlStatTest.php

Currently system tests are failing due to an incorrect assertion. 
`testIsExecutable` asserts on two variables: `fileUrl` and `dirUrl`. They look like below:
On GCS page, it creates following structure:
With this change, we are aligning our test with the actual results of [is_executable](https://www.php.net/manual/en/function.is-executable.php#refsect1-function.is-executable-returnvalues) function.
```
google-cloud-php/Storage % vendor/bin/phpunit -c phpunit-system.xml.dist --filter="UrlStatTest::testIsExecutable"
.                                                                   1 / 1 (100%)
Time: 6.23 seconds, Memory: 12.00 MB
OK (1 test, 2 assertions)
google-cloud-php/Storage %
```
ref: [b/263473669](http://b/263473669#comment6)

chore(Storage): fix UrlStatTest::testIsExecutable

---

Core/src/GrpcRequestWrapper.php
Core/tests/Unit/GrpcRequestWrapperTest.php

Core now allows adding `retryFunction` with `GrpcRequestWrapper::send`. This will be used in Spanner's `BeginTransaction` to retry for `Not_FOUND` errors with a custom pattern as followed in other languages.
[Code Pointer in TS](https://github.com/googleapis/nodejs-spanner/blob/02c6e599a7b744a5c610c8d801229c7299abb668/src/session-pool.ts#L223-L236)
A similar change is also being taken by Go, https://github.com/googleapis/google-cloud-go/pull/7163
1. Adding a `retryFunction` which takes in an Exception as argument and produces a bool to decide whether to retry or not.
2. Unit tests to validate cases such as whether `retryLimit` is still honored and follows the custom logic provided.
ref: [b/263775077#comment8](http://b/263775077#comment8)

feat(Core): add retryFunction in GrpcRequestWrapper::send

---

Datastore/src/Connection/Grpc.php
Datastore/tests/System/QueryResultPaginationTest.php

While fixing datastore query limit for values larger than 300 per https://github.com/googleapis/google-cloud-php/pull/5592, there was an unintended bug where limit is assumed to be `int`. This could break existing clients who use `string` limits.
1. Migrate a check on `limit` values in parsed query from `is_int` to `!is_array`
1. Added a new test for string limits: `testQueryPaginationWithStringLimit`
2. Tests pass on prod:
```
google-cloud-php/Datastore % vendor/bin/phpunit -c phpunit-system.xml.dist
PHPUnit 8.5.32 by Sebastian Bergmann and contributors.
................................................................. 65 / 96 ( 67%)
...............................                                   96 / 96 (100%)
Time: 2.97 minutes, Memory: 18.00 MB
OK (96 tests, 260 assertions) …
```

fix: [Datastore] query limit fails for string limit

---

.gitattributes

Remove ignoring `.repo-metadata.json` via `export-ignore` in `.gitattributes` for umbrella package `google/cloud` so this can be consumed by the developer tools team for our dashboards.

chore: remove export-ignore of repo-metadata

---

Core/src/Logger/AppEngineFlexHandler.php
Core/src/Logger/AppEngineFlexHandlerV2.php
Core/src/Logger/AppEngineFlexHandlerV3.php
Core/src/PhpArray.php
Core/src/Testing/GcTestListener.php
Core/src/Testing/Reflection/DescriptionFactory.php
Core/src/Testing/Reflection/ReflectionHandlerV4.php
Core/src/Testing/Reflection/ReflectionHandlerV5.php
Spanner/src/TransactionalReadTrait.php
Trace/src/Link.php
Trace/src/MessageEvent.php

See #5822 
Marks classes as internal which were throwing warnings. These are being fixed in a separate PR so that when we merge the breaking change detector, it will be passing.

chore: fixes for BC checker

---

PubSub/src/PubSubClient.php

Hi,
I've created a minor change in the doc block of the validateMessage method. 
This method validates messages against a schema. 
Since I was developing locally with the Pubsub emulator it took me some time before I found out that the message string is supposed to be base64 encoded. This was due to two facts; 
1. The Pubsub emulator only reports that the message is not valid. It does not tell why it is not. 
2. The doc block did not mention the message is supposed to be base64 encode. 
I hope that this change will save time for other developers.

docs: [PubSub] Add clarification in validateMessage docblock

---

Spanner/src/Session/CacheSessionPool.php
Spanner/tests/System/SessionTest.php
Spanner/tests/Unit/Session/CacheSessionPoolTest.php

Potentially fixes: https://github.com/googleapis/google-cloud-php/issues/5827
1. Adds a check in `maintain()` to purge sessions older than 28d.
2. Also modifies checks in `CacheSessionPool::isSessionValid(..)`
3. Other changes necessary to retain `['creation']` param, which is set to time in seconds when session was created and only used to check for expiration.
4. Relevant additions to system and unit tests
Both UT and System tests are passing in prod.

feat:[Spanner] CacheSessionPool::maintain deletes sessions older than 28d

---

Core/src/Exception/AbortedException.php
Core/src/Exception/ServiceException.php

Move the logic of retry delay from AbortedException to it's parent ServiceException.
This unblocks https://github.com/googleapis/google-cloud-php/pull/5938.

chore(Core): move retry delay to ServiceException

---

.github/workflows/backwards-compatibility-check.yaml

When the `breaking change allowed` label is applied to a PR, instead of skipping the check entirely, just pass the test.
This allows us to still look at the errors which were thrown as part of the test, as a way to confirm (and also reliably justify) the breaking changes

chore: pass BC check instead of skipping

---

Core/src/ExponentialBackoff.php
Core/tests/Unit/ExponentialBackoffTest.php
Core/tests/Unit/RequestWrapperTest.php
Core/tests/Unit/Upload/ResumableUploaderTest.php
Storage/src/Connection/Rest.php
Storage/tests/Conformance/RetryConformanceTest.php
Storage/tests/Unit/Connection/RestTest.php

Fixed #5954 
Adding unit tests for testing Retry Invocation ID and attempt count addition to the request headers. 
> The testing for the whole system has been done and it was verfied that headers were indeed getting added to the backend by packet sniffing in the emulator.
> Resumable Uploading and Custom Retry Strategy features are tested in the Conformance testing thus adding unit tests for them seems unnecessary as the changes are minimial and the process of these features are more related to how the whole system works.

feat(Storage): Adding unit tests for GCS Retry

---

Datastore/composer.json
Firestore/composer.json

alternative to https://github.com/googleapis/google-cloud-php/pull/6031 and https://github.com/googleapis/google-cloud-php/pull/6032
I believe this will work, as our individual package tests are configured to use the `Core` from the same branch anyway

chore: update core version in Firestore and Datastore

---

.github/workflows/release.yml
dev/src/Command/SplitCommand.php

`composer` should run in the `dev` directory since the release script refactor

chore: fix error in deployment script

---

Debugger/src/Agent.php

fixes https://github.com/googleapis/google-cloud-php/issues/2892

fix: add capture and log strings to switch statement

---

Core/src/ExponentialBackoff.php
Core/src/RequestWrapper.php
Storage/src/Connection/Rest.php
Storage/src/StorageObject.php
Storage/tests/Unit/StorageObjectTest.php

- Removes nesting  of `retryListener` option, which is a little bit hacky
- Moves logic in `StorageObject` into `Connection/Rest`. This seems like the correct place for this logic to be
- Passes tests added in #6072 and conformance tests

chore(gcs-conformance): refactor stream so retryListener is internal

---

Core/src/Upload/AbstractUploader.php
Core/tests/Unit/RequestWrapperTest.php
Core/tests/Unit/Upload/ResumableUploaderTest.php
Storage/tests/Unit/Connection/RestTest.php
Storage/tests/Unit/Connection/RetryTraitTest.php

Addresses the overuse of  `ReflectionClass` and `ReflectionMethod` in unit testing by either 1. testing the `RetryTrait` instead of the `Rest` test directly, or 2. mocking http handlers when calling the `Rest` class.
Also, renames `retryListener` to `restRetryListener` in `AbstractUploader` (I think this was a bug)

chore(gcs-conformance): better unit testing

---

Core/tests/Unit/Report/CloudRunMetadataProviderTest.php

Replaced `Yoast\PHPUnitPolyfills\TestCases\TestCase`  to `PHPUnit\Framework\TestCase` as we now don't use PHPUnitPolyfills.

fix(Core): Fix TestCase dependency

---

Firestore/tests/Unit/AggregateQueryTest.php

Recent experiences with https://github.com/googleapis/google-cloud-php/pull/6098/ suggests that when we need to change function names, it required lot of manual churn in test code. So, removing Reflection calls for private methods.
Specifically here, the private method in question is being called by just one public function, so migrating to use `getSnapshot(..)`

chore: remove Reflection from Aggregation Query unit tests

---

Core/src/RequestWrapper.php
Core/src/Retry.php
Storage/src/Connection/Rest.php
Storage/tests/Unit/Connection/RestTest.php
Storage/tests/Unit/StorageObjectTest.php

Fixes #6122.
See issue [6122](https://github.com/googleapis/google-cloud-php/issues/6122) for more info.
This fix adds the retry header key in `Core/Retry.php` and then uses `Retry::RETRY_HEADER_KEY` in all required places.

fix(Core): Add retry header key in Core/Retry.php

---

.github/workflows/tests.yaml
BigQueryStorage/metadata/descriptor_fix.php
Bigtable/tests/Snippet/TableTest.php
Bigtable/tests/Unit/SmartRetriesTest.php
Bigtable/tests/Unit/TableTest.php

fixes https://github.com/googleapis/google-cloud-php/issues/6121
When protobuf extension is enabled, the `getMessage` method does not exist on the descriptor pool.
I have ensured this doesn't happen again by [adding a test suite](https://github.com/googleapis/google-cloud-php/pull/6131) with the protobuf extension enabled.

fix: descriptor fix when protobuf extension is loaded

---

Datastore/src/Operation.php
Datastore/tests/System/RunQueryTest.php

Potentially fixes https://github.com/googleapis/google-cloud-php/issues/5834 and adds a test for covering this scenario for future.
In REST mode, if query has zero results, it doesn't contain `entityResults`. We depend on this field for calculating the limit values since we need to paginate for every 300 results. So, if the query has a limit set, it will throw an invalid key exception.
Added a default empty array for cases when `entityResults` is not present.
1. passes on PROD:
```
google-cloud-php/Datastore % vendor/bin/phpunit -c phpunit-system.xml.dist --filter="testQueryWithEmptyResult"
PHPUnit 9.6.7 by Sebastian Bergmann and contributors.
..                                                                  2 / 2 (100%)
Time: 00:02.486, Memory: 12.00 MB
OK (2 tests, 4 assertions) …
```

fix(Datastore): query fails when no results and limit is set

---

AdvisoryNotifications/README.md
AlloyDb/README.md
ConfidentialComputing/README.md
KmsInventory/README.md
dev/src/Command/AddComponentCommand.php
dev/templates/README.md.twig
dev/tests/fixtures/component/CustomInput/README.md
dev/tests/fixtures/component/SecretManager/README.md

When published to `cloud.google.com`, the samples link is broken, as it's a relative link from the README. 
We should make these absolute so they are not broken when published to cloud.google.com
https://cloud.google.com/php/docs/reference/cloud-confidentialcomputing/latest

chore(docs): fix 404 in readme when published to cloud.google.com

---

Core/src/RequestWrapper.php
Core/src/ServiceBuilder.php

Removes `Guzzle5Handler` logic, as Guzzle 5 is no longer supported (and the auth library removed them so we are getting static analysis errors)

chore: fix phpstan for latest version of google/auth

---

Spanner/src/Result.php
Spanner/tests/Unit/ResultTest.php

Potentially fixes https://github.com/googleapis/google-cloud-php/issues/5880, where users are seeing `ServiceException` in `ExecuteStreamingSql`.  
Currently retry is performed till default 3 attempts, if each of these satisfy:
1. `resumeToken` is present
2. `ServiceException` is thrown
3. Exception code is `Grpc\STATUS_UNAVAILABLE`
Per the fixes done in other languages [Node](https://github.com/googleapis/nodejs-spanner/pull/795) and [comment](https://github.com/googleapis/google-cloud-php/issues/5880#issuecomment-1507956944) from @olavloite , it seems we should retry by below logic (point # 1 above becomes):
1. No results have been yielded _**OR**_ a `resumeToken` is present
Added UTs which mock the ServiceExceptions with/o the resumeTokens.

fix(Spanner): retry logic of ExecuteStreamingSql

---

ArtifactRegistry/.OwlBot.yaml
AssuredWorkloads/.OwlBot.yaml
BinaryAuthorization/.OwlBot.yaml
Domains/.OwlBot.yaml
GkeHub/.OwlBot.yaml
NetworkSecurity/.OwlBot.yaml
Notebooks/.OwlBot.yaml
SqlAdmin/.OwlBot.yaml
WebSecurityScanner/.OwlBot.yaml
Workflows/.OwlBot.yaml
Workflows/owlbot.py

These clients have been upgraded to use the new client surface. They are all pre-GA
see cl/530406773

chore: configure 10 clients for stable API

---

dev/src/DocFx/Node/ClassNode.php
dev/src/DocFx/Node/MethodNode.php
dev/src/DocFx/Page/Page.php
dev/tests/fixtures/docfx/NewClient/V1.Client.ImageAnnotatorClient.yml
dev/tests/fixtures/docfx/Vision/V1.BatchOperationMetadata.State.yml
dev/tests/fixtures/docfx/Vision/V1.Block.BlockType.yml
dev/tests/fixtures/docfx/Vision/V1.FaceAnnotation.Landmark.Type.yml
dev/tests/fixtures/docfx/Vision/V1.Feature.Type.yml
dev/tests/fixtures/docfx/Vision/V1.ImageAnnotatorClient.yml
dev/tests/fixtures/docfx/Vision/V1.Likelihood.yml
dev/tests/fixtures/docfx/Vision/V1.OperationMetadata.State.yml
dev/tests/fixtures/docfx/Vision/V1.ProductSearchClient.yml
dev/tests/fixtures/docfx/Vision/V1.TextAnnotation.DetectedBreak.BreakType.yml

- Order static methods to bottom and change their name to `static::methodName` for clarity
- Also orders `getOperationsClient` and `resumeOperation` to the bottom, so the RPC methods are at the top for client classes
Here is a preview of what this should look like:

feat(docs): add support for static methods

---

Vision/tests/Snippet/V1/ImageAnnotatorClientTest.php

Remove php warnings from tests
ref: [Test Log](https://fusion2.corp.google.com/ci/kokoro/prod:cloud-devrel%2Fclient-libraries%2Fphp%2Fgoogle-cloud-php%2Fcontinuous%2Fphp74/activity/4c895620-48df-48e1-8fd1-ad0d19cbed06/invocations/4c895620-48df-48e1-8fd1-ad0d19cbed06/targets/cloud-devrel%2Fclient-libraries%2Fphp%2Fgoogle-cloud-php%2Fcontinuous%2Fphp74/log)

chore: remove deprecate warnings for prophecy

---

.github/workflows/docs.yaml
.kokoro/docs/docker/Dockerfile
dev/src/DocFx/Node/ClassNode.php
dev/tests/Unit/Command/DocFxCommandTest.php
dev/tests/fixtures/docfx/NewClient/V1.Client.SecretManagerServiceClient.yml
dev/tests/fixtures/docfx/NewClient/toc.yml
dev/tests/fixtures/phpdoc/newclient.xml

fixes https://github.com/googleapis/google-cloud-php/issues/6245 by upgrading PHPDoc with changes from https://github.com/phpDocumentor/phpDocumentor/pull/3514
adds missing `Async` magic methods for new clients

feat(docs): upgrade phpdoc to latest version, add magic methods

---

Debugger/composer.json
Debugger/src/Connection/Firebase.php
Debugger/src/DebuggerClient.php
composer.json

So that this can be used once the Cloud Debugger is phased out in favour of the snapshot debugger

feat: Add support for Firebase client

---

dev/src/DocFx/Node/MethodNode.php
dev/src/DocFx/Node/XrefTrait.php
dev/tests/Unit/DocFx/NodeTest.php
dev/tests/fixtures/docfx/Vision/V1.ImageAnnotatorClient.yml

fixes https://github.com/googleapis/google-cloud-php/issues/6317
This was due to the markdown links being wrapped for this API:
https://github.com/googleapis/googleapis/blob/77c99e43177c76ae1c1edacee7b6ac4e35a42f3d/google/identity/accesscontextmanager/v1/access_context_manager.proto#L41-L51

fix(docs): newline between link markdown, see tags in parameter descriptions

---

Dlp/composer.json
dev/README.md
dev/google-cloud
dev/src/Command/ReleaseInfoCommand.php
dev/tests/Unit/Command/ComponentInfoCommandTest.php
dev/tests/Unit/Command/DocFxCommandTest.php
dev/tests/Unit/Command/ReleaseInfoCommandTest.php

Command to display information about a released tag:
```
$ ./google-cloud release-info v0.208.0 
+--------------------------+--------------------------------+---------+
| component                | id                             | version |
+--------------------------+--------------------------------+---------+
| BillingBudgets           | cloud-billing-budgets          | 1.2.0   |
| Build                    | cloud-build                    | 0.7.2   |
| Container                | cloud-container                | 1.15.0  |
| Debugger                 | cloud-debugger                 | 1.5.1   |
| Deploy                   | cloud-deploy                   | 0.8.0   |
| DiscoveryEngine          | cloud-discoveryengine          | 0.3.0   |
| PubSub                   | cloud-pubsub …
```

feat(dev): add release-info command

---

Storage/tests/System/StreamWrapper/DirectoryTest.php
Storage/tests/System/StreamWrapper/WriteTest.php

Fixing the warnings system tests throw: 
> assertFileNotExists() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertFileDoesNotExist() instead.

chore: remove assertFileNotExists

---

dev/src/NewComponent.php

Will match shortnames like 
```proto
service ConsumerProcurementService {
option (google.api.default_host) =
"cloudcommerceconsumerprocurement.googleapis.com";
}
```
instead of just when they're on a single line

fix(dev): regex match for shortname

---

ErrorReporting/src/Bootstrap.php
ErrorReporting/tests/Unit/BootstrapTest.php

Adding code to generate `context.httpRequest` as mentioned in the [docs](https://cloud.google.com/error-reporting/docs/formatting-error-messages).

feat(ErrorReporting): Generate HttpRequestContext for log context.

---

Core/composer.json
composer.json

Fix for https://github.com/advisories/GHSA-25mq-v84q-4j7r and https://github.com/advisories/GHSA-q559-8m2m-g699

fix: Bump guzzlehttp/guzzle version

---

BigQuery/src/QueryResults.php

I noticed PhpStorm gave off warnings in several places on `QueryResults`'s PhpDoc.
This PR is an attempt to fix the incorrect docs.

chore(BigQuery): phpdoc for QueryResults

---

dev/src/Command/RepoInfoCommand.php
dev/src/Command/SplitCommand.php
dev/src/GitHub.php

Makes sure when a component is released, the new github repos have:
- the `yoshi-php` team as an admin
- issues, discussion, wiki, pages, and projects disabled (since it's considered READONLY)
In order to keep the code dry, this includes moving logic that was previously in the `RepoInfoCommand` class to the `GitHub` class, and then using that object in both `SplitCommand` and `RepoInfoCommand`.

feat(dev): ensure repo settings are compliant for new repos

---

Spanner/tests/System/BackupTest.php

chore(Spanner): rename print_R to print_r

---

Storage/src/Acl.php
Storage/src/Bucket.php
Storage/src/HmacKey.php
Storage/src/Lifecycle.php
Storage/src/Notification.php
Storage/src/ObjectIterator.php
Storage/src/ObjectPageIterator.php
Storage/src/SigningHelper.php
Storage/src/StorageClient.php
Storage/src/StorageObject.php

PHPdoc links have been broken in our reference documentation (see https://cloud.google.com/php/docs/reference/cloud-storage/latest/StorageObject for instance) due to the wrong paths being used for the classes (relative instead of absolute or shortnames). 
This PR updates the `@see` tags in PHPDoc to use the proper paths.

chore(Storage): fix see tags in phpdoc

---

PubSub/src/BatchPublisher.php
PubSub/src/Message.php
PubSub/src/PubSubClient.php
PubSub/src/Schema.php
PubSub/src/Subscription.php
PubSub/src/Topic.php

See https://cloud.google.com/php/docs/reference/cloud-pubsub/latest/PubSubClient
The documentation on many of these docs pages contain wrong/broken class paths and links due to improperly formatted `@see` tags.

chore(docs): fix see tags in PubSub phpdoc

---

dev/src/DocFx/Node/FencedCodeBlockTrait.php
dev/tests/Unit/DocFx/NodeTest.php
dev/tests/fixtures/docfx/Vision/V1.ImageAnnotatorClient.yml

See the broken formatting in our [PubSubClient reference docs](https://cloud.google.com/php/docs/reference/cloud-pubsub/latest/PubSubClient)
The top of the page is completely broken because the regex matching doesn't work for multiple fenced codeblocks in a single description. 
This PR fixes the RegEx and adds tests to ensure it's now parsed as expected.

fix(dev): mutliple code blocks in phpdoc

---

dev/src/DocFx/Node/MethodNode.php
dev/tests/Unit/DocFx/NodeTest.php

Small improvement on #6628 
Multiple `@see` tags look off in the docs with the way they're currently rendered (for example, [StorageObject::downloadAsString](https://cloud.google.com/php/docs/reference/cloud-storage/latest/StorageObject#_Google_Cloud_Storage_StorageObject__downloadAsString__)) because sometimes the link text terminates with a period, which looks odd with the comma:
<kbd>
</kbd>
This PR changes See tags into an unordered list, so it will render in our public docs like this instead:
<kbd>
</kbd>
Todo:

chore(docs): use unordered lists for see tags

---

composer.json

See Piper Rev-Id: 561043692
GameServer protos have been removed and are no longer being updated / maintained

chore: mark google/cloud-game-servers abandoned

---

.github/workflows/spanner-emulator-system-tests.yaml

https://github.com/googleapis/google-cloud-php/pull/6726 uncovers lack of required env vars in Spanner system tests.
This is causing failures [in other PRs](https://github.com/googleapis/google-cloud-php/actions/runs/6707182781/job/18225126264?pr=6708)

chore: add required vars to Spanner system test

---

Logging/src/LoggingClient.php

Array_merge with a wrong key, the used key was projectIds instead of resourceNames.

fix: Wrong key on array_merge on fetch logs entries

---

phpunit-system.xml.dist

Currently CI tests are broken and only a message is produced by phpunit command, `Test directory "./tests/System" not found`. [ref](https://source.cloud.google.com/results/invocations/ae0f498a-7d40-4af5-995d-7c974acf2614/log)
This PR will atleast get the phpunit to execute the tests.

chore: fix ci tests

---

Core/src/Testing/TestHelpers.php

Fix system tests that seem to be broken, as per the [log](https://btx-internal.corp.google.com/invocations/a04346c8-d8a1-4a29-928a-5cc6ec23b504/targets/cloud-devrel%2Fclient-libraries%2Fphp%2Fgoogle-cloud-php%2Fcontinuous%2Fphp74;config=default/log)
Missing env var failures in the log:
```
20) Google\Cloud\Debugger\Tests\System\E2ETest::testWithFullPath
Set the GOOGLE_PROJECT_ID environment variable
```

chore: fix System tests

---

Storage/src/Bucket.php
Storage/src/Connection/Rest.php
Storage/src/StorageClient.php
Storage/src/StorageObject.php
Storage/tests/System/ManageObjectsTest.php

This adds support for [object retention lock](https://cloud.google.com/storage/docs/object-lock)
Fixes https://github.com/googleapis/google-cloud-php/issues/6741
PRD: [go/gcs-object-retention-client-request](https://goto.google.com/gcs-object-retention-client-request)
System tests pass in my local which were run on an allowlisted project:
```
➜  Storage git:(main) ✗ vendor/bin/phpunit  -c phpunit-system.xml.dist --filter="ManageObjectsTest::testObjectRetentionLock"
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.
.                                                                   1 / 1 (100%)
Time: 00:04.678, Memory: 14.00 MB
OK (1 test, 3 assertions)
➜  Storage git:(main) ✗
```

feat(Storage): support object retention lock

---

Storage/src/Bucket.php
Storage/src/StorageObject.php

The `retentionExpirationTime` is a read-only property on the Object that comes back from the API, so there is no parameter to expose to the users in the function

chore: remove retentionExpirationTime

---

PubSub/composer.json
PubSub/tests/System/SchemaTest.php
composer.json

In https://packagist.org/packages/rg/avro-php, we are seeing deprecation warnings. Fixing them:
```
➜  PubSub git:(chore_spanner_concurrent_tests) ✗ vendor/bin/phpunit  -c phpunit-syst
em.xml.dist --filter="SchemaTest::testPublishWithAvroSchemaBinary" 
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.
..                                                                  2 / 2 (100%)
Time: 00:27.959, Memory: 12.00 MB
OK (2 tests, 2 assertions)
➜  PubSub git:(chore_spanner_concurrent_tests) ✗
```

fix: removed abandoned package from composer

---

.github/workflows/spanner-emulator-system-tests.yaml
Spanner/tests/System/SpannerTestCase.php
Spanner/tests/System/TransactionTest.php
Spanner/tests/System/pcntl/AbortedErrorCausesRetry.php
Spanner/tests/System/pcntl/ConcurrentTransactionsIncrementValueWithExecute.php
Spanner/tests/System/pcntl/ConcurrentTransactionsIncrementValueWithRead.php
Spanner/tests/System/pcntl/forked-process-test.php

This is an attempt to fix the concurrent tests for Spanner.
There are 3 tests dependent on `pcntl` and they assert records values after transaction is committed in concurrent processes.
We need to add `grpc.enable_fork_support=1` in order to enable `pcntl_waitpid` function to exit, else it keeps on waiting forever. The waiting logic is also changed, instead of using a blocking waiting, we also check status of child process and then wait for a max number of retries.
Also, Spanner emulator currently doesn't support parallel transactions, and it randomly kills a transaction if attempted in parallel, leading to more number of transaction iterations than expected in the test. Hence, the tests assert for iterations has been changed to `assertGreaterThan` from previously `assertEquals`.

chore: fix spanner concurrent transaction tests

---

Core/composer.json

fixes https://github.com/googleapis/google-auth-library-php/issues/504
We are now using the `FetchAuthTokenCache::getFetcher` function in `google/auth:v1.25.0`, so we need to ensure the minimum version is set to `1.25.0`

fix(Core): update minimum google/auth version

---

BigQuery/tests/Unit/Connection/RestTest.php
Core/src/RestTrait.php
Core/tests/Unit/RequestWrapperTest.php
Core/tests/Unit/RestTraitTest.php
PubSub/tests/Unit/Connection/GrpcTest.php
PubSub/tests/Unit/Connection/RestTest.php
Storage/tests/Unit/Connection/RestTest.php

Added tests for handwritten classes in BQ / Storage / PubSub for TPC.
I have manually tested that the TPC works for environment when I used `PubSubClient`, `StorageClient` and `BigQueryClient`. I initialized their clients (provided `universeDomain` config in addition to the `universe_domain` present in service account json key) and called methods to `topics`, `buckets` and `datasets` respectively.

fix: adding unit tests for connection classes

---

Quotas/README.md
Quotas/composer.json

I missed this, sorry - for `google/cloud-***` repos, we use the repo format `googleapis/google-cloud-php-***`

chore: rename quotas repo

---

AnalyticsData/.OwlBot.yaml

The AnalyticsData team has brought it to our attention that the `v1alpha` library has not been receiving updates. This is because when we moved to OwlBot two years ago, `v1alpha` was not added to the regex match of the copy configuration.

chore: [AnalyticsData] update owlbot to include v1alpha

---

.gitattributes

Similar to https://github.com/googleapis/google-cloud-php/pull/5837 - we can ship samples in umbrella package since this repo isn't recommended for production anyway
see b/262896693

chore: do not export-ignore samples in umbrella package

---

.gitattributes

The `CHANGELOG.md` is getting big (1.4M), so we should `export-ignore` it so that it doesn't get installed by composer.

chore: export-ignore changelog

---

.github/workflows/backwards-compatibility-check.yaml

See [this failing workflow run](https://github.com/googleapis/google-cloud-php/actions/runs/7643586486/job/20825970498) and [this passing workflow run](https://github.com/googleapis/google-cloud-php/actions/runs/7643817664/job/20826730963) for an example of how these work:
**Failing Workflow Run**
**Passing Workflow Run**
The workflow checks the changed `VERSION` file for a major release, and if it detects one, fails if the component is not contained in a `MAJOR_VERSION_ALLOWED=` tag in the PR body, e.g:
```
MAJOR_VERSION_ALLOWED=Workflows,AnalyticsData
```

feat(ci): check for major versions and use MAJOR_VERSION_ALLOWED= to release them

---

.github/run-package-tests.sh
.github/workflows/tests.yaml

This improves the "Package Tests - Prefer Lowest" tests by
1. Allowing PRs with dependencies on local packages to install from packagist when possible.
2. Allow release PRs to strictly install the package about to be released using the `--prefer-lowest-strict` flag.
This allows PRs to define their dependencies for future releases, while still testing that the lowest deps are defined correctly.

chore(ci): improve prefer lowest tests

---

.kokoro/docs/publish.sh
dev/src/Command/ReleaseInfoCommand.php
dev/src/Command/RepoInfoCommand.php
dev/src/Component.php
dev/src/ComponentPackage.php
dev/src/GitHub.php
dev/tests/Unit/Command/ReleaseInfoCommandTest.php
dev/tests/Unit/GitHubTest.php

**Primary changes**
- adds `from` option to the `release-info` command (previously, the "tag" parameter was required). This returns info for all releases since that date.
- adds `sql` to the `format` option, which outputs the WHERE clause in SQL for the given releases
```sh
dev/google-cloud release-info --from="-6 months" --format sql 
```
**Other misc changes**
- added logic to determine "API Shortname" for non-GAPICs
- if neither "tag" nor "from" is supplied , defaults to latest release
- allows `0` to `results-per-page` in `repo-info` command, which means no pagination
- the `GitHub::getChangelog` method now returns `false` if the tag doesn't exist

feat(dev): latest version query

---

Storage/src/Bucket.php
Storage/tests/Unit/BucketTest.php

Adds support for IncludeFoldersAsPrefixes to object listing, which allows managed folders to be included in the results.
Create / List / Delete / Get calls to be handled separately.
Fixes: https://github.com/googleapis/google-cloud-php/issues/7039

feat(storage): support IncludeFoldersAsPrefixes

---

Core/composer.json
Core/src/InsecureCredentialsWrapper.php
composer.json

BREAKING_CHANGE_REASON=The actual return type of `InsecureCredentialsWrapper:getAuthorizationHeaderCallback()` is `callable` in `ApiCore/CredentialsWrapper`. This PR fixes this by setting the return type of `InsecureCredentialsWrapper:getAuthorizationHeaderCallback()` as callable. So, this PR acknowledge the breaking changes, and they shouldn't have any adverse affects on the users.

chore: Deprecate Google\Cloud\Core\InsecureCredentialsWrapper

---

Core/src/Upload/ResumableUploader.php
Core/tests/Unit/Upload/ResumableUploaderTest.php

When querying the last uploaded bytes, `ResumableUploader` should pass the `total_bytes` to be uploaded in HTTP PUT call. [Guidance here in point # 4](http://go/scotty-http-protocols#common-base-protocol-resumable-http-puts)
Also, fixes tests which were not exactly testing that uploads do happen on resume.
Addresses (but not exactly fixes #https://github.com/googleapis/google-cloud-php/issues/7088

fix(Core): pass total_bytes in ResumableUploader

---

Storage/tests/Snippet/HmacKeyTest.php

Fixes warnings in snippet tests, [here](https://github.com/googleapis/google-cloud-php/actions/runs/8279003211/job/22652518332?pr=7144#step:4:1942).

chore(Storage): fixing risky tests via adding assertions

---

Storage/tests/System/IamTest.php

`$policy['bindings']` can have shuffled keys in each element. 
The `assertContains` method in PHPUnit uses a loose comparison (==) to check if an array contains provided value but the order of keys in the arrays matters.
`in_array` also uses a loose comparison (==), but it doesn't care about the order of keys in arrays.
[b/333035372](http://b/333035372)

chore(Storage): fix IAM system tests

---

dev/tests/Unit/Command/AddComponentCommandTest.php
dev/tests/fixtures/component/SecretManager/README.md

The inclusion of a Documentation URI in the `google/cloud/secretmanager/v1/secretmanager_v1.yaml` file for the `secretmanager` component now breaks tests in the `dev`. Previously, during the AddComponent command, the absence of a Documentation URI would trigger a prompt, allowing the test to provide it.  This PR updates tests to accommodate the change, as the command now automatically obtains the Documentation URI from the YAML file.
Refer: https://github.com/googleapis/googleapis/commit/034570432b14b429c5f597701132b6d9ceb553a2#diff-4dfeb801ec53963f0695de0ee5856641691c50d1b2aa7f8a6159ab26978e4fb3R46

chore(tests): Fix AddComponentCommandTest

---

AppsChat/.repo-metadata.json

The docs URL for `google/apps-chat` is incorrect here: https://cloud.google.com/php/docs/reference

chore: fix docs url for google/apps-chat

---

Spanner/src/Connection/Grpc.php

This was changed to strings in the `1.76.0` release of Spanner. The other fields in the stats object like inside `queryPlan` were already returned as a string so we don't need to cast them.
But these 2 properties, `rowCountLowerBound` and `rowCountExact` are now casted to int so that we preserve the speed boost we get and maintain data integrity within the `ResultStats` object.
Fixes #7279

fix(Spanner): Cast some fields in the ResultStats object to int

---

Storage/src/StorageClient.php
Storage/tests/System/ManageBucketsTest.php

Fixes https://github.com/googleapis/google-cloud-php/issues/7277
```
➜  Storage git:(main) ✗ vendor/bin/phpunit -c phpunit-system.xml.dist --filter="::testCreateBucketsWithHnsConfigs"
PHPUnit 9.6.19 by Sebastian Bergmann and contributors.
...                                                                 3 / 3 (100%)
Time: 00:09.480, Memory: 14.00 MB
OK (3 tests, 12 assertions)
➜  Storage git:(feat_storage_hns1) ✗ 
```

feat(Storage): Enable hierarchical namespace

---

Spanner/src/Connection/Grpc.php

Inside the connection class's `Serializer` instance currently we are setting some fields inside the `metadata` key even when no metadata is returned in the response. This is causing a problem in the [Result class](https://github.com/googleapis/google-cloud-php/issues/7311).
This should fix that issue.

fix: Only override metadata for PartialResultSet when it is present in the response

---

PubSub/src/PubSubClient.php

BREAKING_CHANGE_REASON=changing the VERSION constant is not considered breaking in this library

fix: pubsub version constant

---

dev/src/Command/ComponentInfoCommand.php
dev/src/ComponentPackage.php
dev/tests/Unit/Command/ComponentInfoCommandTest.php

Adds `filter` to `dev/google-cloud component-info` command to better help filter out certain types of components
For example, the following command
```sh
./dev/google-cloud component-info --filter 'release_level=preview,migration_mode~=NEW_SURFACE_ONLY,migration_mode!~=MIGRATING'
```
Will return something like this:
```
+-----------------------------+--------------------------------------------+-----------------+------------------------+---------------+----------------------------+-----------------------------------------------+----------------------------------+
| Component Name              | Package Name                               | Package Version | API Version            | Release Level | Migration Mode             | Proto Path                                    | API Shortname …
```

feat(dev): add filter and sort to component-info command

---

.repo-metadata-full.json

This API should have been marked stable already (and has been for some time)

chore: mark AccessContextManager stable

---

dev/templates/owlbot.py.twig
dev/tests/fixtures/component/CustomInput/owlbot.py
dev/tests/fixtures/component/SecretManager/owlbot.py

We no longer need to exclude the underscored protobuf files, as these have been removed from generation.

chore(dev): remove unneeded copy_excludes

---

Bigtable/src/BigtableClient.php
Bigtable/src/ChunkFormatter.php
Bigtable/src/ResumableStream.php
Bigtable/src/Table.php
Bigtable/tests/Unit/SmartRetriesTest.php
Core/src/InsecureCredentialsWrapper.php

This PR adds two visibility features to the Bigtable client in `v0.221.0` (which will apply to `google/cloud-bigtable: 1.28.3`)
If a retryable exception is thrown, and the Bigtable client retries the call, all additional attempts will contain the header/metadata `bigtable-attempt`, which will start with "1" for the first retry and increment from there
By setting a [PSR3-compatible](https://www.php-fig.org/psr/psr-3/) logging client, the `BigtableClient` class will log retryable or non-retryable exceptions which occur during the `readRows` stream
```php
// create any PSR3-compatible logging client
$logger = new Monolog\Logger();
// pass it in when creating the bigtable client
$bigtable = new Google\Cloud\Bigtable\BigtableClient(['logger' => $logger]);
// Or pass it in when calling …
```

feat(Bigtable): add attempts headers on retry and exception logging

---

Storage/src/Connection/Rest.php
Storage/tests/Unit/StorageObjectTest.php

Attempts to address https://github.com/googleapis/google-cloud-php/issues/7473 by not copying streams by default. This was copying the full streams even when the stream was only supposed to be opened. 
The new code copies the stream only if retries took place. Admittedly this also isn't optimal behavior - it would be better to return a new stream which prepends any previous streams (without seeking through the new stream). We should investigate the Stream classes being used to see if it's possible to do something like this.

fix(Storage): ensure streams arent copied by default

---

dev/src/Command/ComponentInfoCommand.php
dev/src/Command/SplitCommand.php
dev/src/Component.php
dev/tests/Unit/Command/ComponentInfoCommandTest.php

Adds the following features to the dev commands:
1. Allows "all" keyword to `--fields` option to show all fields (the default is to only show a few, for readability)
2. Allows multiple "component" values supplied, e.g. `-c Storage -c BigQuery` so that multiple specific components can be easily viewed
3. Ensures new repos are `public` when modifying their settings.
4. Allow CSV output to stdout
Potential TODO: allow multiple `--filter` options which are a logical OR between them (similar to components)

feat(dev): add "all" keyword and multiple components to component-info command

---

.github/emulator/start-emulator.sh
Core/src/EmulatorTrait.php
Core/tests/Unit/EmulatorTraitTest.php

This fixes https://github.com/googleapis/google-cloud-php/issues/7187
Unfortunately using the PubSub emulator is still not entirely straightforward with REST: the `https` schema is hardcoded in `Google\ApiCore\RequestBuilder::buildUri()`, probably for very good reason!
I have managed to get it to work by supplying a modified `httpHandler`:
```php
// double the # of characters before truncation by default
$bodySummarizer = new BodySummarizer(240);
$stack = HandlerStack::create();
$stack->remove('http_errors');
$stack->unshift(Middleware::httpErrors($bodySummarizer), 'http_errors');
$stack->push(Middleware::mapRequest(static function (RequestInterface $request) {
$uri = $request->getUri();
return $request->withUri($uri->withScheme('http')); // convert https -> http for emulator
}));
$client …
```

fix: [PubSub] Prevent fatal error when using emulator without grpc

---

.github/workflows/tests.yaml
CommonProtos/composer.json

Reverts googleapis/google-cloud-php#7532, as https://github.com/grpc/grpc/issues/37222 is now fixed. This will make our individual package tests run about 20 minutes faster
Additionally, add "version" to `CommonProtos`, as this is required for the same reason that it's required in `LongRunning` (it ends up being a dependency of a dependency in testing)

chore: revert pin grpc to fix failing tests, add version to CommonProtos

---

dev/src/DocFx/Node/XrefTrait.php
dev/tests/Unit/DocFx/NodeTest.php

This fixes ~1500 broken references across all our reference documentation
When running `.kokoro/docs/publish.sh` with the `DEBUG` flag on `main`, we get 2618 broken links.
The same command from this PR shows 964 broken links, for a total of **1654 fixed links**!
It should be mentioned that **422** of the remaining broken links are _empty_ (meaning the protos do not reference anything in the link). The rest seem to mostly be errors in the protos, but will require more investigation for the FixIt.

fix(docs): fixes for reference documentation links

---

AutoMl/MIGRATING.md
BigQueryDataTransfer/MIGRATING.md
Dataproc/MIGRATING.md
Dlp/MIGRATING.md
DocumentAi/MIGRATING.md
Functions/MIGRATING.md
Kms/MIGRATING.md
OsConfig/MIGRATING.md
Retail/MIGRATING.md
Scheduler/MIGRATING.md
StorageTransfer/MIGRATING.md
Talent/MIGRATING.md
VideoIntelligence/MIGRATING.md
WebRisk/MIGRATING.md

BEGIN_VERISON_OVERRIDE
AutoMl: 2.0.0
BigQueryDataTransfer: 2.0.0
Dataproc: 2.0.0
Dlp: 2.0.0
DocumentAi: 2.0.0
Functions: 2.0.0
Kms: 2.0.0
OsConfig: 2.0.0
Retail: 2.0.0
Scheduler: 2.0.0
StorageTransfer: 2.0.0
Talent: 2.0.0
VideoIntelligence: 2.0.0
WebRisk: 2.0.0
END_VERSION_OVERRIDE

chore: add MIGRATING.md for recently promoted 2.0 clients

---

Bigtable/phpunit-conformance.xml.dist
Bigtable/src/ResumableStream.php
Bigtable/tests/Conformance/ReadRowsTest.php
Bigtable/tests/Unit/ResumableStreamTest.php

... also, ensure the exponential delay is reset when we receive a successful row

feat: add exponential backoff to ResumableStream

---

Bigtable/src/ResumableStream.php
Bigtable/tests/Unit/SmartRetriesTest.php

In `Table`, the `retryFunction` can retry even when an exception is not thrown (if one of the responses has a non-OK status code, see [here](https://github.com/googleapis/google-cloud-php/blob/21a154bc73ea8f04b12250f1f48b2b17c4329c43/Bigtable/src/Table.php#L549)). Because of this, we need to ensure attempts are incremented even when there is no exception.
Also removes unnecessary check for `$this->retryFunction`

fix: ensure attempts increment without exception

---

.github/workflows/backwards-compatibility-checks.yaml
Redis/tests/System/V1/CloudRedisClientTest.php
Storage/tests/System/ManageAclTest.php
Storage/tests/System/StorageTestCase.php
Storage/tests/System/UniverseDomainTest.php
dev/src/Command/ComponentInfoCommand.php

- fix logic in "Conventional Commit Check" action
- fix typo in Redis System Test
- mark Storage `ManageAcl` tests as flakey
- refactor Storage UniverseDomain tests
- adds test for Storage Bucket Delete
- adds "starts with" filter to dev component

chore: misc system test fixes and cleanup

---

.github/workflows/backwards-compatibility-checks.yaml

See https://github.com/googleapis/google-cloud-php/actions/runs/11251717947/job/31283357805#step:5:39
Will fix the argument to the backwards compatibility checker from a value such as `merge/7728` to `bshaffer-patch-1`

fix(ci): ref in backwards-compatibility-checks

---

.github/workflows/release.yml

Reworks the compile splitsh step on the release action to clone the lite version, build it and have it ready to pass to the final step of the splitting.

Chore: Rework the compile splitsh command

---

dev/src/DocFx/Node/XrefTrait.php
dev/tests/Unit/DocFx/NodeTest.php
dev/tests/fixtures/docfx/NewClient/V1.Client.SecretManagerServiceClient.yml
dev/tests/fixtures/docfx/Vision/V1.Client.ImageAnnotatorClient.yml
dev/tests/fixtures/docfx/Vision/V1.Client.ProductSearchClient.yml

Add external links for Guzzle's `PromiseInterface` for a more descriptive documentation on the `async` magic methods.
related:
https://github.com/googleapis/gapic-generator-php/pull/732
Bug:
b/372535203

feat: Add support for external links for the Guzzle's Promise Interface

---

dev/src/DocFx/Node/XrefTrait.php
dev/tests/Unit/DocFx/NodeTest.php

Escapes the `<` and '>' character for the HTML generation in the docs.

fix: Escape the < character for generic types

---

Spanner/src/Connection/Grpc.php
Spanner/src/Database.php
Spanner/src/Operation.php
Spanner/src/Transaction.php
Spanner/src/TransactionConfigurationTrait.php
Spanner/tests/Unit/DatabaseTest.php
Spanner/tests/Unit/OperationTest.php
Spanner/tests/Unit/TransactionTest.php

Ensures `excludeTxnFromChangeStreams` is configurable for the following methods, and adds tests:
- Database::runTransaction
- Database::executePartitionedUpdate
- Operation::transaction
- Operation::execute
- Operation::executeUpdate
- Database::batchUpdate
Additionally, ensures `excludeTxnFromChangeStreams` is NOT configurable for the following methods, and adds tests:
- Transaction::executeUpdate
```php
$database->runTransaction(function (Transaction $t) use ($sql) {
// Run a query
}, [
'transactionOptions' => ['excludeTxnFromChangeStreams' => true]
]);
```
```php
$database->executePartitionedUpdate($sql, [
'transactionOptions' => ['excludeTxnFromChangeStreams' => true]
]);
```
```php
$transaction = $operation->transaction($this->session, [
'transactionOptions' => …
```

feat: support excludeTxnFromChangeStreams option

---

AUTHENTICATION.md
README.md

Update the documentation for the AUTHENTICATION.md file with a sample of how to authenticate a client.
b/313672715

docs: Authentication update

---

dev/src/Command/ComponentInfoCommand.php
dev/src/Component.php

Small change to the `./dev/google-cloud component-info` command: Adds field `library_type` to list of possible output fields.  Possible options are `GAPIC_AUTO`, `GAPIC_COMBO`, `GAPIC_MANUAL` and `CORE`
```
$ $ ./dev/google-cloud component-info --filter 'component_name~=Storage' --fields '+library_type'
+-----------------+-------------------------------+-----------------+-------------+---------------+-----------------+--------------+
| Component Name  | Package Name                  | Package Version | API Version | Release Level | API Shortname   | Library Type |
+-----------------+-------------------------------+-----------------+-------------+---------------+-----------------+--------------+
| BigQueryStorage | google/cloud-bigquery-storage | 2.1.1           | V1          | stable …
```

feat(dev): add library_type component field

---

Core/src/ServiceBuilder.php

With the coming V2 changes, many of these clients are getting removed or renamed. Best to encourage users to remove use of this class altogether by marking it as deprecated.

chore: deprecate ServiceBuilder

---

Bigtable/src/Table.php
Bigtable/tests/Unit/TableTest.php

fixes issue found when implementing #7959 
if a user sets `appProfileId` in `Table` class constructor, this option is not passed to the requests as expected. Instead, the user has to pass `appProfileId` in for each call.
This change fixed the issue and ensures that any `appProfileId` passed into the `Table` constructor will be propagated to each RPC call. This still allows a call-time `appProfileId` to be passed in as well, which takes precedence.

fix(Bigtable): ensure appProfileId is sent in requests when set in options

---

Bigtable/src/BigtableClient.php

fixes https://github.com/googleapis/google-cloud-php/issues/8018

fix: add SERVICE_NAME constant to bigtable client

---

.github/workflows/system-tests-pubsub-emulator.yaml
PubSub/tests/System/PubSubTestCase.php
PubSub/tests/System/PublishAndPullTest.php

ensure PubSub emulator tests are run for REST
This was not being done in the past because the emulator didn't support it, but now it does!

chore(tests): [PubSub] run rest tests against the emulator

---

Debugger/README.md
Debugger/src/Agent.php
Debugger/src/AliasContext.php
Debugger/src/Breakpoint.php
Debugger/src/BreakpointStorage/FileBreakpointStorage.php
Debugger/src/BreakpointStorage/SysvBreakpointStorage.php
Debugger/src/BufferFullException.php
Debugger/src/CliDaemon.php
Debugger/src/CloudRepoSourceContext.php
Debugger/src/CloudWorkspaceId.php
Debugger/src/CloudWorkspaceSourceContext.php
Debugger/src/Connection/Firebase.php
Debugger/src/Connection/Grpc.php
Debugger/src/Connection/Rest.php
Debugger/src/Daemon.php
Debugger/src/Debuggee.php
Debugger/src/DebuggerClient.php
Debugger/src/ExtendedSourceContext.php
Debugger/src/FormatMessage.php
Debugger/src/GerritSourceContext.php
Debugger/src/GitSourceContext.php
Debugger/src/MatchingFileIterator.php
Debugger/src/ProjectRepoId.php
Debugger/src/RepoId.php
Debugger/src/SourceLocation.php
Debugger/src/SourceLocationResolver.php
Debugger/src/StackFrame.php
Debugger/src/StatusMessage.php
Debugger/src/Variable.php
Debugger/src/VariableTable.php

Addresses https://github.com/googleapis/google-cloud-php/issues/6153 almost two years too late

fix: mark Debugger deprecated

---

dev/src/Command/DocFxCommand.php
dev/tests/fixtures/docfx/ProductNeutralGuides/toc.yml

Cloud RAD does NOT like the name `readme` in the URL, apparently - this 404s in our help docs

fix(docs): avoid readme keyword in URL

---

.github/workflows/conformance-tests-storage-emulator.yaml

This is a LSC run by http://go/ghss to upgrade all depreacated ubuntu-20.04 runners to ubuntu-24.04.
On April 1, 2025, GitHub will stop supporting ubuntu-20.04 runners and workflows configured with this label will cease to run.  This PR is an attempt to save you work by doing the upgrade for you.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it and deal with the problem yourselves.
More context and feedback: http://b/406537467

Update runners to ubuntu-24.04 from deprecated ubuntu-20.04 label

---

phpstan.neon.dist

The [latest version of PHPStan](https://github.com/phpstan/phpstan/releases/tag/2.1.13) breaks our static analysis tests for the "bleeding edge" configuration.  To fix this, remove the "bleeding edge" from our configuration.
Additionally, uses the `identifer` instead of message matching for `array.duplicateKey` and `new.static`, and clean up the formatting/whitespace to be more readable.

fix(cs): remove bleeding edge from phpstan, cleanup config

---

GRPC.md
dev/src/Command/DocFxCommand.php
dev/tests/fixtures/docfx/ProductNeutralGuides/grpc.md
dev/tests/fixtures/docfx/ProductNeutralGuides/toc.yml

fixes https://github.com/googleapis/google-cloud-php/issues/8075
Adds guide for installing GRPC, to be deployed to "product neutral guides"

docs: add GRPC guide

---

.github/workflows/owlbot-checks.yaml
.github/workflows/release-checks.yaml

fixes https://github.com/googleapis/google-cloud-php/issues/8106
Also organizes "Backwards Compatibility Checks" better by separating it into "Release Checks" and "OwlBot Checks", which is more accurate

feat(ci): add check for owl-bot-staging dir

---

BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json

Results of running [breaking_changes_test.py](https://source.corp.google.com/piper///depot/google3/experimental/users/shollyman/discovery_testing/breaking_change_test.py)
```
[ RUN      ] BreakingChangeDetector.test_breaking_changes_bigquery_v2
I0609 14:57:07.882179 140084443844032 breaking_change_test.py:38] all differences:
I0609 14:57:07.882470 140084443844032 breaking_change_test.py:40] Difference(endpoints: DifferenceType.CHANGED)
I0609 14:57:07.882587 140084443844032 breaking_change_test.py:40] Difference(resources.datasets.methods.get.parameters.datasetView.enumDescriptions: DifferenceType.CHANGED)
I0609 14:57:07.882647 140084443844032 breaking_change_test.py:40] Difference(resources.routines.methods.testIamPermissions: DifferenceType.ADDED)
I0609 14:57:07.882694 140084443844032 …
```

feat(BigQuery): Upgrade Discovery JSON file to latest revision 20250511

---

Core/src/GrpcTrait.php
Datastore/composer.json
Datastore/src/Connection/Grpc.php
Datastore/src/Connection/Rest.php
Datastore/src/Connection/ServiceDefinition/datastore-v1.json
Datastore/src/DatastoreClient.php
Datastore/src/EntityIterator.php
Datastore/src/EntityPageIterator.php
Datastore/src/Operation.php
Datastore/src/Query/AggregationQueryResult.php
Datastore/tests/System/AggregationQueryTest.php
Datastore/tests/System/RunQueryTest.php
Datastore/tests/Unit/DatastoreClientTest.php
Datastore/tests/Unit/EntityIteratorTest.php

This PR adds support for the `ExplainOptions` message type being passed to the `runQuery` and `runAggregationQuery` methods:
```php
use Google\Cloud\Datastore\DatastoreClient;
use Google\Cloud\Datastore\V1\ExplainOptions;
$datastore = new DatastoreClient([
'projectId' => <project id>,
'databaseId' => <database id>
]);
$query = $datastore->query();
$query->kind('Task');
$query->filter('done', '=', false);
$explainOptions = new ExplainOptions();
$explainOptions->setAnalyze(true);
$response = $datastore->runQuery($query, [
'explainOptions' => $explainOptions
])
var_dump ($response->getExplainMetrics()) //This contains all the explain metrics, se the ExplainMetrics proto.
```
b/364933728

feat: Add support for the ExplainOptions

---

Firestore/src/AggregateQuery.php
Firestore/src/AggregateQuerySnapshot.php
Firestore/src/Connection/Grpc.php
Firestore/src/Query.php
Firestore/src/QuerySnapshot.php
Firestore/tests/System/AggregateQueryTest.php
Firestore/tests/System/GetAllDocumentsTest.php
Firestore/tests/System/QueryTest.php
Firestore/tests/Unit/QueryTest.php

This adds support for the `explainOptions` class providing some profiling tools.
Example:
```
$snapshot = $firestoreClient->collection('pokemon')
->documents([
'explainOptions' => $explainOptions
]);
foreach ($snapshot as $pokemon) {
printf("Name: " . $pokemon['name'] . "\n");
}
var_dump($snapshot->getExplainMetrics());
```
b/2F364935279

feat: Add the ExplainOptions class support

---

.github/workflows/conformance-tests-bigtable-proxy.yaml
Bigtable/src/Table.php

fix(Bigtable): always set rowsLimit to 1 for readRow requests

---

Spanner/src/Database.php
Spanner/tests/System/ReadTest.php
Spanner/tests/Unit/DatabaseTest.php

Add documentation and support for the `orderBy` and `lockHint` options.
This consists mostly on adding documentation as the options are already being passed to the GAPIC client and the server validates the type.

feat: Ordering and lock options

---

BigQuery/src/BigQueryClient.php
dev/src/DocFx/Node/ParameterNode.php

Currently, phpdoc will separate field names at "." which causes issues in our docs. This commit fixes it.

fix: Support dot notation in docs

---

.github/workflows/release-checks.yaml

Should fix the following error we've been seeing intermittently in our release PRs:

fix(ci): add token to prevent rate limit error in release check

---

CONTRIBUTING.md
composer.json

Now you can run both styles checkers with one line:
```sh
composer style-check
```
And if that fails you can fix it with another one-liner:
```sh
composer style-fix
```
And for consistency, you can also use `composer phpstan` as a shortcut to running `dev/sh/static-analysis`:
```sh
composer phpstan
```

feat(ci): add scripts to quickly check and fix code styles

---

Core/src/RestTrait.php
Storage/src/Connection/Rest.php
Storage/src/Connection/RetryTrait.php
Storage/src/StorageClient.php
Storage/tests/Unit/StorageClientTest.php

- fixed support for retry strategy
- override support for - delay function, calc delay function, retry function
- added restDelayFunction and restCalcDelayFunction support for RestTrait.
- added phpDoc for `StorageClient` on available options
- fixed language typos
- fixed minor formatting issues
Fixes #8309.

fix: retry options for Storage Client.

---

Spanner/src/Database.php
Spanner/src/TransactionalReadTrait.php
Spanner/tests/System/ReadTest.php
Spanner/tests/System/SnapshotTest.php
Spanner/tests/System/TransactionTest.php

The LockHint is only used for read-write transactions. This change fixes the previous version where this was not documented.
This documentation is also added to the Snapshot::Read method as it is internally using the `transactionalReadTrait` for `$snapshot->read()`.

feat: Add documentation for Snapshot and Transaction for lockHint

---

AUTHENTICATION.md
BigQuery/src/BigQueryClient.php
Bigtable/src/BigtableClient.php
Core/src/RequestWrapperTrait.php
Core/src/ServiceBuilder.php
Datastore/src/DatastoreClient.php
Firestore/src/FirestoreClient.php
Logging/src/LoggingClient.php
PubSub/src/PubSubClient.php
Spanner/src/SpannerClient.php
Storage/src/Bucket.php
Storage/src/SigningHelper.php
Storage/src/StorageClient.php
Storage/src/StorageObject.php
Trace/src/TraceClient.php
dev/tests/fixtures/docfx/ProductNeutralGuides/authentication.md

See 
- https://github.com/googleapis/google-auth-library-php/pull/624
- https://github.com/googleapis/gax-php/pull/631
- https://github.com/googleapis/gapic-generator-php/pull/780
b/437993663

fix: mark all keyFile and keyFilePath options deprecated

---

Core/src/ApiHelperTrait.php
Core/tests/Unit/ApiHelperTraitTest.php
Core/tests/Unit/Stubs/ApiHelpersTraitImpl.php

We decided to remove the use of the serializer method on the `validateOptions` method as it makes certain cases more complicated to utilize.

feat: Validate options no serializer

---

dev/src/Command/RepoInfoCommand.php
dev/src/Packagist.php

clean up `repo-info` output and show the packagist maintainers for a package as well:
**Before**
```
+----------------------------------------+------------+--------------+----------+-----------+-----------------+--------------------+
| Name                                   | Has Issues | Has Projects | Has Wiki | Has Pages | Has Discussions | Teams              |
+----------------------------------------+------------+--------------+----------+-----------+-----------------+--------------------+
| google-cloud-php-access-approval       | false      | false        | false    | false     | false           | **Token Required** |
```
**After**
```
+----------------------------------------+--------------------+------------------+--------------------+
| Name                                   | …
```

feat(dev): add packagist complaince check

---

Spanner/src/Connection/Grpc.php
Spanner/src/Database.php
Spanner/src/TransactionConfigurationTrait.php
Spanner/tests/Unit/DatabaseTest.php
Spanner/tests/Unit/OperationTest.php

Feature to add `ReadLockMode` option for `ReadWrite` transactions only. Two ways users can set the option -
1) Set it on the base `transactionOption` array like any other txn option. This provides consistency with how our other option configurations work 
2) Set it directly on the `readWrite` options inside the `transactionOption` array. This provides flexibility for the user since the readLockMode is a special nested option inside of the readWrite.
Some comment changes to be in accordance with this new feature and unit tests have been added.

feat: Support for Spanner ReadLockMode
